/*
 * drivers/video/tegra/host/gk20a/gk20a_gating_reglist.h
 *
 * Copyright (c) 2012-2014, NVIDIA Corporation.  All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This file is autogenerated.  Do not edit.
 */

#include "gk20a.h"

void gr_gk20a_slcg_gr_load_gating_prod(struct gk20a *g,
	bool prod);

void gr_gk20a_slcg_perf_load_gating_prod(struct gk20a *g,
	bool prod);

void ltc_gk20a_slcg_ltc_load_gating_prod(struct gk20a *g,
	bool prod);

void gr_gk20a_blcg_gr_load_gating_prod(struct gk20a *g,
	bool prod);

void gr_gk20a_pg_gr_load_gating_prod(struct gk20a *g,
	bool prod);

void gr_gk20a_slcg_therm_load_gating_prod(struct gk20a *g,
	bool prod);


