GCOV_PROFILE := y
#subdir-ccflags-y := -Werror

obj-$(CONFIG_TEGRA_NVMAP)  += $(call tegra-path,nvmap/,drivers/video/tegra/nvmap/)
obj-$(CONFIG_TEGRA_GRHOST) += $(call tegra-path,nvhost/,drivers/video/tegra/host/)
