obj-$(CONFIG_TEGRA_CAMERA_PLATFORM) += camera/
obj-y += host/
obj-$(CONFIG_TEGRA_NVMAP) += nvmap/

GCOV_PROFILE := y
#subdir-ccflags-y := -Werror

obj-$(CONFIG_TEGRA_DC) += dc/
obj-$(CONFIG_FB_TEGRA) += fb.o
