GCOV_PROFILE := y
#subdir-ccflags-y := -Werror

obj-$(CONFIG_TEGRA_GRHOST) += $(call tegra-path,nvhost/,drivers/video/tegra/host/)
obj-$(CONFIG_TEGRA_GR_VIRTUALIZATION) += virt/
obj-y += $(call tegra-path,display,drivers/video/tegra/)
