GCOV_PROFILE := y
ccflags-y += -I$(srctree)/../nvhost/drivers/video/tegra/host
ccflags-y += -Idrivers/video/tegra/host
ccflags-y += -Iarch/arm/mach-tegra

ifeq ($(CONFIG_TEGRA_T19X_GRHOST),y)
ccflags-y += -I$(srctree)/../nvhost-t19x/drivers/video/tegra/host/
endif

nvhost-nvdec-objs  = \
	nvdec.o

obj-$(CONFIG_TEGRA_GRHOST) += nvhost-nvdec.o
