GCOV_PROFILE := y
ccflags-y += -I$(srctree)/../nvhost/drivers/video/tegra/host
ccflags-y += -Idrivers/video/tegra/host
ccflags-y += -Idrivers/video/tegra/camera
ccflags-y += -Werror

nvhost-isp-objs  = \
		isp_isr_v1.o \
		isp.o

obj-$(CONFIG_TEGRA_GRHOST_ISP) += nvhost-isp.o

ifeq ($(CONFIG_ARCH_TEGRA_18x_SOC),y)
nvhost-isp-t186-objs  = \
		isp_isr_v2.o

obj-$(CONFIG_TEGRA_GRHOST_ISP) += nvhost-isp-t186.o
endif
