GCOV_PROFILE := y
EXTRA_CFLAGS += -I../kernel-nvhost/drivers/video/tegra/host
ccflags-y += -I$(srctree)/arch/arm/mach-tegra/include/mach
obj-y += dev.o
obj-y += util.o
obj-y += cursor.o
obj-y += events.o
obj-y += control.o
