GCOV_PROFILE := y
obj-y				+= vi/
obj-y				+= csi/
ccflags-y += -I../nvhost/drivers/video/tegra/host
ccflags-y += -Idrivers/video/tegra/host
ccflags-y += -Idrivers/video/tegra/camera
ccflags-y += -Idrivers/media/platform/tegra
ccflags-y += -Werror

obj-y += camera_common.o camera_gpio.o sensor_common.o
