GCOV_PROFILE := y
ccflags-y += -I../kernel-nvhost/drivers/video/tegra/host
ccflags-y += -Idrivers/video/tegra/camera
ccflags-y += -Idrivers/media/platform/tegra/vi
ccflags-y += -Werror

obj-y += camera_common.o mc_common.o core.o channel.o graph.o camera_gpio.o
