/* To merge back to "dt-bindings/memory/tegra-swgroup.h" */
#define TEGRA_SWGROUP_NVCSI	45
#define TEGRA_SWGROUP_SCE	52
#define TEGRA_SWGROUP_HOST1X_CTX0	53
#define TEGRA_SWGROUP_HOST1X_CTX1	54
#define TEGRA_SWGROUP_HOST1X_CTX2	55
#define TEGRA_SWGROUP_HOST1X_CTX3	56
#define TEGRA_SWGROUP_HOST1X_CTX4	57
#define TEGRA_SWGROUP_HOST1X_CTX5	58
#define TEGRA_SWGROUP_HOST1X_CTX6	59
#define TEGRA_SWGROUP_HOST1X_CTX7	60
#define TEGRA_SWGROUP_SE2		61
#define TEGRA_SWGROUP_SE3		62
