/* To merge back to "dt-bindings/memory/tegra-swgroup.h" */
#define TEGRA_SWGROUP_NVCSI	45
#define TEGRA_SWGROUP_SCE	52
#define TEGRA_SWGROUP_HOST1X_CTX0	53
#define TEGRA_SWGROUP_HOST1X_CTX1	54
#define TEGRA_SWGROUP_HOST1X_CTX2	55
#define TEGRA_SWGROUP_HOST1X_CTX3	56
#define TEGRA_SWGROUP_HOST1X_CTX4	57
#define TEGRA_SWGROUP_HOST1X_CTX5	58
#define TEGRA_SWGROUP_HOST1X_CTX6	59
#define TEGRA_SWGROUP_HOST1X_CTX7	60
#define TEGRA_SWGROUP_SE2		61
#define TEGRA_SWGROUP_SE3		62

#define TEGRA_SID_GPCDMA_0	46	/* Same as SWGROUP_AXIS */
#define TEGRA_SID_GPCDMA_1	63
#define TEGRA_SID_GPCDMA_2	65
#define TEGRA_SID_GPCDMA_3	66
#define TEGRA_SID_GPCDMA_4	67
#define TEGRA_SID_GPCDMA_5	68
#define TEGRA_SID_GPCDMA_6	69
#define TEGRA_SID_GPCDMA_7	70
