GCOV_PROFILE := y
subdir-ccflags-y := -Werror
ccflags-y += -I$(srctree)/../display/drivers/video/tegra/dc
ccflags-y += -I$(srctree)/../t18x/drivers/video/tegra/dc/nvdisp

ifeq ($(CONFIG_ARCH_TEGRA_19x_SOC),y)
        obj-$(CONFIG_TEGRA_NVDISPLAY) += sor_t19x.o
        obj-$(CONFIG_TEGRA_NVDISPLAY) += nvdisp/
        obj-$(CONFIG_TEGRA_NVDISPLAY) += ext/
endif
