GCOV_PROFILE := y

subdir-ccflags-y := -Werror

ccflags-y += -I$(srctree)/../nvmap/drivers/video/tegra/nvmap/
ccflags-y += -I$(srctree)/../nvmap-t19x/include/

obj-y += nvmap_init_t19x.o
obj-y += nvmap_dmabuf_t19x.o
obj-y += nvmap_cache_t19x.o
