GCOV_PROFILE := y
#ccflags-y += -Iarch/arm/mach-tegra/
ccflags-y += -Idrivers/video/tegra/host
ccflags-y += -Idrivers/video/tegra/camera
ccflags-y += -I$(TEGRA_TOP)/gpu/drv/sdk/nvidia/inc/hwref/t21x
ccflags-y += -Werror

obj-$(CONFIG_TEGRA_GRHOST_VII2C) += vii2c.o
