GCOV_PROFILE := y
ccflags-y += -Idrivers/video/tegra/host
ccflags-y += -Idrivers/video/tegra/host/t124
ccflags-y += -Wno-multichar
ccflags-y += -Werror

nvhost-t186-objs  = \
        t186.o

obj-$(CONFIG_TEGRA_GRHOST) += nvhost-t186.o
