/*
 * Copyright (c) 2015, NVIDIA CORPORATION.  All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed in the hope it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 */

#ifndef _DT_BINDINGS_PADCTRL_TEGRA186_PADS_H
#define _DT_BINDINGS_PADCTRL_TEGRA186_PADS_H

/* IO PAD group */
#define TEGRA_IO_PAD_GROUP_AUDIO	0
#define TEGRA_IO_PAD_GROUP_AUDIO_HV	1
#define TEGRA_IO_PAD_GROUP_CAM		2
#define TEGRA_IO_PAD_GROUP_CSIA		3
#define TEGRA_IO_PAD_GROUP_CSIB		4
#define TEGRA_IO_PAD_GROUP_CSIC		5
#define TEGRA_IO_PAD_GROUP_CSID		6
#define TEGRA_IO_PAD_GROUP_CSIE		7
#define TEGRA_IO_PAD_GROUP_CSIF		8
#define TEGRA_IO_PAD_GROUP_DBG		9
#define TEGRA_IO_PAD_GROUP_DEBUG_NONAO	10
#define TEGRA_IO_PAD_GROUP_DMIC		11
#define TEGRA_IO_PAD_GROUP_DP		12
#define TEGRA_IO_PAD_GROUP_DSI		13
#define TEGRA_IO_PAD_GROUP_DSIB		14
#define TEGRA_IO_PAD_GROUP_DSIC		15
#define TEGRA_IO_PAD_GROUP_DSID		16
#define TEGRA_IO_PAD_GROUP_EMMC		17
#define TEGRA_IO_PAD_GROUP_EMMC2	18
#define TEGRA_IO_PAD_GROUP_GPIO		19
#define TEGRA_IO_PAD_GROUP_HDMI		20
#define TEGRA_IO_PAD_GROUP_HSIC		21
#define TEGRA_IO_PAD_GROUP_LVDS		22
#define TEGRA_IO_PAD_GROUP_MIPI_BIAS	23
#define TEGRA_IO_PAD_GROUP_PEX_BIAS	24
#define TEGRA_IO_PAD_GROUP_PEX_CLK1	25
#define TEGRA_IO_PAD_GROUP_PEX_CLK2	26
#define TEGRA_IO_PAD_GROUP_PEX_CTRL	27
#define TEGRA_IO_PAD_GROUP_SDMMC1	28
#define TEGRA_IO_PAD_GROUP_SDMMC3	29
#define TEGRA_IO_PAD_GROUP_SPI		30
#define TEGRA_IO_PAD_GROUP_SPI_HV	31
#define TEGRA_IO_PAD_GROUP_UART		32
#define TEGRA_IO_PAD_GROUP_USB_BIAS	33
#define TEGRA_IO_PAD_GROUP_USB0		34
#define TEGRA_IO_PAD_GROUP_USB1		35
#define TEGRA_IO_PAD_GROUP_USB2		36
#define TEGRA_IO_PAD_GROUP_USB3		37
#define TEGRA_IO_PAD_GROUP_BB		38
#define TEGRA_IO_PAD_GROUP_SYS		39
#define TEGRA_IO_PAD_GROUP_HV		40
#define TEGRA_IO_PAD_GROUP_CONN		41
#define TEGRA_IO_PAD_GROUP_EDP		42
#define TEGRA_IO_PAD_GROUP_UFS		43
#define TEGRA_IO_PAD_GROUP_MEM		44
#define TEGRA_IO_PAD_GROUP_MEM1		45
#define TEGRA_IO_PAD_GROUP_MIPI		46
#define TEGRA_IO_PAD_GROUP_SDMMC4	47
#define TEGRA_IO_PAD_GROUP_SDMMC1_HV	48
#define TEGRA_IO_PAD_GROUP_MEM_COMP	49
#define TEGRA_IO_PAD_GROUP_MEM1_COMP	50
#define TEGRA_IO_PAD_GROUP_SDMMC2	51
#define TEGRA_IO_PAD_GROUP_AO		52
#define TEGRA_IO_PAD_GROUP_AO_HV	53
#define TEGRA_IO_PAD_GROUP_DMIC_HV	54
#define TEGRA_IO_PAD_GROUP_GPIO_HV	55
#define TEGRA_IO_PAD_GROUP_SDMMC2_HV	56
#define TEGRA_IO_PAD_GROUP_SDMMC3_HV	57
#define TEGRA_IO_PAD_GROUP_DDR_DVI	58
#define TEGRA_IO_PAD_GROUP_DDR_GMI	59
#define TEGRA_IO_PAD_GROUP_DDR_SDMMC2	60
#define TEGRA_IO_PAD_GROUP_DDR_SPI	61

#define IO_PAD_VOLTAGE_1_2V	1200000
#define IO_PAD_VOLTAGE_1_8V	1800000
#define IO_PAD_VOLTAGE_3_3V	3300000

#endif
