GCOV_PROFILE := y
EXTRA_CFLAGS += -Idrivers/video/tegra/host
EXTRA_CFLAGS += -Idrivers/video/tegra/camera
EXTRA_CFLAGS += -Idrivers/video/tegra/host/t124

nvhost-t210-objs  = \
        t210.o

obj-$(CONFIG_TEGRA_GRHOST) += nvhost-t210.o
