/*
 * Copyright (c) 2015, NVIDIA CORPORATION.  All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed in the hope it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef __ABI_MACH_T186_POWERGATE_T186_H_
#define __ABI_MACH_T186_POWERGATE_T186_H_

#define TEGRA186_POWER_DOMAIN_AUD	0
#define TEGRA186_POWER_DOMAIN_DFD	1
#define TEGRA186_POWER_DOMAIN_DISP	2
#define TEGRA186_POWER_DOMAIN_DISPB	3
#define TEGRA186_POWER_DOMAIN_DISPC	4
#define TEGRA186_POWER_DOMAIN_ISPA	5
#define TEGRA186_POWER_DOMAIN_NVDEC	6
#define TEGRA186_POWER_DOMAIN_NVJPG	7
#define TEGRA186_POWER_DOMAIN_MPE	8
#define TEGRA186_POWER_DOMAIN_PCX	9
#define TEGRA186_POWER_DOMAIN_SAX	10
#define TEGRA186_POWER_DOMAIN_VE	11
#define TEGRA186_POWER_DOMAIN_VIC	12
#define TEGRA186_POWER_DOMAIN_XUSBA	13
#define TEGRA186_POWER_DOMAIN_XUSBB	14
#define TEGRA186_POWER_DOMAIN_XUSBC	15
#define TEGRA186_POWER_DOMAIN_SCRATCH	16
#define TEGRA186_POWER_DOMAIN_AONPG	17
#define TEGRA186_POWER_DOMAIN_CAR	18
#define TEGRA186_POWER_DOMAIN_EMCA	19
#define TEGRA186_POWER_DOMAIN_EMCB	20
#define TEGRA186_POWER_DOMAIN_HOST	21
#define TEGRA186_POWER_DOMAIN_MCA	22
#define TEGRA186_POWER_DOMAIN_MCB	23
#define TEGRA186_POWER_DOMAIN_MCHA	24
#define TEGRA186_POWER_DOMAIN_MCHB	25
#define TEGRA186_POWER_DOMAIN_MCHBB	26
#define TEGRA186_POWER_DOMAIN_NIC	27
#define TEGRA186_POWER_DOMAIN_SEC	28
#define TEGRA186_POWER_DOMAIN_UFS	29
#define TEGRA186_POWER_DOMAIN_BPMP	30
#define TEGRA186_POWER_DOMAIN_SCE	31
#define TEGRA186_POWER_DOMAIN_AOPG_TCM0	32
#define TEGRA186_POWER_DOMAIN_AOPG_TCM1	33
#define TEGRA186_POWER_DOMAIN_AOPG_TCM2	34
#define TEGRA186_POWER_DOMAIN_AOPG_TCM3	35
#define TEGRA186_POWER_DOMAIN_AOPG_TCM4	36
#define TEGRA186_POWER_DOMAIN_AOPG_TCM5	37
#define TEGRA186_POWER_DOMAIN_AOPG_TCM6	38
#define TEGRA186_POWER_DOMAIN_AOPG_TCM7	39
#define TEGRA186_POWER_DOMAIN_AOPG_CACHE	40
#define TEGRA186_POWER_DOMAIN_AOPG_CAN0	41
#define TEGRA186_POWER_DOMAIN_AOPG_CAN1	42
#define TEGRA186_POWER_DOMAIN_GPU	43
#define TEGRA186_POWER_DOMAIN_MAX	44

#endif
