GCOV_PROFILE := y
ccflags-y += -Idrivers/gpu/nvgpu
ccflags-y += -Wno-multichar

obj-$(CONFIG_GK20A)  = \
	hal_gm20b.o \
	ltc_gm20b.o \
	gr_gm20b.o \
	gr_gm20b.o \
	fb_gm20b.o \
	fifo_gm20b.o \
	gr_ctx_gm20b.o \
	gm20b_gating_reglist.o
