GCOV_PROFILE := y
ccflags-y += -I$(srctree)/../nvhost/drivers/video/tegra/host
ccflags-y += -I$(srctree)/../nvidia/drivers/video/tegra/camera
ccflags-y += -I$(srctree)/../nvidia/drivers/media/platform/tegra
ccflags-y += -I$(srctree)/../nvidia/drivers/video/tegra/host
ccflags-y += -I$(srctree)/../nvhost/include
ccflags-y += -I$(srctree)/../nvidia/include
ccflags-y += -I$(srctree)/../t19x/include
ccflags-y += -Werror

obj-y += vi5_fops.o
