GCOV_PROFILE := y
ccflags-y += -I$(srctree)/../nvhost/drivers/video/tegra/host
ccflags-y += -Idrivers/video/tegra/host
ccflags-y += -Werror

ifeq ($(CONFIG_TEGRA_T19X_GRHOST),y)
ccflags-y += -I$(srctree)/../nvhost-t19x/drivers/video/tegra/host/
endif

nvhost-host1x-objs  = \
	host1x.o

obj-$(CONFIG_TEGRA_GRHOST) += nvhost-host1x.o
