ifdef CONFIG_ARCH_TEGRA_19x_SOC

obj-$(CONFIG_TEGRA_CENTRAL_ACTMON) += cactmon_t19x.o
obj-y += t19x_mce.o
obj-y += t19x_cache.o
obj-y += cvnas.o
obj-$(CONFIG_TEGRA_19X_RAS) += carmel_ras.o
obj-$(CONFIG_TEGRA_CBB_NOC) += tegra_cbb.o

endif
