subdir-ccflags-y += -Werror

ccflags-y += -I$(srctree)/drivers/media/platform/tegra
ccflags-y += -I$(srctree)/drivers/video/tegra/camera

ccflags-y += -DT19x_uFPGA

obj-$(CONFIG_VIDEO_IMX204) += imx204.o
