#
# Makefile for Hypervisor interface
#

obj-$(CONFIG_TEGRA_VIRTUALIZATION)	+= hyp_syscall.o sys.o
obj-$(CONFIG_TEGRA_HV_MANAGER)		+= tegra_hv.o tegra-ivc.o
obj-$(CONFIG_TEGRA_HV_MANAGER)		+= hv_sys_test.o
