GCOV_PROFILE := y

ccflags-y += -I$(srctree)/../kernel-t18x/drivers/video/tegra/host
ccflags-y += -I$(srctree)/drivers/video/tegra/host
obj-$(CONFIG_CRYPTO_DEV_TEGRA_SE_USE_HOST1X_INTERFACE) += tegra-se-nvhost.o
