GCOV_PROFILE := y
ccflags-y += -I$(srctree)/../nvidia/drivers/video/tegra/host
ccflags-y += -I$(srctree)/drivers/video/tegra/host
ccflags-y += -I$(srctree)/../nvidia/drivers/media/platform/tegra/

obj-y += tegra_camera_platform.o
obj-y += tegra_camera_dev_mfi.o
