/*
 * drivers/video/tegra/host/gk20a/hw_bus_gk20a.h
 *
 * Copyright (c) 2012, NVIDIA Corporation.
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed in the hope it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

 /*
  * Function naming determines intended use:
  *
  *     <x>_r(void) : Returns the offset for register <x>.
  *
  *     <x>_w(void) : Returns the word offset for word (4 byte) element <x>.
  *
  *     <x>_<y>_s(void) : Returns size of field <y> of register <x> in bits.
  *
  *     <x>_<y>_f(u32 v) : Returns a value based on 'v' which has been shifted
  *         and masked to place it at field <y> of register <x>.  This value
  *         can be |'d with others to produce a full register value for
  *         register <x>.
  *
  *     <x>_<y>_m(void) : Returns a mask for field <y> of register <x>.  This
  *         value can be ~'d and then &'d to clear the value of field <y> for
  *         register <x>.
  *
  *     <x>_<y>_<z>_f(void) : Returns the constant value <z> after being shifted
  *         to place it at field <y> of register <x>.  This value can be |'d
  *         with others to produce a full register value for <x>.
  *
  *     <x>_<y>_v(u32 r) : Returns the value of field <y> from a full register
  *         <x> value 'r' after being shifted to place its LSB at bit 0.
  *         This value is suitable for direct comparison with other unshifted
  *         values appropriate for use in field <y> of register <x>.
  *
  *     <x>_<y>_<z>_v(void) : Returns the constant value for <z> defined for
  *         field <y> of register <x>.  This value is suitable for direct
  *         comparison with unshifted values appropriate for use in field <y>
  *         of register <x>.
  */

#ifndef __hw_bus_gk20a_h__
#define __hw_bus_gk20a_h__
/*This file is autogenerated.  Do not edit. */

static inline u32 bus_bar1_block_r(void)
{
	return 0x00001704;
}
static inline u32 bus_bar1_block_map_s(void)
{
	return 30;
}
static inline u32 bus_bar1_block_map_f(u32 v)
{
	return (v & 0x3fffffff) << 0;
}
static inline u32 bus_bar1_block_map_m(void)
{
	return 0x3fffffff << 0;
}
static inline u32 bus_bar1_block_map_v(u32 r)
{
	return (r >> 0) & 0x3fffffff;
}
static inline u32 bus_bar1_block_ptr_s(void)
{
	return 28;
}
static inline u32 bus_bar1_block_ptr_f(u32 v)
{
	return (v & 0xfffffff) << 0;
}
static inline u32 bus_bar1_block_ptr_m(void)
{
	return 0xfffffff << 0;
}
static inline u32 bus_bar1_block_ptr_v(u32 r)
{
	return (r >> 0) & 0xfffffff;
}
static inline u32 bus_bar1_block_ptr_0_v(void)
{
	return 0x00000000;
}
static inline u32 bus_bar1_block_ptr_0_f(void)
{
	return 0x0;
}
static inline u32 bus_bar1_block_target_s(void)
{
	return 2;
}
static inline u32 bus_bar1_block_target_f(u32 v)
{
	return (v & 0x3) << 28;
}
static inline u32 bus_bar1_block_target_m(void)
{
	return 0x3 << 28;
}
static inline u32 bus_bar1_block_target_v(u32 r)
{
	return (r >> 28) & 0x3;
}
static inline u32 bus_bar1_block_target_vid_mem_v(void)
{
	return 0x00000000;
}
static inline u32 bus_bar1_block_target_vid_mem_f(void)
{
	return 0x0;
}
static inline u32 bus_bar1_block_target_sys_mem_coherent_v(void)
{
	return 0x00000002;
}
static inline u32 bus_bar1_block_target_sys_mem_coherent_f(void)
{
	return 0x20000000;
}
static inline u32 bus_bar1_block_target_sys_mem_noncoherent_v(void)
{
	return 0x00000003;
}
static inline u32 bus_bar1_block_target_sys_mem_noncoherent_f(void)
{
	return 0x30000000;
}
static inline u32 bus_bar1_block_mode_s(void)
{
	return 1;
}
static inline u32 bus_bar1_block_mode_f(u32 v)
{
	return (v & 0x1) << 31;
}
static inline u32 bus_bar1_block_mode_m(void)
{
	return 0x1 << 31;
}
static inline u32 bus_bar1_block_mode_v(u32 r)
{
	return (r >> 31) & 0x1;
}
static inline u32 bus_bar1_block_mode_physical_v(void)
{
	return 0x00000000;
}
static inline u32 bus_bar1_block_mode_physical_f(void)
{
	return 0x0;
}
static inline u32 bus_bar1_block_mode_virtual_v(void)
{
	return 0x00000001;
}
static inline u32 bus_bar1_block_mode_virtual_f(void)
{
	return 0x80000000;
}
static inline u32 bus_bar1_block_ptr_shift_v(void)
{
	return 12;
}

#endif /* __hw_bus_gk20a_h__ */
