/*
 * drivers/video/tegra/host/gk20a/hw_ram_gk20a.h
 *
 * Copyright (c) 2012, NVIDIA Corporation.
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed in the hope it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

 /*
  * Function naming determines intended use:
  *
  *     <x>_r(void) : Returns the offset for register <x>.
  *
  *     <x>_w(void) : Returns the word offset for word (4 byte) element <x>.
  *
  *     <x>_<y>_s(void) : Returns size of field <y> of register <x> in bits.
  *
  *     <x>_<y>_f(u32 v) : Returns a value based on 'v' which has been shifted
  *         and masked to place it at field <y> of register <x>.  This value
  *         can be |'d with others to produce a full register value for
  *         register <x>.
  *
  *     <x>_<y>_m(void) : Returns a mask for field <y> of register <x>.  This
  *         value can be ~'d and then &'d to clear the value of field <y> for
  *         register <x>.
  *
  *     <x>_<y>_<z>_f(void) : Returns the constant value <z> after being shifted
  *         to place it at field <y> of register <x>.  This value can be |'d
  *         with others to produce a full register value for <x>.
  *
  *     <x>_<y>_v(u32 r) : Returns the value of field <y> from a full register
  *         <x> value 'r' after being shifted to place its LSB at bit 0.
  *         This value is suitable for direct comparison with other unshifted
  *         values appropriate for use in field <y> of register <x>.
  *
  *     <x>_<y>_<z>_v(void) : Returns the constant value for <z> defined for
  *         field <y> of register <x>.  This value is suitable for direct
  *         comparison with unshifted values appropriate for use in field <y>
  *         of register <x>.
  */

#ifndef __hw_ram_gk20a_h__
#define __hw_ram_gk20a_h__
/*This file is autogenerated.  Do not edit. */

static inline u32 ram_in_base_shift_v(void)
{
	return 12;
}
static inline u32 ram_in_alloc_size_v(void)
{
	return 4096;
}
static inline u32 ram_in_ramfc_w(void)
{
	return 0;
}
static inline u32 ram_in_ramfc_s(void)
{
	return 4096;
}
static inline u32 ram_in_ramfc_f(u32 v)
{
	return (v & 0x0) << 0;
}
static inline u32 ram_in_ramfc_m(void)
{
	return 0x0 << 0;
}
static inline u32 ram_in_ramfc_v(u32 r)
{
	return (r >> 0) & 0x0;
}
static inline u32 ram_in_page_dir_base_target_w(void)
{
	return 128;
}
static inline u32 ram_in_page_dir_base_target_s(void)
{
	return 2;
}
static inline u32 ram_in_page_dir_base_target_f(u32 v)
{
	return (v & 0x3) << 0;
}
static inline u32 ram_in_page_dir_base_target_m(void)
{
	return 0x3 << 0;
}
static inline u32 ram_in_page_dir_base_target_v(u32 r)
{
	return (r >> 0) & 0x3;
}
static inline u32 ram_in_page_dir_base_target_vid_mem_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_page_dir_base_target_vid_mem_f(void)
{
	return 0x0;
}
static inline u32 ram_in_page_dir_base_target_sys_mem_coherent_v(void)
{
	return 0x00000002;
}
static inline u32 ram_in_page_dir_base_target_sys_mem_coherent_f(void)
{
	return 0x2;
}
static inline u32 ram_in_page_dir_base_target_sys_mem_noncoherent_v(void)
{
	return 0x00000003;
}
static inline u32 ram_in_page_dir_base_target_sys_mem_noncoherent_f(void)
{
	return 0x3;
}
static inline u32 ram_in_page_dir_base_vol_w(void)
{
	return 128;
}
static inline u32 ram_in_page_dir_base_vol_s(void)
{
	return 1;
}
static inline u32 ram_in_page_dir_base_vol_f(u32 v)
{
	return (v & 0x1) << 2;
}
static inline u32 ram_in_page_dir_base_vol_m(void)
{
	return 0x1 << 2;
}
static inline u32 ram_in_page_dir_base_vol_v(u32 r)
{
	return (r >> 2) & 0x1;
}
static inline u32 ram_in_page_dir_base_vol_true_v(void)
{
	return 0x00000001;
}
static inline u32 ram_in_page_dir_base_vol_true_f(void)
{
	return 0x4;
}
static inline u32 ram_in_page_dir_base_vol_false_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_page_dir_base_vol_false_f(void)
{
	return 0x0;
}
static inline u32 ram_in_page_dir_base_lo_w(void)
{
	return 128;
}
static inline u32 ram_in_page_dir_base_lo_s(void)
{
	return 20;
}
static inline u32 ram_in_page_dir_base_lo_f(u32 v)
{
	return (v & 0xfffff) << 12;
}
static inline u32 ram_in_page_dir_base_lo_m(void)
{
	return 0xfffff << 12;
}
static inline u32 ram_in_page_dir_base_lo_v(u32 r)
{
	return (r >> 12) & 0xfffff;
}
static inline u32 ram_in_page_dir_base_hi_w(void)
{
	return 129;
}
static inline u32 ram_in_page_dir_base_hi_s(void)
{
	return 8;
}
static inline u32 ram_in_page_dir_base_hi_f(u32 v)
{
	return (v & 0xff) << 0;
}
static inline u32 ram_in_page_dir_base_hi_m(void)
{
	return 0xff << 0;
}
static inline u32 ram_in_page_dir_base_hi_v(u32 r)
{
	return (r >> 0) & 0xff;
}
static inline u32 ram_in_adr_limit_lo_w(void)
{
	return 130;
}
static inline u32 ram_in_adr_limit_lo_s(void)
{
	return 20;
}
static inline u32 ram_in_adr_limit_lo_f(u32 v)
{
	return (v & 0xfffff) << 12;
}
static inline u32 ram_in_adr_limit_lo_m(void)
{
	return 0xfffff << 12;
}
static inline u32 ram_in_adr_limit_lo_v(u32 r)
{
	return (r >> 12) & 0xfffff;
}
static inline u32 ram_in_adr_limit_hi_w(void)
{
	return 131;
}
static inline u32 ram_in_adr_limit_hi_s(void)
{
	return 8;
}
static inline u32 ram_in_adr_limit_hi_f(u32 v)
{
	return (v & 0xff) << 0;
}
static inline u32 ram_in_adr_limit_hi_m(void)
{
	return 0xff << 0;
}
static inline u32 ram_in_adr_limit_hi_v(u32 r)
{
	return (r >> 0) & 0xff;
}
static inline u32 ram_in_engine_cs_w(void)
{
	return 132;
}
static inline u32 ram_in_engine_cs_s(void)
{
	return 1;
}
static inline u32 ram_in_engine_cs_f(u32 v)
{
	return (v & 0x1) << 3;
}
static inline u32 ram_in_engine_cs_m(void)
{
	return 0x1 << 3;
}
static inline u32 ram_in_engine_cs_v(u32 r)
{
	return (r >> 3) & 0x1;
}
static inline u32 ram_in_engine_cs_wfi_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_engine_cs_wfi_f(void)
{
	return 0x0;
}
static inline u32 ram_in_engine_cs_fg_v(void)
{
	return 0x00000001;
}
static inline u32 ram_in_engine_cs_fg_f(void)
{
	return 0x8;
}
static inline u32 ram_in_engine_wfi_target_w(void)
{
	return 132;
}
static inline u32 ram_in_engine_wfi_target_s(void)
{
	return 2;
}
static inline u32 ram_in_engine_wfi_target_f(u32 v)
{
	return (v & 0x3) << 0;
}
static inline u32 ram_in_engine_wfi_target_m(void)
{
	return 0x3 << 0;
}
static inline u32 ram_in_engine_wfi_target_v(u32 r)
{
	return (r >> 0) & 0x3;
}
static inline u32 ram_in_engine_wfi_target_local_mem_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_engine_wfi_target_local_mem_f(void)
{
	return 0x0;
}
static inline u32 ram_in_engine_wfi_target_sys_mem_coherent_v(void)
{
	return 0x00000002;
}
static inline u32 ram_in_engine_wfi_target_sys_mem_coherent_f(void)
{
	return 0x2;
}
static inline u32 ram_in_engine_wfi_target_sys_mem_noncoherent_v(void)
{
	return 0x00000003;
}
static inline u32 ram_in_engine_wfi_target_sys_mem_noncoherent_f(void)
{
	return 0x3;
}
static inline u32 ram_in_engine_wfi_mode_w(void)
{
	return 132;
}
static inline u32 ram_in_engine_wfi_mode_s(void)
{
	return 1;
}
static inline u32 ram_in_engine_wfi_mode_f(u32 v)
{
	return (v & 0x1) << 2;
}
static inline u32 ram_in_engine_wfi_mode_m(void)
{
	return 0x1 << 2;
}
static inline u32 ram_in_engine_wfi_mode_v(u32 r)
{
	return (r >> 2) & 0x1;
}
static inline u32 ram_in_engine_wfi_mode_physical_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_engine_wfi_mode_physical_f(void)
{
	return 0x0;
}
static inline u32 ram_in_engine_wfi_mode_virtual_v(void)
{
	return 0x00000001;
}
static inline u32 ram_in_engine_wfi_mode_virtual_f(void)
{
	return 0x4;
}
static inline u32 ram_in_engine_wfi_ptr_lo_w(void)
{
	return 132;
}
static inline u32 ram_in_engine_wfi_ptr_lo_s(void)
{
	return 20;
}
static inline u32 ram_in_engine_wfi_ptr_lo_f(u32 v)
{
	return (v & 0xfffff) << 12;
}
static inline u32 ram_in_engine_wfi_ptr_lo_m(void)
{
	return 0xfffff << 12;
}
static inline u32 ram_in_engine_wfi_ptr_lo_v(u32 r)
{
	return (r >> 12) & 0xfffff;
}
static inline u32 ram_in_engine_wfi_ptr_hi_w(void)
{
	return 133;
}
static inline u32 ram_in_engine_wfi_ptr_hi_s(void)
{
	return 8;
}
static inline u32 ram_in_engine_wfi_ptr_hi_f(u32 v)
{
	return (v & 0xff) << 0;
}
static inline u32 ram_in_engine_wfi_ptr_hi_m(void)
{
	return 0xff << 0;
}
static inline u32 ram_in_engine_wfi_ptr_hi_v(u32 r)
{
	return (r >> 0) & 0xff;
}
static inline u32 ram_in_engine_fg_target_w(void)
{
	return 134;
}
static inline u32 ram_in_engine_fg_target_s(void)
{
	return 2;
}
static inline u32 ram_in_engine_fg_target_f(u32 v)
{
	return (v & 0x3) << 0;
}
static inline u32 ram_in_engine_fg_target_m(void)
{
	return 0x3 << 0;
}
static inline u32 ram_in_engine_fg_target_v(u32 r)
{
	return (r >> 0) & 0x3;
}
static inline u32 ram_in_engine_fg_target_local_mem_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_engine_fg_target_local_mem_f(void)
{
	return 0x0;
}
static inline u32 ram_in_engine_fg_target_sys_mem_coherent_v(void)
{
	return 0x00000002;
}
static inline u32 ram_in_engine_fg_target_sys_mem_coherent_f(void)
{
	return 0x2;
}
static inline u32 ram_in_engine_fg_target_sys_mem_noncoherent_v(void)
{
	return 0x00000003;
}
static inline u32 ram_in_engine_fg_target_sys_mem_noncoherent_f(void)
{
	return 0x3;
}
static inline u32 ram_in_engine_fg_mode_w(void)
{
	return 134;
}
static inline u32 ram_in_engine_fg_mode_s(void)
{
	return 1;
}
static inline u32 ram_in_engine_fg_mode_f(u32 v)
{
	return (v & 0x1) << 2;
}
static inline u32 ram_in_engine_fg_mode_m(void)
{
	return 0x1 << 2;
}
static inline u32 ram_in_engine_fg_mode_v(u32 r)
{
	return (r >> 2) & 0x1;
}
static inline u32 ram_in_engine_fg_mode_physical_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_engine_fg_mode_physical_f(void)
{
	return 0x0;
}
static inline u32 ram_in_engine_fg_mode_virtual_v(void)
{
	return 0x00000001;
}
static inline u32 ram_in_engine_fg_mode_virtual_f(void)
{
	return 0x4;
}
static inline u32 ram_in_engine_fg_ptr_lo_w(void)
{
	return 134;
}
static inline u32 ram_in_engine_fg_ptr_lo_s(void)
{
	return 20;
}
static inline u32 ram_in_engine_fg_ptr_lo_f(u32 v)
{
	return (v & 0xfffff) << 12;
}
static inline u32 ram_in_engine_fg_ptr_lo_m(void)
{
	return 0xfffff << 12;
}
static inline u32 ram_in_engine_fg_ptr_lo_v(u32 r)
{
	return (r >> 12) & 0xfffff;
}
static inline u32 ram_in_engine_fg_ptr_hi_w(void)
{
	return 135;
}
static inline u32 ram_in_engine_fg_ptr_hi_s(void)
{
	return 8;
}
static inline u32 ram_in_engine_fg_ptr_hi_f(u32 v)
{
	return (v & 0xff) << 0;
}
static inline u32 ram_in_engine_fg_ptr_hi_m(void)
{
	return 0xff << 0;
}
static inline u32 ram_in_engine_fg_ptr_hi_v(u32 r)
{
	return (r >> 0) & 0xff;
}
static inline u32 ram_in_gr_cs_w(void)
{
	return 132;
}
static inline u32 ram_in_gr_cs_s(void)
{
	return 1;
}
static inline u32 ram_in_gr_cs_f(u32 v)
{
	return (v & 0x1) << 3;
}
static inline u32 ram_in_gr_cs_m(void)
{
	return 0x1 << 3;
}
static inline u32 ram_in_gr_cs_v(u32 r)
{
	return (r >> 3) & 0x1;
}
static inline u32 ram_in_gr_cs_wfi_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_gr_cs_wfi_f(void)
{
	return 0x0;
}
static inline u32 ram_in_gr_cs_fg_v(void)
{
	return 0x00000001;
}
static inline u32 ram_in_gr_cs_fg_f(void)
{
	return 0x8;
}
static inline u32 ram_in_gr_wfi_target_w(void)
{
	return 132;
}
static inline u32 ram_in_gr_wfi_target_s(void)
{
	return 2;
}
static inline u32 ram_in_gr_wfi_target_f(u32 v)
{
	return (v & 0x3) << 0;
}
static inline u32 ram_in_gr_wfi_target_m(void)
{
	return 0x3 << 0;
}
static inline u32 ram_in_gr_wfi_target_v(u32 r)
{
	return (r >> 0) & 0x3;
}
static inline u32 ram_in_gr_wfi_target_local_mem_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_gr_wfi_target_local_mem_f(void)
{
	return 0x0;
}
static inline u32 ram_in_gr_wfi_target_sys_mem_coherent_v(void)
{
	return 0x00000002;
}
static inline u32 ram_in_gr_wfi_target_sys_mem_coherent_f(void)
{
	return 0x2;
}
static inline u32 ram_in_gr_wfi_target_sys_mem_noncoherent_v(void)
{
	return 0x00000003;
}
static inline u32 ram_in_gr_wfi_target_sys_mem_noncoherent_f(void)
{
	return 0x3;
}
static inline u32 ram_in_gr_wfi_mode_w(void)
{
	return 132;
}
static inline u32 ram_in_gr_wfi_mode_s(void)
{
	return 1;
}
static inline u32 ram_in_gr_wfi_mode_f(u32 v)
{
	return (v & 0x1) << 2;
}
static inline u32 ram_in_gr_wfi_mode_m(void)
{
	return 0x1 << 2;
}
static inline u32 ram_in_gr_wfi_mode_v(u32 r)
{
	return (r >> 2) & 0x1;
}
static inline u32 ram_in_gr_wfi_mode_physical_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_gr_wfi_mode_physical_f(void)
{
	return 0x0;
}
static inline u32 ram_in_gr_wfi_mode_virtual_v(void)
{
	return 0x00000001;
}
static inline u32 ram_in_gr_wfi_mode_virtual_f(void)
{
	return 0x4;
}
static inline u32 ram_in_gr_wfi_ptr_lo_w(void)
{
	return 132;
}
static inline u32 ram_in_gr_wfi_ptr_lo_s(void)
{
	return 20;
}
static inline u32 ram_in_gr_wfi_ptr_lo_f(u32 v)
{
	return (v & 0xfffff) << 12;
}
static inline u32 ram_in_gr_wfi_ptr_lo_m(void)
{
	return 0xfffff << 12;
}
static inline u32 ram_in_gr_wfi_ptr_lo_v(u32 r)
{
	return (r >> 12) & 0xfffff;
}
static inline u32 ram_in_gr_wfi_ptr_hi_w(void)
{
	return 133;
}
static inline u32 ram_in_gr_wfi_ptr_hi_s(void)
{
	return 8;
}
static inline u32 ram_in_gr_wfi_ptr_hi_f(u32 v)
{
	return (v & 0xff) << 0;
}
static inline u32 ram_in_gr_wfi_ptr_hi_m(void)
{
	return 0xff << 0;
}
static inline u32 ram_in_gr_wfi_ptr_hi_v(u32 r)
{
	return (r >> 0) & 0xff;
}
static inline u32 ram_in_gr_fg_target_w(void)
{
	return 134;
}
static inline u32 ram_in_gr_fg_target_s(void)
{
	return 2;
}
static inline u32 ram_in_gr_fg_target_f(u32 v)
{
	return (v & 0x3) << 0;
}
static inline u32 ram_in_gr_fg_target_m(void)
{
	return 0x3 << 0;
}
static inline u32 ram_in_gr_fg_target_v(u32 r)
{
	return (r >> 0) & 0x3;
}
static inline u32 ram_in_gr_fg_target_local_mem_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_gr_fg_target_local_mem_f(void)
{
	return 0x0;
}
static inline u32 ram_in_gr_fg_target_sys_mem_coherent_v(void)
{
	return 0x00000002;
}
static inline u32 ram_in_gr_fg_target_sys_mem_coherent_f(void)
{
	return 0x2;
}
static inline u32 ram_in_gr_fg_target_sys_mem_noncoherent_v(void)
{
	return 0x00000003;
}
static inline u32 ram_in_gr_fg_target_sys_mem_noncoherent_f(void)
{
	return 0x3;
}
static inline u32 ram_in_gr_fg_mode_w(void)
{
	return 134;
}
static inline u32 ram_in_gr_fg_mode_s(void)
{
	return 1;
}
static inline u32 ram_in_gr_fg_mode_f(u32 v)
{
	return (v & 0x1) << 2;
}
static inline u32 ram_in_gr_fg_mode_m(void)
{
	return 0x1 << 2;
}
static inline u32 ram_in_gr_fg_mode_v(u32 r)
{
	return (r >> 2) & 0x1;
}
static inline u32 ram_in_gr_fg_mode_physical_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_gr_fg_mode_physical_f(void)
{
	return 0x0;
}
static inline u32 ram_in_gr_fg_mode_virtual_v(void)
{
	return 0x00000001;
}
static inline u32 ram_in_gr_fg_mode_virtual_f(void)
{
	return 0x4;
}
static inline u32 ram_in_gr_fg_ptr_lo_w(void)
{
	return 134;
}
static inline u32 ram_in_gr_fg_ptr_lo_s(void)
{
	return 20;
}
static inline u32 ram_in_gr_fg_ptr_lo_f(u32 v)
{
	return (v & 0xfffff) << 12;
}
static inline u32 ram_in_gr_fg_ptr_lo_m(void)
{
	return 0xfffff << 12;
}
static inline u32 ram_in_gr_fg_ptr_lo_v(u32 r)
{
	return (r >> 12) & 0xfffff;
}
static inline u32 ram_in_gr_fg_ptr_hi_w(void)
{
	return 135;
}
static inline u32 ram_in_gr_fg_ptr_hi_s(void)
{
	return 8;
}
static inline u32 ram_in_gr_fg_ptr_hi_f(u32 v)
{
	return (v & 0xff) << 0;
}
static inline u32 ram_in_gr_fg_ptr_hi_m(void)
{
	return 0xff << 0;
}
static inline u32 ram_in_gr_fg_ptr_hi_v(u32 r)
{
	return (r >> 0) & 0xff;
}
static inline u32 ram_in_sec_cs_w(void)
{
	return 136;
}
static inline u32 ram_in_sec_cs_s(void)
{
	return 1;
}
static inline u32 ram_in_sec_cs_f(u32 v)
{
	return (v & 0x1) << 3;
}
static inline u32 ram_in_sec_cs_m(void)
{
	return 0x1 << 3;
}
static inline u32 ram_in_sec_cs_v(u32 r)
{
	return (r >> 3) & 0x1;
}
static inline u32 ram_in_sec_cs_wfi_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_sec_cs_wfi_f(void)
{
	return 0x0;
}
static inline u32 ram_in_sec_cs_fg_v(void)
{
	return 0x00000001;
}
static inline u32 ram_in_sec_cs_fg_f(void)
{
	return 0x8;
}
static inline u32 ram_in_sec_wfi_target_w(void)
{
	return 136;
}
static inline u32 ram_in_sec_wfi_target_s(void)
{
	return 2;
}
static inline u32 ram_in_sec_wfi_target_f(u32 v)
{
	return (v & 0x3) << 0;
}
static inline u32 ram_in_sec_wfi_target_m(void)
{
	return 0x3 << 0;
}
static inline u32 ram_in_sec_wfi_target_v(u32 r)
{
	return (r >> 0) & 0x3;
}
static inline u32 ram_in_sec_wfi_target_local_mem_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_sec_wfi_target_local_mem_f(void)
{
	return 0x0;
}
static inline u32 ram_in_sec_wfi_target_sys_mem_coherent_v(void)
{
	return 0x00000002;
}
static inline u32 ram_in_sec_wfi_target_sys_mem_coherent_f(void)
{
	return 0x2;
}
static inline u32 ram_in_sec_wfi_target_sys_mem_noncoherent_v(void)
{
	return 0x00000003;
}
static inline u32 ram_in_sec_wfi_target_sys_mem_noncoherent_f(void)
{
	return 0x3;
}
static inline u32 ram_in_sec_wfi_mode_w(void)
{
	return 136;
}
static inline u32 ram_in_sec_wfi_mode_s(void)
{
	return 1;
}
static inline u32 ram_in_sec_wfi_mode_f(u32 v)
{
	return (v & 0x1) << 2;
}
static inline u32 ram_in_sec_wfi_mode_m(void)
{
	return 0x1 << 2;
}
static inline u32 ram_in_sec_wfi_mode_v(u32 r)
{
	return (r >> 2) & 0x1;
}
static inline u32 ram_in_sec_wfi_mode_physical_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_sec_wfi_mode_physical_f(void)
{
	return 0x0;
}
static inline u32 ram_in_sec_wfi_mode_virtual_v(void)
{
	return 0x00000001;
}
static inline u32 ram_in_sec_wfi_mode_virtual_f(void)
{
	return 0x4;
}
static inline u32 ram_in_sec_wfi_ptr_lo_w(void)
{
	return 136;
}
static inline u32 ram_in_sec_wfi_ptr_lo_s(void)
{
	return 20;
}
static inline u32 ram_in_sec_wfi_ptr_lo_f(u32 v)
{
	return (v & 0xfffff) << 12;
}
static inline u32 ram_in_sec_wfi_ptr_lo_m(void)
{
	return 0xfffff << 12;
}
static inline u32 ram_in_sec_wfi_ptr_lo_v(u32 r)
{
	return (r >> 12) & 0xfffff;
}
static inline u32 ram_in_sec_wfi_ptr_hi_w(void)
{
	return 137;
}
static inline u32 ram_in_sec_wfi_ptr_hi_s(void)
{
	return 8;
}
static inline u32 ram_in_sec_wfi_ptr_hi_f(u32 v)
{
	return (v & 0xff) << 0;
}
static inline u32 ram_in_sec_wfi_ptr_hi_m(void)
{
	return 0xff << 0;
}
static inline u32 ram_in_sec_wfi_ptr_hi_v(u32 r)
{
	return (r >> 0) & 0xff;
}
static inline u32 ram_in_sec_fg_target_w(void)
{
	return 138;
}
static inline u32 ram_in_sec_fg_target_s(void)
{
	return 2;
}
static inline u32 ram_in_sec_fg_target_f(u32 v)
{
	return (v & 0x3) << 0;
}
static inline u32 ram_in_sec_fg_target_m(void)
{
	return 0x3 << 0;
}
static inline u32 ram_in_sec_fg_target_v(u32 r)
{
	return (r >> 0) & 0x3;
}
static inline u32 ram_in_sec_fg_target_local_mem_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_sec_fg_target_local_mem_f(void)
{
	return 0x0;
}
static inline u32 ram_in_sec_fg_target_sys_mem_coherent_v(void)
{
	return 0x00000002;
}
static inline u32 ram_in_sec_fg_target_sys_mem_coherent_f(void)
{
	return 0x2;
}
static inline u32 ram_in_sec_fg_target_sys_mem_noncoherent_v(void)
{
	return 0x00000003;
}
static inline u32 ram_in_sec_fg_target_sys_mem_noncoherent_f(void)
{
	return 0x3;
}
static inline u32 ram_in_sec_fg_mode_w(void)
{
	return 138;
}
static inline u32 ram_in_sec_fg_mode_s(void)
{
	return 1;
}
static inline u32 ram_in_sec_fg_mode_f(u32 v)
{
	return (v & 0x1) << 2;
}
static inline u32 ram_in_sec_fg_mode_m(void)
{
	return 0x1 << 2;
}
static inline u32 ram_in_sec_fg_mode_v(u32 r)
{
	return (r >> 2) & 0x1;
}
static inline u32 ram_in_sec_fg_mode_physical_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_sec_fg_mode_physical_f(void)
{
	return 0x0;
}
static inline u32 ram_in_sec_fg_mode_virtual_v(void)
{
	return 0x00000001;
}
static inline u32 ram_in_sec_fg_mode_virtual_f(void)
{
	return 0x4;
}
static inline u32 ram_in_sec_fg_ptr_lo_w(void)
{
	return 138;
}
static inline u32 ram_in_sec_fg_ptr_lo_s(void)
{
	return 20;
}
static inline u32 ram_in_sec_fg_ptr_lo_f(u32 v)
{
	return (v & 0xfffff) << 12;
}
static inline u32 ram_in_sec_fg_ptr_lo_m(void)
{
	return 0xfffff << 12;
}
static inline u32 ram_in_sec_fg_ptr_lo_v(u32 r)
{
	return (r >> 12) & 0xfffff;
}
static inline u32 ram_in_sec_fg_ptr_hi_w(void)
{
	return 139;
}
static inline u32 ram_in_sec_fg_ptr_hi_s(void)
{
	return 8;
}
static inline u32 ram_in_sec_fg_ptr_hi_f(u32 v)
{
	return (v & 0xff) << 0;
}
static inline u32 ram_in_sec_fg_ptr_hi_m(void)
{
	return 0xff << 0;
}
static inline u32 ram_in_sec_fg_ptr_hi_v(u32 r)
{
	return (r >> 0) & 0xff;
}
static inline u32 ram_in_ce0_cs_w(void)
{
	return 140;
}
static inline u32 ram_in_ce0_cs_s(void)
{
	return 1;
}
static inline u32 ram_in_ce0_cs_f(u32 v)
{
	return (v & 0x1) << 3;
}
static inline u32 ram_in_ce0_cs_m(void)
{
	return 0x1 << 3;
}
static inline u32 ram_in_ce0_cs_v(u32 r)
{
	return (r >> 3) & 0x1;
}
static inline u32 ram_in_ce0_cs_wfi_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_ce0_cs_wfi_f(void)
{
	return 0x0;
}
static inline u32 ram_in_ce0_cs_fg_v(void)
{
	return 0x00000001;
}
static inline u32 ram_in_ce0_cs_fg_f(void)
{
	return 0x8;
}
static inline u32 ram_in_ce0_wfi_target_w(void)
{
	return 140;
}
static inline u32 ram_in_ce0_wfi_target_s(void)
{
	return 2;
}
static inline u32 ram_in_ce0_wfi_target_f(u32 v)
{
	return (v & 0x3) << 0;
}
static inline u32 ram_in_ce0_wfi_target_m(void)
{
	return 0x3 << 0;
}
static inline u32 ram_in_ce0_wfi_target_v(u32 r)
{
	return (r >> 0) & 0x3;
}
static inline u32 ram_in_ce0_wfi_target_local_mem_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_ce0_wfi_target_local_mem_f(void)
{
	return 0x0;
}
static inline u32 ram_in_ce0_wfi_target_sys_mem_coherent_v(void)
{
	return 0x00000002;
}
static inline u32 ram_in_ce0_wfi_target_sys_mem_coherent_f(void)
{
	return 0x2;
}
static inline u32 ram_in_ce0_wfi_target_sys_mem_noncoherent_v(void)
{
	return 0x00000003;
}
static inline u32 ram_in_ce0_wfi_target_sys_mem_noncoherent_f(void)
{
	return 0x3;
}
static inline u32 ram_in_ce0_wfi_mode_w(void)
{
	return 140;
}
static inline u32 ram_in_ce0_wfi_mode_s(void)
{
	return 1;
}
static inline u32 ram_in_ce0_wfi_mode_f(u32 v)
{
	return (v & 0x1) << 2;
}
static inline u32 ram_in_ce0_wfi_mode_m(void)
{
	return 0x1 << 2;
}
static inline u32 ram_in_ce0_wfi_mode_v(u32 r)
{
	return (r >> 2) & 0x1;
}
static inline u32 ram_in_ce0_wfi_mode_physical_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_ce0_wfi_mode_physical_f(void)
{
	return 0x0;
}
static inline u32 ram_in_ce0_wfi_mode_virtual_v(void)
{
	return 0x00000001;
}
static inline u32 ram_in_ce0_wfi_mode_virtual_f(void)
{
	return 0x4;
}
static inline u32 ram_in_ce0_wfi_ptr_lo_w(void)
{
	return 140;
}
static inline u32 ram_in_ce0_wfi_ptr_lo_s(void)
{
	return 20;
}
static inline u32 ram_in_ce0_wfi_ptr_lo_f(u32 v)
{
	return (v & 0xfffff) << 12;
}
static inline u32 ram_in_ce0_wfi_ptr_lo_m(void)
{
	return 0xfffff << 12;
}
static inline u32 ram_in_ce0_wfi_ptr_lo_v(u32 r)
{
	return (r >> 12) & 0xfffff;
}
static inline u32 ram_in_ce0_wfi_ptr_hi_w(void)
{
	return 141;
}
static inline u32 ram_in_ce0_wfi_ptr_hi_s(void)
{
	return 8;
}
static inline u32 ram_in_ce0_wfi_ptr_hi_f(u32 v)
{
	return (v & 0xff) << 0;
}
static inline u32 ram_in_ce0_wfi_ptr_hi_m(void)
{
	return 0xff << 0;
}
static inline u32 ram_in_ce0_wfi_ptr_hi_v(u32 r)
{
	return (r >> 0) & 0xff;
}
static inline u32 ram_in_ce0_fg_target_w(void)
{
	return 142;
}
static inline u32 ram_in_ce0_fg_target_s(void)
{
	return 2;
}
static inline u32 ram_in_ce0_fg_target_f(u32 v)
{
	return (v & 0x3) << 0;
}
static inline u32 ram_in_ce0_fg_target_m(void)
{
	return 0x3 << 0;
}
static inline u32 ram_in_ce0_fg_target_v(u32 r)
{
	return (r >> 0) & 0x3;
}
static inline u32 ram_in_ce0_fg_target_local_mem_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_ce0_fg_target_local_mem_f(void)
{
	return 0x0;
}
static inline u32 ram_in_ce0_fg_target_sys_mem_coherent_v(void)
{
	return 0x00000002;
}
static inline u32 ram_in_ce0_fg_target_sys_mem_coherent_f(void)
{
	return 0x2;
}
static inline u32 ram_in_ce0_fg_target_sys_mem_noncoherent_v(void)
{
	return 0x00000003;
}
static inline u32 ram_in_ce0_fg_target_sys_mem_noncoherent_f(void)
{
	return 0x3;
}
static inline u32 ram_in_ce0_fg_mode_w(void)
{
	return 142;
}
static inline u32 ram_in_ce0_fg_mode_s(void)
{
	return 1;
}
static inline u32 ram_in_ce0_fg_mode_f(u32 v)
{
	return (v & 0x1) << 2;
}
static inline u32 ram_in_ce0_fg_mode_m(void)
{
	return 0x1 << 2;
}
static inline u32 ram_in_ce0_fg_mode_v(u32 r)
{
	return (r >> 2) & 0x1;
}
static inline u32 ram_in_ce0_fg_mode_physical_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_ce0_fg_mode_physical_f(void)
{
	return 0x0;
}
static inline u32 ram_in_ce0_fg_mode_virtual_v(void)
{
	return 0x00000001;
}
static inline u32 ram_in_ce0_fg_mode_virtual_f(void)
{
	return 0x4;
}
static inline u32 ram_in_ce0_fg_ptr_lo_w(void)
{
	return 142;
}
static inline u32 ram_in_ce0_fg_ptr_lo_s(void)
{
	return 20;
}
static inline u32 ram_in_ce0_fg_ptr_lo_f(u32 v)
{
	return (v & 0xfffff) << 12;
}
static inline u32 ram_in_ce0_fg_ptr_lo_m(void)
{
	return 0xfffff << 12;
}
static inline u32 ram_in_ce0_fg_ptr_lo_v(u32 r)
{
	return (r >> 12) & 0xfffff;
}
static inline u32 ram_in_ce0_fg_ptr_hi_w(void)
{
	return 143;
}
static inline u32 ram_in_ce0_fg_ptr_hi_s(void)
{
	return 8;
}
static inline u32 ram_in_ce0_fg_ptr_hi_f(u32 v)
{
	return (v & 0xff) << 0;
}
static inline u32 ram_in_ce0_fg_ptr_hi_m(void)
{
	return 0xff << 0;
}
static inline u32 ram_in_ce0_fg_ptr_hi_v(u32 r)
{
	return (r >> 0) & 0xff;
}
static inline u32 ram_in_ce1_cs_w(void)
{
	return 144;
}
static inline u32 ram_in_ce1_cs_s(void)
{
	return 1;
}
static inline u32 ram_in_ce1_cs_f(u32 v)
{
	return (v & 0x1) << 3;
}
static inline u32 ram_in_ce1_cs_m(void)
{
	return 0x1 << 3;
}
static inline u32 ram_in_ce1_cs_v(u32 r)
{
	return (r >> 3) & 0x1;
}
static inline u32 ram_in_ce1_cs_wfi_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_ce1_cs_wfi_f(void)
{
	return 0x0;
}
static inline u32 ram_in_ce1_cs_fg_v(void)
{
	return 0x00000001;
}
static inline u32 ram_in_ce1_cs_fg_f(void)
{
	return 0x8;
}
static inline u32 ram_in_ce1_wfi_target_w(void)
{
	return 144;
}
static inline u32 ram_in_ce1_wfi_target_s(void)
{
	return 2;
}
static inline u32 ram_in_ce1_wfi_target_f(u32 v)
{
	return (v & 0x3) << 0;
}
static inline u32 ram_in_ce1_wfi_target_m(void)
{
	return 0x3 << 0;
}
static inline u32 ram_in_ce1_wfi_target_v(u32 r)
{
	return (r >> 0) & 0x3;
}
static inline u32 ram_in_ce1_wfi_target_local_mem_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_ce1_wfi_target_local_mem_f(void)
{
	return 0x0;
}
static inline u32 ram_in_ce1_wfi_target_sys_mem_coherent_v(void)
{
	return 0x00000002;
}
static inline u32 ram_in_ce1_wfi_target_sys_mem_coherent_f(void)
{
	return 0x2;
}
static inline u32 ram_in_ce1_wfi_target_sys_mem_noncoherent_v(void)
{
	return 0x00000003;
}
static inline u32 ram_in_ce1_wfi_target_sys_mem_noncoherent_f(void)
{
	return 0x3;
}
static inline u32 ram_in_ce1_wfi_mode_w(void)
{
	return 144;
}
static inline u32 ram_in_ce1_wfi_mode_s(void)
{
	return 1;
}
static inline u32 ram_in_ce1_wfi_mode_f(u32 v)
{
	return (v & 0x1) << 2;
}
static inline u32 ram_in_ce1_wfi_mode_m(void)
{
	return 0x1 << 2;
}
static inline u32 ram_in_ce1_wfi_mode_v(u32 r)
{
	return (r >> 2) & 0x1;
}
static inline u32 ram_in_ce1_wfi_mode_physical_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_ce1_wfi_mode_physical_f(void)
{
	return 0x0;
}
static inline u32 ram_in_ce1_wfi_mode_virtual_v(void)
{
	return 0x00000001;
}
static inline u32 ram_in_ce1_wfi_mode_virtual_f(void)
{
	return 0x4;
}
static inline u32 ram_in_ce1_wfi_ptr_lo_w(void)
{
	return 144;
}
static inline u32 ram_in_ce1_wfi_ptr_lo_s(void)
{
	return 20;
}
static inline u32 ram_in_ce1_wfi_ptr_lo_f(u32 v)
{
	return (v & 0xfffff) << 12;
}
static inline u32 ram_in_ce1_wfi_ptr_lo_m(void)
{
	return 0xfffff << 12;
}
static inline u32 ram_in_ce1_wfi_ptr_lo_v(u32 r)
{
	return (r >> 12) & 0xfffff;
}
static inline u32 ram_in_ce1_wfi_ptr_hi_w(void)
{
	return 145;
}
static inline u32 ram_in_ce1_wfi_ptr_hi_s(void)
{
	return 8;
}
static inline u32 ram_in_ce1_wfi_ptr_hi_f(u32 v)
{
	return (v & 0xff) << 0;
}
static inline u32 ram_in_ce1_wfi_ptr_hi_m(void)
{
	return 0xff << 0;
}
static inline u32 ram_in_ce1_wfi_ptr_hi_v(u32 r)
{
	return (r >> 0) & 0xff;
}
static inline u32 ram_in_ce1_fg_target_w(void)
{
	return 146;
}
static inline u32 ram_in_ce1_fg_target_s(void)
{
	return 2;
}
static inline u32 ram_in_ce1_fg_target_f(u32 v)
{
	return (v & 0x3) << 0;
}
static inline u32 ram_in_ce1_fg_target_m(void)
{
	return 0x3 << 0;
}
static inline u32 ram_in_ce1_fg_target_v(u32 r)
{
	return (r >> 0) & 0x3;
}
static inline u32 ram_in_ce1_fg_target_local_mem_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_ce1_fg_target_local_mem_f(void)
{
	return 0x0;
}
static inline u32 ram_in_ce1_fg_target_sys_mem_coherent_v(void)
{
	return 0x00000002;
}
static inline u32 ram_in_ce1_fg_target_sys_mem_coherent_f(void)
{
	return 0x2;
}
static inline u32 ram_in_ce1_fg_target_sys_mem_noncoherent_v(void)
{
	return 0x00000003;
}
static inline u32 ram_in_ce1_fg_target_sys_mem_noncoherent_f(void)
{
	return 0x3;
}
static inline u32 ram_in_ce1_fg_mode_w(void)
{
	return 146;
}
static inline u32 ram_in_ce1_fg_mode_s(void)
{
	return 1;
}
static inline u32 ram_in_ce1_fg_mode_f(u32 v)
{
	return (v & 0x1) << 2;
}
static inline u32 ram_in_ce1_fg_mode_m(void)
{
	return 0x1 << 2;
}
static inline u32 ram_in_ce1_fg_mode_v(u32 r)
{
	return (r >> 2) & 0x1;
}
static inline u32 ram_in_ce1_fg_mode_physical_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_ce1_fg_mode_physical_f(void)
{
	return 0x0;
}
static inline u32 ram_in_ce1_fg_mode_virtual_v(void)
{
	return 0x00000001;
}
static inline u32 ram_in_ce1_fg_mode_virtual_f(void)
{
	return 0x4;
}
static inline u32 ram_in_ce1_fg_ptr_lo_w(void)
{
	return 146;
}
static inline u32 ram_in_ce1_fg_ptr_lo_s(void)
{
	return 20;
}
static inline u32 ram_in_ce1_fg_ptr_lo_f(u32 v)
{
	return (v & 0xfffff) << 12;
}
static inline u32 ram_in_ce1_fg_ptr_lo_m(void)
{
	return 0xfffff << 12;
}
static inline u32 ram_in_ce1_fg_ptr_lo_v(u32 r)
{
	return (r >> 12) & 0xfffff;
}
static inline u32 ram_in_ce1_fg_ptr_hi_w(void)
{
	return 147;
}
static inline u32 ram_in_ce1_fg_ptr_hi_s(void)
{
	return 8;
}
static inline u32 ram_in_ce1_fg_ptr_hi_f(u32 v)
{
	return (v & 0xff) << 0;
}
static inline u32 ram_in_ce1_fg_ptr_hi_m(void)
{
	return 0xff << 0;
}
static inline u32 ram_in_ce1_fg_ptr_hi_v(u32 r)
{
	return (r >> 0) & 0xff;
}
static inline u32 ram_in_mspdec_cs_w(void)
{
	return 148;
}
static inline u32 ram_in_mspdec_cs_s(void)
{
	return 1;
}
static inline u32 ram_in_mspdec_cs_f(u32 v)
{
	return (v & 0x1) << 3;
}
static inline u32 ram_in_mspdec_cs_m(void)
{
	return 0x1 << 3;
}
static inline u32 ram_in_mspdec_cs_v(u32 r)
{
	return (r >> 3) & 0x1;
}
static inline u32 ram_in_mspdec_cs_wfi_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_mspdec_cs_wfi_f(void)
{
	return 0x0;
}
static inline u32 ram_in_mspdec_cs_fg_v(void)
{
	return 0x00000001;
}
static inline u32 ram_in_mspdec_cs_fg_f(void)
{
	return 0x8;
}
static inline u32 ram_in_mspdec_wfi_target_w(void)
{
	return 148;
}
static inline u32 ram_in_mspdec_wfi_target_s(void)
{
	return 2;
}
static inline u32 ram_in_mspdec_wfi_target_f(u32 v)
{
	return (v & 0x3) << 0;
}
static inline u32 ram_in_mspdec_wfi_target_m(void)
{
	return 0x3 << 0;
}
static inline u32 ram_in_mspdec_wfi_target_v(u32 r)
{
	return (r >> 0) & 0x3;
}
static inline u32 ram_in_mspdec_wfi_target_local_mem_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_mspdec_wfi_target_local_mem_f(void)
{
	return 0x0;
}
static inline u32 ram_in_mspdec_wfi_target_sys_mem_coherent_v(void)
{
	return 0x00000002;
}
static inline u32 ram_in_mspdec_wfi_target_sys_mem_coherent_f(void)
{
	return 0x2;
}
static inline u32 ram_in_mspdec_wfi_target_sys_mem_noncoherent_v(void)
{
	return 0x00000003;
}
static inline u32 ram_in_mspdec_wfi_target_sys_mem_noncoherent_f(void)
{
	return 0x3;
}
static inline u32 ram_in_mspdec_wfi_mode_w(void)
{
	return 148;
}
static inline u32 ram_in_mspdec_wfi_mode_s(void)
{
	return 1;
}
static inline u32 ram_in_mspdec_wfi_mode_f(u32 v)
{
	return (v & 0x1) << 2;
}
static inline u32 ram_in_mspdec_wfi_mode_m(void)
{
	return 0x1 << 2;
}
static inline u32 ram_in_mspdec_wfi_mode_v(u32 r)
{
	return (r >> 2) & 0x1;
}
static inline u32 ram_in_mspdec_wfi_mode_physical_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_mspdec_wfi_mode_physical_f(void)
{
	return 0x0;
}
static inline u32 ram_in_mspdec_wfi_mode_virtual_v(void)
{
	return 0x00000001;
}
static inline u32 ram_in_mspdec_wfi_mode_virtual_f(void)
{
	return 0x4;
}
static inline u32 ram_in_mspdec_wfi_ptr_lo_w(void)
{
	return 148;
}
static inline u32 ram_in_mspdec_wfi_ptr_lo_s(void)
{
	return 20;
}
static inline u32 ram_in_mspdec_wfi_ptr_lo_f(u32 v)
{
	return (v & 0xfffff) << 12;
}
static inline u32 ram_in_mspdec_wfi_ptr_lo_m(void)
{
	return 0xfffff << 12;
}
static inline u32 ram_in_mspdec_wfi_ptr_lo_v(u32 r)
{
	return (r >> 12) & 0xfffff;
}
static inline u32 ram_in_mspdec_wfi_ptr_hi_w(void)
{
	return 149;
}
static inline u32 ram_in_mspdec_wfi_ptr_hi_s(void)
{
	return 8;
}
static inline u32 ram_in_mspdec_wfi_ptr_hi_f(u32 v)
{
	return (v & 0xff) << 0;
}
static inline u32 ram_in_mspdec_wfi_ptr_hi_m(void)
{
	return 0xff << 0;
}
static inline u32 ram_in_mspdec_wfi_ptr_hi_v(u32 r)
{
	return (r >> 0) & 0xff;
}
static inline u32 ram_in_mspdec_fg_target_w(void)
{
	return 150;
}
static inline u32 ram_in_mspdec_fg_target_s(void)
{
	return 2;
}
static inline u32 ram_in_mspdec_fg_target_f(u32 v)
{
	return (v & 0x3) << 0;
}
static inline u32 ram_in_mspdec_fg_target_m(void)
{
	return 0x3 << 0;
}
static inline u32 ram_in_mspdec_fg_target_v(u32 r)
{
	return (r >> 0) & 0x3;
}
static inline u32 ram_in_mspdec_fg_target_local_mem_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_mspdec_fg_target_local_mem_f(void)
{
	return 0x0;
}
static inline u32 ram_in_mspdec_fg_target_sys_mem_coherent_v(void)
{
	return 0x00000002;
}
static inline u32 ram_in_mspdec_fg_target_sys_mem_coherent_f(void)
{
	return 0x2;
}
static inline u32 ram_in_mspdec_fg_target_sys_mem_noncoherent_v(void)
{
	return 0x00000003;
}
static inline u32 ram_in_mspdec_fg_target_sys_mem_noncoherent_f(void)
{
	return 0x3;
}
static inline u32 ram_in_mspdec_fg_mode_w(void)
{
	return 150;
}
static inline u32 ram_in_mspdec_fg_mode_s(void)
{
	return 1;
}
static inline u32 ram_in_mspdec_fg_mode_f(u32 v)
{
	return (v & 0x1) << 2;
}
static inline u32 ram_in_mspdec_fg_mode_m(void)
{
	return 0x1 << 2;
}
static inline u32 ram_in_mspdec_fg_mode_v(u32 r)
{
	return (r >> 2) & 0x1;
}
static inline u32 ram_in_mspdec_fg_mode_physical_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_mspdec_fg_mode_physical_f(void)
{
	return 0x0;
}
static inline u32 ram_in_mspdec_fg_mode_virtual_v(void)
{
	return 0x00000001;
}
static inline u32 ram_in_mspdec_fg_mode_virtual_f(void)
{
	return 0x4;
}
static inline u32 ram_in_mspdec_fg_ptr_lo_w(void)
{
	return 150;
}
static inline u32 ram_in_mspdec_fg_ptr_lo_s(void)
{
	return 20;
}
static inline u32 ram_in_mspdec_fg_ptr_lo_f(u32 v)
{
	return (v & 0xfffff) << 12;
}
static inline u32 ram_in_mspdec_fg_ptr_lo_m(void)
{
	return 0xfffff << 12;
}
static inline u32 ram_in_mspdec_fg_ptr_lo_v(u32 r)
{
	return (r >> 12) & 0xfffff;
}
static inline u32 ram_in_mspdec_fg_ptr_hi_w(void)
{
	return 151;
}
static inline u32 ram_in_mspdec_fg_ptr_hi_s(void)
{
	return 8;
}
static inline u32 ram_in_mspdec_fg_ptr_hi_f(u32 v)
{
	return (v & 0xff) << 0;
}
static inline u32 ram_in_mspdec_fg_ptr_hi_m(void)
{
	return 0xff << 0;
}
static inline u32 ram_in_mspdec_fg_ptr_hi_v(u32 r)
{
	return (r >> 0) & 0xff;
}
static inline u32 ram_in_msppp_cs_w(void)
{
	return 152;
}
static inline u32 ram_in_msppp_cs_s(void)
{
	return 1;
}
static inline u32 ram_in_msppp_cs_f(u32 v)
{
	return (v & 0x1) << 3;
}
static inline u32 ram_in_msppp_cs_m(void)
{
	return 0x1 << 3;
}
static inline u32 ram_in_msppp_cs_v(u32 r)
{
	return (r >> 3) & 0x1;
}
static inline u32 ram_in_msppp_cs_wfi_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_msppp_cs_wfi_f(void)
{
	return 0x0;
}
static inline u32 ram_in_msppp_cs_fg_v(void)
{
	return 0x00000001;
}
static inline u32 ram_in_msppp_cs_fg_f(void)
{
	return 0x8;
}
static inline u32 ram_in_msppp_wfi_target_w(void)
{
	return 152;
}
static inline u32 ram_in_msppp_wfi_target_s(void)
{
	return 2;
}
static inline u32 ram_in_msppp_wfi_target_f(u32 v)
{
	return (v & 0x3) << 0;
}
static inline u32 ram_in_msppp_wfi_target_m(void)
{
	return 0x3 << 0;
}
static inline u32 ram_in_msppp_wfi_target_v(u32 r)
{
	return (r >> 0) & 0x3;
}
static inline u32 ram_in_msppp_wfi_target_local_mem_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_msppp_wfi_target_local_mem_f(void)
{
	return 0x0;
}
static inline u32 ram_in_msppp_wfi_target_sys_mem_coherent_v(void)
{
	return 0x00000002;
}
static inline u32 ram_in_msppp_wfi_target_sys_mem_coherent_f(void)
{
	return 0x2;
}
static inline u32 ram_in_msppp_wfi_target_sys_mem_noncoherent_v(void)
{
	return 0x00000003;
}
static inline u32 ram_in_msppp_wfi_target_sys_mem_noncoherent_f(void)
{
	return 0x3;
}
static inline u32 ram_in_msppp_wfi_mode_w(void)
{
	return 152;
}
static inline u32 ram_in_msppp_wfi_mode_s(void)
{
	return 1;
}
static inline u32 ram_in_msppp_wfi_mode_f(u32 v)
{
	return (v & 0x1) << 2;
}
static inline u32 ram_in_msppp_wfi_mode_m(void)
{
	return 0x1 << 2;
}
static inline u32 ram_in_msppp_wfi_mode_v(u32 r)
{
	return (r >> 2) & 0x1;
}
static inline u32 ram_in_msppp_wfi_mode_physical_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_msppp_wfi_mode_physical_f(void)
{
	return 0x0;
}
static inline u32 ram_in_msppp_wfi_mode_virtual_v(void)
{
	return 0x00000001;
}
static inline u32 ram_in_msppp_wfi_mode_virtual_f(void)
{
	return 0x4;
}
static inline u32 ram_in_msppp_wfi_ptr_lo_w(void)
{
	return 152;
}
static inline u32 ram_in_msppp_wfi_ptr_lo_s(void)
{
	return 20;
}
static inline u32 ram_in_msppp_wfi_ptr_lo_f(u32 v)
{
	return (v & 0xfffff) << 12;
}
static inline u32 ram_in_msppp_wfi_ptr_lo_m(void)
{
	return 0xfffff << 12;
}
static inline u32 ram_in_msppp_wfi_ptr_lo_v(u32 r)
{
	return (r >> 12) & 0xfffff;
}
static inline u32 ram_in_msppp_wfi_ptr_hi_w(void)
{
	return 153;
}
static inline u32 ram_in_msppp_wfi_ptr_hi_s(void)
{
	return 8;
}
static inline u32 ram_in_msppp_wfi_ptr_hi_f(u32 v)
{
	return (v & 0xff) << 0;
}
static inline u32 ram_in_msppp_wfi_ptr_hi_m(void)
{
	return 0xff << 0;
}
static inline u32 ram_in_msppp_wfi_ptr_hi_v(u32 r)
{
	return (r >> 0) & 0xff;
}
static inline u32 ram_in_msppp_fg_target_w(void)
{
	return 154;
}
static inline u32 ram_in_msppp_fg_target_s(void)
{
	return 2;
}
static inline u32 ram_in_msppp_fg_target_f(u32 v)
{
	return (v & 0x3) << 0;
}
static inline u32 ram_in_msppp_fg_target_m(void)
{
	return 0x3 << 0;
}
static inline u32 ram_in_msppp_fg_target_v(u32 r)
{
	return (r >> 0) & 0x3;
}
static inline u32 ram_in_msppp_fg_target_local_mem_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_msppp_fg_target_local_mem_f(void)
{
	return 0x0;
}
static inline u32 ram_in_msppp_fg_target_sys_mem_coherent_v(void)
{
	return 0x00000002;
}
static inline u32 ram_in_msppp_fg_target_sys_mem_coherent_f(void)
{
	return 0x2;
}
static inline u32 ram_in_msppp_fg_target_sys_mem_noncoherent_v(void)
{
	return 0x00000003;
}
static inline u32 ram_in_msppp_fg_target_sys_mem_noncoherent_f(void)
{
	return 0x3;
}
static inline u32 ram_in_msppp_fg_mode_w(void)
{
	return 154;
}
static inline u32 ram_in_msppp_fg_mode_s(void)
{
	return 1;
}
static inline u32 ram_in_msppp_fg_mode_f(u32 v)
{
	return (v & 0x1) << 2;
}
static inline u32 ram_in_msppp_fg_mode_m(void)
{
	return 0x1 << 2;
}
static inline u32 ram_in_msppp_fg_mode_v(u32 r)
{
	return (r >> 2) & 0x1;
}
static inline u32 ram_in_msppp_fg_mode_physical_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_msppp_fg_mode_physical_f(void)
{
	return 0x0;
}
static inline u32 ram_in_msppp_fg_mode_virtual_v(void)
{
	return 0x00000001;
}
static inline u32 ram_in_msppp_fg_mode_virtual_f(void)
{
	return 0x4;
}
static inline u32 ram_in_msppp_fg_ptr_lo_w(void)
{
	return 154;
}
static inline u32 ram_in_msppp_fg_ptr_lo_s(void)
{
	return 20;
}
static inline u32 ram_in_msppp_fg_ptr_lo_f(u32 v)
{
	return (v & 0xfffff) << 12;
}
static inline u32 ram_in_msppp_fg_ptr_lo_m(void)
{
	return 0xfffff << 12;
}
static inline u32 ram_in_msppp_fg_ptr_lo_v(u32 r)
{
	return (r >> 12) & 0xfffff;
}
static inline u32 ram_in_msppp_fg_ptr_hi_w(void)
{
	return 155;
}
static inline u32 ram_in_msppp_fg_ptr_hi_s(void)
{
	return 8;
}
static inline u32 ram_in_msppp_fg_ptr_hi_f(u32 v)
{
	return (v & 0xff) << 0;
}
static inline u32 ram_in_msppp_fg_ptr_hi_m(void)
{
	return 0xff << 0;
}
static inline u32 ram_in_msppp_fg_ptr_hi_v(u32 r)
{
	return (r >> 0) & 0xff;
}
static inline u32 ram_in_msvld_cs_w(void)
{
	return 156;
}
static inline u32 ram_in_msvld_cs_s(void)
{
	return 1;
}
static inline u32 ram_in_msvld_cs_f(u32 v)
{
	return (v & 0x1) << 3;
}
static inline u32 ram_in_msvld_cs_m(void)
{
	return 0x1 << 3;
}
static inline u32 ram_in_msvld_cs_v(u32 r)
{
	return (r >> 3) & 0x1;
}
static inline u32 ram_in_msvld_cs_wfi_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_msvld_cs_wfi_f(void)
{
	return 0x0;
}
static inline u32 ram_in_msvld_cs_fg_v(void)
{
	return 0x00000001;
}
static inline u32 ram_in_msvld_cs_fg_f(void)
{
	return 0x8;
}
static inline u32 ram_in_msvld_wfi_target_w(void)
{
	return 156;
}
static inline u32 ram_in_msvld_wfi_target_s(void)
{
	return 2;
}
static inline u32 ram_in_msvld_wfi_target_f(u32 v)
{
	return (v & 0x3) << 0;
}
static inline u32 ram_in_msvld_wfi_target_m(void)
{
	return 0x3 << 0;
}
static inline u32 ram_in_msvld_wfi_target_v(u32 r)
{
	return (r >> 0) & 0x3;
}
static inline u32 ram_in_msvld_wfi_target_local_mem_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_msvld_wfi_target_local_mem_f(void)
{
	return 0x0;
}
static inline u32 ram_in_msvld_wfi_target_sys_mem_coherent_v(void)
{
	return 0x00000002;
}
static inline u32 ram_in_msvld_wfi_target_sys_mem_coherent_f(void)
{
	return 0x2;
}
static inline u32 ram_in_msvld_wfi_target_sys_mem_noncoherent_v(void)
{
	return 0x00000003;
}
static inline u32 ram_in_msvld_wfi_target_sys_mem_noncoherent_f(void)
{
	return 0x3;
}
static inline u32 ram_in_msvld_wfi_mode_w(void)
{
	return 156;
}
static inline u32 ram_in_msvld_wfi_mode_s(void)
{
	return 1;
}
static inline u32 ram_in_msvld_wfi_mode_f(u32 v)
{
	return (v & 0x1) << 2;
}
static inline u32 ram_in_msvld_wfi_mode_m(void)
{
	return 0x1 << 2;
}
static inline u32 ram_in_msvld_wfi_mode_v(u32 r)
{
	return (r >> 2) & 0x1;
}
static inline u32 ram_in_msvld_wfi_mode_physical_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_msvld_wfi_mode_physical_f(void)
{
	return 0x0;
}
static inline u32 ram_in_msvld_wfi_mode_virtual_v(void)
{
	return 0x00000001;
}
static inline u32 ram_in_msvld_wfi_mode_virtual_f(void)
{
	return 0x4;
}
static inline u32 ram_in_msvld_wfi_ptr_lo_w(void)
{
	return 156;
}
static inline u32 ram_in_msvld_wfi_ptr_lo_s(void)
{
	return 20;
}
static inline u32 ram_in_msvld_wfi_ptr_lo_f(u32 v)
{
	return (v & 0xfffff) << 12;
}
static inline u32 ram_in_msvld_wfi_ptr_lo_m(void)
{
	return 0xfffff << 12;
}
static inline u32 ram_in_msvld_wfi_ptr_lo_v(u32 r)
{
	return (r >> 12) & 0xfffff;
}
static inline u32 ram_in_msvld_wfi_ptr_hi_w(void)
{
	return 157;
}
static inline u32 ram_in_msvld_wfi_ptr_hi_s(void)
{
	return 8;
}
static inline u32 ram_in_msvld_wfi_ptr_hi_f(u32 v)
{
	return (v & 0xff) << 0;
}
static inline u32 ram_in_msvld_wfi_ptr_hi_m(void)
{
	return 0xff << 0;
}
static inline u32 ram_in_msvld_wfi_ptr_hi_v(u32 r)
{
	return (r >> 0) & 0xff;
}
static inline u32 ram_in_msvld_fg_target_w(void)
{
	return 158;
}
static inline u32 ram_in_msvld_fg_target_s(void)
{
	return 2;
}
static inline u32 ram_in_msvld_fg_target_f(u32 v)
{
	return (v & 0x3) << 0;
}
static inline u32 ram_in_msvld_fg_target_m(void)
{
	return 0x3 << 0;
}
static inline u32 ram_in_msvld_fg_target_v(u32 r)
{
	return (r >> 0) & 0x3;
}
static inline u32 ram_in_msvld_fg_target_local_mem_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_msvld_fg_target_local_mem_f(void)
{
	return 0x0;
}
static inline u32 ram_in_msvld_fg_target_sys_mem_coherent_v(void)
{
	return 0x00000002;
}
static inline u32 ram_in_msvld_fg_target_sys_mem_coherent_f(void)
{
	return 0x2;
}
static inline u32 ram_in_msvld_fg_target_sys_mem_noncoherent_v(void)
{
	return 0x00000003;
}
static inline u32 ram_in_msvld_fg_target_sys_mem_noncoherent_f(void)
{
	return 0x3;
}
static inline u32 ram_in_msvld_fg_mode_w(void)
{
	return 158;
}
static inline u32 ram_in_msvld_fg_mode_s(void)
{
	return 1;
}
static inline u32 ram_in_msvld_fg_mode_f(u32 v)
{
	return (v & 0x1) << 2;
}
static inline u32 ram_in_msvld_fg_mode_m(void)
{
	return 0x1 << 2;
}
static inline u32 ram_in_msvld_fg_mode_v(u32 r)
{
	return (r >> 2) & 0x1;
}
static inline u32 ram_in_msvld_fg_mode_physical_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_msvld_fg_mode_physical_f(void)
{
	return 0x0;
}
static inline u32 ram_in_msvld_fg_mode_virtual_v(void)
{
	return 0x00000001;
}
static inline u32 ram_in_msvld_fg_mode_virtual_f(void)
{
	return 0x4;
}
static inline u32 ram_in_msvld_fg_ptr_lo_w(void)
{
	return 158;
}
static inline u32 ram_in_msvld_fg_ptr_lo_s(void)
{
	return 20;
}
static inline u32 ram_in_msvld_fg_ptr_lo_f(u32 v)
{
	return (v & 0xfffff) << 12;
}
static inline u32 ram_in_msvld_fg_ptr_lo_m(void)
{
	return 0xfffff << 12;
}
static inline u32 ram_in_msvld_fg_ptr_lo_v(u32 r)
{
	return (r >> 12) & 0xfffff;
}
static inline u32 ram_in_msvld_fg_ptr_hi_w(void)
{
	return 159;
}
static inline u32 ram_in_msvld_fg_ptr_hi_s(void)
{
	return 8;
}
static inline u32 ram_in_msvld_fg_ptr_hi_f(u32 v)
{
	return (v & 0xff) << 0;
}
static inline u32 ram_in_msvld_fg_ptr_hi_m(void)
{
	return 0xff << 0;
}
static inline u32 ram_in_msvld_fg_ptr_hi_v(u32 r)
{
	return (r >> 0) & 0xff;
}
static inline u32 ram_in_vic_cs_w(void)
{
	return 160;
}
static inline u32 ram_in_vic_cs_s(void)
{
	return 1;
}
static inline u32 ram_in_vic_cs_f(u32 v)
{
	return (v & 0x1) << 3;
}
static inline u32 ram_in_vic_cs_m(void)
{
	return 0x1 << 3;
}
static inline u32 ram_in_vic_cs_v(u32 r)
{
	return (r >> 3) & 0x1;
}
static inline u32 ram_in_vic_cs_wfi_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_vic_cs_wfi_f(void)
{
	return 0x0;
}
static inline u32 ram_in_vic_cs_fg_v(void)
{
	return 0x00000001;
}
static inline u32 ram_in_vic_cs_fg_f(void)
{
	return 0x8;
}
static inline u32 ram_in_vic_wfi_target_w(void)
{
	return 160;
}
static inline u32 ram_in_vic_wfi_target_s(void)
{
	return 2;
}
static inline u32 ram_in_vic_wfi_target_f(u32 v)
{
	return (v & 0x3) << 0;
}
static inline u32 ram_in_vic_wfi_target_m(void)
{
	return 0x3 << 0;
}
static inline u32 ram_in_vic_wfi_target_v(u32 r)
{
	return (r >> 0) & 0x3;
}
static inline u32 ram_in_vic_wfi_target_local_mem_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_vic_wfi_target_local_mem_f(void)
{
	return 0x0;
}
static inline u32 ram_in_vic_wfi_target_sys_mem_coherent_v(void)
{
	return 0x00000002;
}
static inline u32 ram_in_vic_wfi_target_sys_mem_coherent_f(void)
{
	return 0x2;
}
static inline u32 ram_in_vic_wfi_target_sys_mem_noncoherent_v(void)
{
	return 0x00000003;
}
static inline u32 ram_in_vic_wfi_target_sys_mem_noncoherent_f(void)
{
	return 0x3;
}
static inline u32 ram_in_vic_wfi_mode_w(void)
{
	return 160;
}
static inline u32 ram_in_vic_wfi_mode_s(void)
{
	return 1;
}
static inline u32 ram_in_vic_wfi_mode_f(u32 v)
{
	return (v & 0x1) << 2;
}
static inline u32 ram_in_vic_wfi_mode_m(void)
{
	return 0x1 << 2;
}
static inline u32 ram_in_vic_wfi_mode_v(u32 r)
{
	return (r >> 2) & 0x1;
}
static inline u32 ram_in_vic_wfi_mode_physical_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_vic_wfi_mode_physical_f(void)
{
	return 0x0;
}
static inline u32 ram_in_vic_wfi_mode_virtual_v(void)
{
	return 0x00000001;
}
static inline u32 ram_in_vic_wfi_mode_virtual_f(void)
{
	return 0x4;
}
static inline u32 ram_in_vic_wfi_ptr_lo_w(void)
{
	return 160;
}
static inline u32 ram_in_vic_wfi_ptr_lo_s(void)
{
	return 20;
}
static inline u32 ram_in_vic_wfi_ptr_lo_f(u32 v)
{
	return (v & 0xfffff) << 12;
}
static inline u32 ram_in_vic_wfi_ptr_lo_m(void)
{
	return 0xfffff << 12;
}
static inline u32 ram_in_vic_wfi_ptr_lo_v(u32 r)
{
	return (r >> 12) & 0xfffff;
}
static inline u32 ram_in_vic_wfi_ptr_hi_w(void)
{
	return 161;
}
static inline u32 ram_in_vic_wfi_ptr_hi_s(void)
{
	return 8;
}
static inline u32 ram_in_vic_wfi_ptr_hi_f(u32 v)
{
	return (v & 0xff) << 0;
}
static inline u32 ram_in_vic_wfi_ptr_hi_m(void)
{
	return 0xff << 0;
}
static inline u32 ram_in_vic_wfi_ptr_hi_v(u32 r)
{
	return (r >> 0) & 0xff;
}
static inline u32 ram_in_vic_fg_target_w(void)
{
	return 162;
}
static inline u32 ram_in_vic_fg_target_s(void)
{
	return 2;
}
static inline u32 ram_in_vic_fg_target_f(u32 v)
{
	return (v & 0x3) << 0;
}
static inline u32 ram_in_vic_fg_target_m(void)
{
	return 0x3 << 0;
}
static inline u32 ram_in_vic_fg_target_v(u32 r)
{
	return (r >> 0) & 0x3;
}
static inline u32 ram_in_vic_fg_target_local_mem_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_vic_fg_target_local_mem_f(void)
{
	return 0x0;
}
static inline u32 ram_in_vic_fg_target_sys_mem_coherent_v(void)
{
	return 0x00000002;
}
static inline u32 ram_in_vic_fg_target_sys_mem_coherent_f(void)
{
	return 0x2;
}
static inline u32 ram_in_vic_fg_target_sys_mem_noncoherent_v(void)
{
	return 0x00000003;
}
static inline u32 ram_in_vic_fg_target_sys_mem_noncoherent_f(void)
{
	return 0x3;
}
static inline u32 ram_in_vic_fg_mode_w(void)
{
	return 162;
}
static inline u32 ram_in_vic_fg_mode_s(void)
{
	return 1;
}
static inline u32 ram_in_vic_fg_mode_f(u32 v)
{
	return (v & 0x1) << 2;
}
static inline u32 ram_in_vic_fg_mode_m(void)
{
	return 0x1 << 2;
}
static inline u32 ram_in_vic_fg_mode_v(u32 r)
{
	return (r >> 2) & 0x1;
}
static inline u32 ram_in_vic_fg_mode_physical_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_vic_fg_mode_physical_f(void)
{
	return 0x0;
}
static inline u32 ram_in_vic_fg_mode_virtual_v(void)
{
	return 0x00000001;
}
static inline u32 ram_in_vic_fg_mode_virtual_f(void)
{
	return 0x4;
}
static inline u32 ram_in_vic_fg_ptr_lo_w(void)
{
	return 162;
}
static inline u32 ram_in_vic_fg_ptr_lo_s(void)
{
	return 20;
}
static inline u32 ram_in_vic_fg_ptr_lo_f(u32 v)
{
	return (v & 0xfffff) << 12;
}
static inline u32 ram_in_vic_fg_ptr_lo_m(void)
{
	return 0xfffff << 12;
}
static inline u32 ram_in_vic_fg_ptr_lo_v(u32 r)
{
	return (r >> 12) & 0xfffff;
}
static inline u32 ram_in_vic_fg_ptr_hi_w(void)
{
	return 163;
}
static inline u32 ram_in_vic_fg_ptr_hi_s(void)
{
	return 8;
}
static inline u32 ram_in_vic_fg_ptr_hi_f(u32 v)
{
	return (v & 0xff) << 0;
}
static inline u32 ram_in_vic_fg_ptr_hi_m(void)
{
	return 0xff << 0;
}
static inline u32 ram_in_vic_fg_ptr_hi_v(u32 r)
{
	return (r >> 0) & 0xff;
}
static inline u32 ram_in_msenc_cs_w(void)
{
	return 164;
}
static inline u32 ram_in_msenc_cs_s(void)
{
	return 1;
}
static inline u32 ram_in_msenc_cs_f(u32 v)
{
	return (v & 0x1) << 3;
}
static inline u32 ram_in_msenc_cs_m(void)
{
	return 0x1 << 3;
}
static inline u32 ram_in_msenc_cs_v(u32 r)
{
	return (r >> 3) & 0x1;
}
static inline u32 ram_in_msenc_cs_wfi_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_msenc_cs_wfi_f(void)
{
	return 0x0;
}
static inline u32 ram_in_msenc_cs_fg_v(void)
{
	return 0x00000001;
}
static inline u32 ram_in_msenc_cs_fg_f(void)
{
	return 0x8;
}
static inline u32 ram_in_msenc_wfi_target_w(void)
{
	return 164;
}
static inline u32 ram_in_msenc_wfi_target_s(void)
{
	return 2;
}
static inline u32 ram_in_msenc_wfi_target_f(u32 v)
{
	return (v & 0x3) << 0;
}
static inline u32 ram_in_msenc_wfi_target_m(void)
{
	return 0x3 << 0;
}
static inline u32 ram_in_msenc_wfi_target_v(u32 r)
{
	return (r >> 0) & 0x3;
}
static inline u32 ram_in_msenc_wfi_target_local_mem_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_msenc_wfi_target_local_mem_f(void)
{
	return 0x0;
}
static inline u32 ram_in_msenc_wfi_target_sys_mem_coherent_v(void)
{
	return 0x00000002;
}
static inline u32 ram_in_msenc_wfi_target_sys_mem_coherent_f(void)
{
	return 0x2;
}
static inline u32 ram_in_msenc_wfi_target_sys_mem_noncoherent_v(void)
{
	return 0x00000003;
}
static inline u32 ram_in_msenc_wfi_target_sys_mem_noncoherent_f(void)
{
	return 0x3;
}
static inline u32 ram_in_msenc_wfi_mode_w(void)
{
	return 164;
}
static inline u32 ram_in_msenc_wfi_mode_s(void)
{
	return 1;
}
static inline u32 ram_in_msenc_wfi_mode_f(u32 v)
{
	return (v & 0x1) << 2;
}
static inline u32 ram_in_msenc_wfi_mode_m(void)
{
	return 0x1 << 2;
}
static inline u32 ram_in_msenc_wfi_mode_v(u32 r)
{
	return (r >> 2) & 0x1;
}
static inline u32 ram_in_msenc_wfi_mode_physical_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_msenc_wfi_mode_physical_f(void)
{
	return 0x0;
}
static inline u32 ram_in_msenc_wfi_mode_virtual_v(void)
{
	return 0x00000001;
}
static inline u32 ram_in_msenc_wfi_mode_virtual_f(void)
{
	return 0x4;
}
static inline u32 ram_in_msenc_wfi_ptr_lo_w(void)
{
	return 164;
}
static inline u32 ram_in_msenc_wfi_ptr_lo_s(void)
{
	return 20;
}
static inline u32 ram_in_msenc_wfi_ptr_lo_f(u32 v)
{
	return (v & 0xfffff) << 12;
}
static inline u32 ram_in_msenc_wfi_ptr_lo_m(void)
{
	return 0xfffff << 12;
}
static inline u32 ram_in_msenc_wfi_ptr_lo_v(u32 r)
{
	return (r >> 12) & 0xfffff;
}
static inline u32 ram_in_msenc_wfi_ptr_hi_w(void)
{
	return 165;
}
static inline u32 ram_in_msenc_wfi_ptr_hi_s(void)
{
	return 8;
}
static inline u32 ram_in_msenc_wfi_ptr_hi_f(u32 v)
{
	return (v & 0xff) << 0;
}
static inline u32 ram_in_msenc_wfi_ptr_hi_m(void)
{
	return 0xff << 0;
}
static inline u32 ram_in_msenc_wfi_ptr_hi_v(u32 r)
{
	return (r >> 0) & 0xff;
}
static inline u32 ram_in_msenc_fg_target_w(void)
{
	return 166;
}
static inline u32 ram_in_msenc_fg_target_s(void)
{
	return 2;
}
static inline u32 ram_in_msenc_fg_target_f(u32 v)
{
	return (v & 0x3) << 0;
}
static inline u32 ram_in_msenc_fg_target_m(void)
{
	return 0x3 << 0;
}
static inline u32 ram_in_msenc_fg_target_v(u32 r)
{
	return (r >> 0) & 0x3;
}
static inline u32 ram_in_msenc_fg_target_local_mem_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_msenc_fg_target_local_mem_f(void)
{
	return 0x0;
}
static inline u32 ram_in_msenc_fg_target_sys_mem_coherent_v(void)
{
	return 0x00000002;
}
static inline u32 ram_in_msenc_fg_target_sys_mem_coherent_f(void)
{
	return 0x2;
}
static inline u32 ram_in_msenc_fg_target_sys_mem_noncoherent_v(void)
{
	return 0x00000003;
}
static inline u32 ram_in_msenc_fg_target_sys_mem_noncoherent_f(void)
{
	return 0x3;
}
static inline u32 ram_in_msenc_fg_mode_w(void)
{
	return 166;
}
static inline u32 ram_in_msenc_fg_mode_s(void)
{
	return 1;
}
static inline u32 ram_in_msenc_fg_mode_f(u32 v)
{
	return (v & 0x1) << 2;
}
static inline u32 ram_in_msenc_fg_mode_m(void)
{
	return 0x1 << 2;
}
static inline u32 ram_in_msenc_fg_mode_v(u32 r)
{
	return (r >> 2) & 0x1;
}
static inline u32 ram_in_msenc_fg_mode_physical_v(void)
{
	return 0x00000000;
}
static inline u32 ram_in_msenc_fg_mode_physical_f(void)
{
	return 0x0;
}
static inline u32 ram_in_msenc_fg_mode_virtual_v(void)
{
	return 0x00000001;
}
static inline u32 ram_in_msenc_fg_mode_virtual_f(void)
{
	return 0x4;
}
static inline u32 ram_in_msenc_fg_ptr_lo_w(void)
{
	return 166;
}
static inline u32 ram_in_msenc_fg_ptr_lo_s(void)
{
	return 20;
}
static inline u32 ram_in_msenc_fg_ptr_lo_f(u32 v)
{
	return (v & 0xfffff) << 12;
}
static inline u32 ram_in_msenc_fg_ptr_lo_m(void)
{
	return 0xfffff << 12;
}
static inline u32 ram_in_msenc_fg_ptr_lo_v(u32 r)
{
	return (r >> 12) & 0xfffff;
}
static inline u32 ram_in_msenc_fg_ptr_hi_w(void)
{
	return 167;
}
static inline u32 ram_in_msenc_fg_ptr_hi_s(void)
{
	return 8;
}
static inline u32 ram_in_msenc_fg_ptr_hi_f(u32 v)
{
	return (v & 0xff) << 0;
}
static inline u32 ram_in_msenc_fg_ptr_hi_m(void)
{
	return 0xff << 0;
}
static inline u32 ram_in_msenc_fg_ptr_hi_v(u32 r)
{
	return (r >> 0) & 0xff;
}
static inline u32 ram_fc_gp_put_w(void)
{
	return 0;
}
static inline u32 ram_fc_gp_put_s(void)
{
	return 32;
}
static inline u32 ram_fc_gp_put_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_gp_put_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_gp_put_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_reserved1_w(void)
{
	return 1;
}
static inline u32 ram_fc_reserved1_s(void)
{
	return 32;
}
static inline u32 ram_fc_reserved1_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_reserved1_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_reserved1_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_userd_w(void)
{
	return 2;
}
static inline u32 ram_fc_userd_s(void)
{
	return 32;
}
static inline u32 ram_fc_userd_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_userd_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_userd_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_userd_hi_w(void)
{
	return 3;
}
static inline u32 ram_fc_userd_hi_s(void)
{
	return 32;
}
static inline u32 ram_fc_userd_hi_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_userd_hi_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_userd_hi_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_signature_w(void)
{
	return 4;
}
static inline u32 ram_fc_signature_s(void)
{
	return 32;
}
static inline u32 ram_fc_signature_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_signature_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_signature_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_gp_get_w(void)
{
	return 5;
}
static inline u32 ram_fc_gp_get_s(void)
{
	return 32;
}
static inline u32 ram_fc_gp_get_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_gp_get_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_gp_get_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_pb_get_w(void)
{
	return 6;
}
static inline u32 ram_fc_pb_get_s(void)
{
	return 32;
}
static inline u32 ram_fc_pb_get_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_pb_get_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_pb_get_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_pb_get_hi_w(void)
{
	return 7;
}
static inline u32 ram_fc_pb_get_hi_s(void)
{
	return 32;
}
static inline u32 ram_fc_pb_get_hi_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_pb_get_hi_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_pb_get_hi_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_pb_top_level_get_w(void)
{
	return 8;
}
static inline u32 ram_fc_pb_top_level_get_s(void)
{
	return 32;
}
static inline u32 ram_fc_pb_top_level_get_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_pb_top_level_get_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_pb_top_level_get_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_pb_top_level_get_hi_w(void)
{
	return 9;
}
static inline u32 ram_fc_pb_top_level_get_hi_s(void)
{
	return 32;
}
static inline u32 ram_fc_pb_top_level_get_hi_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_pb_top_level_get_hi_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_pb_top_level_get_hi_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_ref_w(void)
{
	return 10;
}
static inline u32 ram_fc_ref_s(void)
{
	return 32;
}
static inline u32 ram_fc_ref_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_ref_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_ref_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_runtime_w(void)
{
	return 11;
}
static inline u32 ram_fc_runtime_s(void)
{
	return 32;
}
static inline u32 ram_fc_runtime_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_runtime_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_runtime_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_acquire_w(void)
{
	return 12;
}
static inline u32 ram_fc_acquire_s(void)
{
	return 32;
}
static inline u32 ram_fc_acquire_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_acquire_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_acquire_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_acquire_deadline_w(void)
{
	return 13;
}
static inline u32 ram_fc_acquire_deadline_s(void)
{
	return 32;
}
static inline u32 ram_fc_acquire_deadline_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_acquire_deadline_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_acquire_deadline_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_semaphorea_w(void)
{
	return 14;
}
static inline u32 ram_fc_semaphorea_s(void)
{
	return 32;
}
static inline u32 ram_fc_semaphorea_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_semaphorea_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_semaphorea_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_semaphoreb_w(void)
{
	return 15;
}
static inline u32 ram_fc_semaphoreb_s(void)
{
	return 32;
}
static inline u32 ram_fc_semaphoreb_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_semaphoreb_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_semaphoreb_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_semaphorec_w(void)
{
	return 16;
}
static inline u32 ram_fc_semaphorec_s(void)
{
	return 32;
}
static inline u32 ram_fc_semaphorec_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_semaphorec_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_semaphorec_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_semaphored_w(void)
{
	return 17;
}
static inline u32 ram_fc_semaphored_s(void)
{
	return 32;
}
static inline u32 ram_fc_semaphored_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_semaphored_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_semaphored_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_gp_base_w(void)
{
	return 18;
}
static inline u32 ram_fc_gp_base_s(void)
{
	return 32;
}
static inline u32 ram_fc_gp_base_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_gp_base_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_gp_base_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_gp_base_hi_w(void)
{
	return 19;
}
static inline u32 ram_fc_gp_base_hi_s(void)
{
	return 32;
}
static inline u32 ram_fc_gp_base_hi_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_gp_base_hi_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_gp_base_hi_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_gp_fetch_w(void)
{
	return 20;
}
static inline u32 ram_fc_gp_fetch_s(void)
{
	return 32;
}
static inline u32 ram_fc_gp_fetch_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_gp_fetch_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_gp_fetch_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_pb_fetch_w(void)
{
	return 21;
}
static inline u32 ram_fc_pb_fetch_s(void)
{
	return 32;
}
static inline u32 ram_fc_pb_fetch_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_pb_fetch_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_pb_fetch_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_pb_fetch_hi_w(void)
{
	return 22;
}
static inline u32 ram_fc_pb_fetch_hi_s(void)
{
	return 32;
}
static inline u32 ram_fc_pb_fetch_hi_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_pb_fetch_hi_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_pb_fetch_hi_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_pb_put_w(void)
{
	return 23;
}
static inline u32 ram_fc_pb_put_s(void)
{
	return 32;
}
static inline u32 ram_fc_pb_put_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_pb_put_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_pb_put_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_pb_put_hi_w(void)
{
	return 24;
}
static inline u32 ram_fc_pb_put_hi_s(void)
{
	return 32;
}
static inline u32 ram_fc_pb_put_hi_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_pb_put_hi_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_pb_put_hi_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_reserved25_w(void)
{
	return 25;
}
static inline u32 ram_fc_reserved25_s(void)
{
	return 32;
}
static inline u32 ram_fc_reserved25_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_reserved25_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_reserved25_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_pb_get_stager_w(void)
{
	return 26;
}
static inline u32 ram_fc_pb_get_stager_s(void)
{
	return 32;
}
static inline u32 ram_fc_pb_get_stager_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_pb_get_stager_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_pb_get_stager_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_pb_put_stager_w(void)
{
	return 27;
}
static inline u32 ram_fc_pb_put_stager_s(void)
{
	return 32;
}
static inline u32 ram_fc_pb_put_stager_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_pb_put_stager_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_pb_put_stager_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_pb_top_level_get_stager_w(void)
{
	return 28;
}
static inline u32 ram_fc_pb_top_level_get_stager_s(void)
{
	return 32;
}
static inline u32 ram_fc_pb_top_level_get_stager_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_pb_top_level_get_stager_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_pb_top_level_get_stager_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_gp_crc_w(void)
{
	return 29;
}
static inline u32 ram_fc_gp_crc_s(void)
{
	return 32;
}
static inline u32 ram_fc_gp_crc_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_gp_crc_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_gp_crc_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_reserved30_w(void)
{
	return 30;
}
static inline u32 ram_fc_reserved30_s(void)
{
	return 32;
}
static inline u32 ram_fc_reserved30_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_reserved30_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_reserved30_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_reserved31_w(void)
{
	return 31;
}
static inline u32 ram_fc_reserved31_s(void)
{
	return 32;
}
static inline u32 ram_fc_reserved31_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_reserved31_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_reserved31_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_reserved32_w(void)
{
	return 32;
}
static inline u32 ram_fc_reserved32_s(void)
{
	return 32;
}
static inline u32 ram_fc_reserved32_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_reserved32_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_reserved32_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_pb_header_w(void)
{
	return 33;
}
static inline u32 ram_fc_pb_header_s(void)
{
	return 32;
}
static inline u32 ram_fc_pb_header_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_pb_header_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_pb_header_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_pb_count_w(void)
{
	return 34;
}
static inline u32 ram_fc_pb_count_s(void)
{
	return 32;
}
static inline u32 ram_fc_pb_count_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_pb_count_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_pb_count_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_pb_data0_w(void)
{
	return 35;
}
static inline u32 ram_fc_pb_data0_s(void)
{
	return 32;
}
static inline u32 ram_fc_pb_data0_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_pb_data0_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_pb_data0_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_pb_data1_w(void)
{
	return 36;
}
static inline u32 ram_fc_pb_data1_s(void)
{
	return 32;
}
static inline u32 ram_fc_pb_data1_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_pb_data1_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_pb_data1_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_subdevice_w(void)
{
	return 37;
}
static inline u32 ram_fc_subdevice_s(void)
{
	return 32;
}
static inline u32 ram_fc_subdevice_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_subdevice_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_subdevice_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_pb_crc_w(void)
{
	return 38;
}
static inline u32 ram_fc_pb_crc_s(void)
{
	return 32;
}
static inline u32 ram_fc_pb_crc_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_pb_crc_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_pb_crc_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_formats_w(void)
{
	return 39;
}
static inline u32 ram_fc_formats_s(void)
{
	return 32;
}
static inline u32 ram_fc_formats_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_formats_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_formats_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_mem_op_a_w(void)
{
	return 40;
}
static inline u32 ram_fc_mem_op_a_s(void)
{
	return 32;
}
static inline u32 ram_fc_mem_op_a_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_mem_op_a_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_mem_op_a_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_syncpointa_w(void)
{
	return 41;
}
static inline u32 ram_fc_syncpointa_s(void)
{
	return 32;
}
static inline u32 ram_fc_syncpointa_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_syncpointa_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_syncpointa_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_syncpointb_w(void)
{
	return 42;
}
static inline u32 ram_fc_syncpointb_s(void)
{
	return 32;
}
static inline u32 ram_fc_syncpointb_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_syncpointb_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_syncpointb_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_target_w(void)
{
	return 43;
}
static inline u32 ram_fc_target_s(void)
{
	return 32;
}
static inline u32 ram_fc_target_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_target_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_target_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_method_crc_w(void)
{
	return 44;
}
static inline u32 ram_fc_method_crc_s(void)
{
	return 32;
}
static inline u32 ram_fc_method_crc_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_method_crc_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_method_crc_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_reserved45_w(void)
{
	return 45;
}
static inline u32 ram_fc_reserved45_s(void)
{
	return 32;
}
static inline u32 ram_fc_reserved45_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_reserved45_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_reserved45_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_reserved46_w(void)
{
	return 46;
}
static inline u32 ram_fc_reserved46_s(void)
{
	return 32;
}
static inline u32 ram_fc_reserved46_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_reserved46_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_reserved46_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_reserved47_w(void)
{
	return 47;
}
static inline u32 ram_fc_reserved47_s(void)
{
	return 32;
}
static inline u32 ram_fc_reserved47_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_reserved47_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_reserved47_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_method0_w(void)
{
	return 48;
}
static inline u32 ram_fc_method0_s(void)
{
	return 32;
}
static inline u32 ram_fc_method0_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_method0_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_method0_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_data0_w(void)
{
	return 49;
}
static inline u32 ram_fc_data0_s(void)
{
	return 32;
}
static inline u32 ram_fc_data0_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_data0_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_data0_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_method1_w(void)
{
	return 50;
}
static inline u32 ram_fc_method1_s(void)
{
	return 32;
}
static inline u32 ram_fc_method1_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_method1_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_method1_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_data1_w(void)
{
	return 51;
}
static inline u32 ram_fc_data1_s(void)
{
	return 32;
}
static inline u32 ram_fc_data1_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_data1_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_data1_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_method2_w(void)
{
	return 52;
}
static inline u32 ram_fc_method2_s(void)
{
	return 32;
}
static inline u32 ram_fc_method2_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_method2_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_method2_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_data2_w(void)
{
	return 53;
}
static inline u32 ram_fc_data2_s(void)
{
	return 32;
}
static inline u32 ram_fc_data2_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_data2_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_data2_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_method3_w(void)
{
	return 54;
}
static inline u32 ram_fc_method3_s(void)
{
	return 32;
}
static inline u32 ram_fc_method3_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_method3_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_method3_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_data3_w(void)
{
	return 55;
}
static inline u32 ram_fc_data3_s(void)
{
	return 32;
}
static inline u32 ram_fc_data3_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_data3_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_data3_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_spare56_w(void)
{
	return 56;
}
static inline u32 ram_fc_spare56_s(void)
{
	return 32;
}
static inline u32 ram_fc_spare56_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_spare56_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_spare56_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_hce_ctrl_w(void)
{
	return 57;
}
static inline u32 ram_fc_hce_ctrl_s(void)
{
	return 32;
}
static inline u32 ram_fc_hce_ctrl_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_hce_ctrl_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_hce_ctrl_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_chid_w(void)
{
	return 58;
}
static inline u32 ram_fc_chid_s(void)
{
	return 32;
}
static inline u32 ram_fc_chid_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_chid_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_chid_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_chid_id_w(void)
{
	return 0;
}
static inline u32 ram_fc_chid_id_s(void)
{
	return 12;
}
static inline u32 ram_fc_chid_id_f(u32 v)
{
	return (v & 0xfff) << 0;
}
static inline u32 ram_fc_chid_id_m(void)
{
	return 0xfff << 0;
}
static inline u32 ram_fc_chid_id_v(u32 r)
{
	return (r >> 0) & 0xfff;
}
static inline u32 ram_fc_spare58_w(void)
{
	return 58;
}
static inline u32 ram_fc_spare58_s(void)
{
	return 32;
}
static inline u32 ram_fc_spare58_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_spare58_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_spare58_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_gp_peek_w(void)
{
	return 59;
}
static inline u32 ram_fc_gp_peek_s(void)
{
	return 32;
}
static inline u32 ram_fc_gp_peek_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_gp_peek_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_gp_peek_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_pb_data2_w(void)
{
	return 60;
}
static inline u32 ram_fc_pb_data2_s(void)
{
	return 32;
}
static inline u32 ram_fc_pb_data2_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_pb_data2_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_pb_data2_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_l2_w(void)
{
	return 61;
}
static inline u32 ram_fc_l2_s(void)
{
	return 32;
}
static inline u32 ram_fc_l2_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_l2_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_l2_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_runlist_timeslice_w(void)
{
	return 62;
}
static inline u32 ram_fc_runlist_timeslice_s(void)
{
	return 32;
}
static inline u32 ram_fc_runlist_timeslice_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_runlist_timeslice_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_runlist_timeslice_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_eng_timeslice_w(void)
{
	return 62;
}
static inline u32 ram_fc_eng_timeslice_s(void)
{
	return 32;
}
static inline u32 ram_fc_eng_timeslice_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_eng_timeslice_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_eng_timeslice_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_pb_timeslice_w(void)
{
	return 63;
}
static inline u32 ram_fc_pb_timeslice_s(void)
{
	return 32;
}
static inline u32 ram_fc_pb_timeslice_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_pb_timeslice_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_pb_timeslice_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_base_shift_v(void)
{
	return 12;
}
static inline u32 ram_fc_map0_w(void)
{
	return 41;
}
static inline u32 ram_fc_map0_s(void)
{
	return 32;
}
static inline u32 ram_fc_map0_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_map0_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_map0_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_map1_w(void)
{
	return 42;
}
static inline u32 ram_fc_map1_s(void)
{
	return 32;
}
static inline u32 ram_fc_map1_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_map1_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_map1_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_spare57_w(void)
{
	return 57;
}
static inline u32 ram_fc_spare57_s(void)
{
	return 32;
}
static inline u32 ram_fc_spare57_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_fc_spare57_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_fc_spare57_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_fc_size_val_v(void)
{
	return 0x00000200;
}
static inline u32 ram_fc_host_fetch_size_val_v(void)
{
	return 0x00000180;
}
static inline u32 ram_userd_put_w(void)
{
	return 16;
}
static inline u32 ram_userd_put_s(void)
{
	return 32;
}
static inline u32 ram_userd_put_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_userd_put_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_userd_put_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_userd_get_w(void)
{
	return 17;
}
static inline u32 ram_userd_get_s(void)
{
	return 32;
}
static inline u32 ram_userd_get_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_userd_get_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_userd_get_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_userd_ref_w(void)
{
	return 18;
}
static inline u32 ram_userd_ref_s(void)
{
	return 32;
}
static inline u32 ram_userd_ref_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_userd_ref_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_userd_ref_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_userd_put_hi_w(void)
{
	return 19;
}
static inline u32 ram_userd_put_hi_s(void)
{
	return 32;
}
static inline u32 ram_userd_put_hi_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_userd_put_hi_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_userd_put_hi_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_userd_ref_threshold_w(void)
{
	return 20;
}
static inline u32 ram_userd_ref_threshold_s(void)
{
	return 32;
}
static inline u32 ram_userd_ref_threshold_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_userd_ref_threshold_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_userd_ref_threshold_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_userd_top_level_get_w(void)
{
	return 22;
}
static inline u32 ram_userd_top_level_get_s(void)
{
	return 32;
}
static inline u32 ram_userd_top_level_get_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_userd_top_level_get_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_userd_top_level_get_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_userd_top_level_get_hi_w(void)
{
	return 23;
}
static inline u32 ram_userd_top_level_get_hi_s(void)
{
	return 32;
}
static inline u32 ram_userd_top_level_get_hi_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_userd_top_level_get_hi_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_userd_top_level_get_hi_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_userd_get_hi_w(void)
{
	return 24;
}
static inline u32 ram_userd_get_hi_s(void)
{
	return 32;
}
static inline u32 ram_userd_get_hi_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_userd_get_hi_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_userd_get_hi_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_userd_gp_get_w(void)
{
	return 34;
}
static inline u32 ram_userd_gp_get_s(void)
{
	return 32;
}
static inline u32 ram_userd_gp_get_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_userd_gp_get_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_userd_gp_get_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_userd_gp_put_w(void)
{
	return 35;
}
static inline u32 ram_userd_gp_put_s(void)
{
	return 32;
}
static inline u32 ram_userd_gp_put_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_userd_gp_put_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_userd_gp_put_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_userd_base_shift_v(void)
{
	return 9;
}
static inline u32 ram_userd_chan_size_v(void)
{
	return 512;
}
static inline u32 ram_userd_gp_top_level_get_w(void)
{
	return 22;
}
static inline u32 ram_userd_gp_top_level_get_s(void)
{
	return 32;
}
static inline u32 ram_userd_gp_top_level_get_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_userd_gp_top_level_get_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_userd_gp_top_level_get_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_userd_gp_top_level_get_hi_w(void)
{
	return 23;
}
static inline u32 ram_userd_gp_top_level_get_hi_s(void)
{
	return 32;
}
static inline u32 ram_userd_gp_top_level_get_hi_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 ram_userd_gp_top_level_get_hi_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 ram_userd_gp_top_level_get_hi_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 ram_rl_entry_chid_w(void)
{
	return 0;
}
static inline u32 ram_rl_entry_chid_s(void)
{
	return 12;
}
static inline u32 ram_rl_entry_chid_f(u32 v)
{
	return (v & 0xfff) << 0;
}
static inline u32 ram_rl_entry_chid_m(void)
{
	return 0xfff << 0;
}
static inline u32 ram_rl_entry_chid_v(u32 r)
{
	return (r >> 0) & 0xfff;
}
static inline u32 ram_rl_entry_id_w(void)
{
	return 0;
}
static inline u32 ram_rl_entry_id_s(void)
{
	return 12;
}
static inline u32 ram_rl_entry_id_f(u32 v)
{
	return (v & 0xfff) << 0;
}
static inline u32 ram_rl_entry_id_m(void)
{
	return 0xfff << 0;
}
static inline u32 ram_rl_entry_id_v(u32 r)
{
	return (r >> 0) & 0xfff;
}
static inline u32 ram_rl_entry_id_hw_w(void)
{
	return 0;
}
static inline u32 ram_rl_entry_id_hw_s(void)
{
	return 7;
}
static inline u32 ram_rl_entry_id_hw_f(u32 v)
{
	return (v & 0x7f) << 0;
}
static inline u32 ram_rl_entry_id_hw_m(void)
{
	return 0x7f << 0;
}
static inline u32 ram_rl_entry_id_hw_v(u32 r)
{
	return (r >> 0) & 0x7f;
}
static inline u32 ram_rl_entry_id_max_v(void)
{
	return 128-1;
}
static inline u32 ram_rl_entry_type_w(void)
{
	return 0;
}
static inline u32 ram_rl_entry_type_s(void)
{
	return 1;
}
static inline u32 ram_rl_entry_type_f(u32 v)
{
	return (v & 0x1) << 13;
}
static inline u32 ram_rl_entry_type_m(void)
{
	return 0x1 << 13;
}
static inline u32 ram_rl_entry_type_v(u32 r)
{
	return (r >> 13) & 0x1;
}
static inline u32 ram_rl_entry_type_chid_v(void)
{
	return 0x00000000;
}
static inline u32 ram_rl_entry_type_chid_f(void)
{
	return 0x0;
}
static inline u32 ram_rl_entry_type_tsg_v(void)
{
	return 0x00000001;
}
static inline u32 ram_rl_entry_type_tsg_f(void)
{
	return 0x2000;
}
static inline u32 ram_rl_entry_timeslice_scale_w(void)
{
	return 0;
}
static inline u32 ram_rl_entry_timeslice_scale_s(void)
{
	return 4;
}
static inline u32 ram_rl_entry_timeslice_scale_f(u32 v)
{
	return (v & 0xf) << 14;
}
static inline u32 ram_rl_entry_timeslice_scale_m(void)
{
	return 0xf << 14;
}
static inline u32 ram_rl_entry_timeslice_scale_v(u32 r)
{
	return (r >> 14) & 0xf;
}
static inline u32 ram_rl_entry_timeslice_scale_3_v(void)
{
	return 0x00000003;
}
static inline u32 ram_rl_entry_timeslice_scale_3_f(void)
{
	return 0xc000;
}
static inline u32 ram_rl_entry_timeslice_timeout_w(void)
{
	return 0;
}
static inline u32 ram_rl_entry_timeslice_timeout_s(void)
{
	return 8;
}
static inline u32 ram_rl_entry_timeslice_timeout_f(u32 v)
{
	return (v & 0xff) << 18;
}
static inline u32 ram_rl_entry_timeslice_timeout_m(void)
{
	return 0xff << 18;
}
static inline u32 ram_rl_entry_timeslice_timeout_v(u32 r)
{
	return (r >> 18) & 0xff;
}
static inline u32 ram_rl_entry_timeslice_timeout_128_v(void)
{
	return 0x00000080;
}
static inline u32 ram_rl_entry_timeslice_timeout_128_f(void)
{
	return 0x2000000;
}
static inline u32 ram_rl_entry_tsg_length_w(void)
{
	return 0;
}
static inline u32 ram_rl_entry_tsg_length_s(void)
{
	return 6;
}
static inline u32 ram_rl_entry_tsg_length_f(u32 v)
{
	return (v & 0x3f) << 26;
}
static inline u32 ram_rl_entry_tsg_length_m(void)
{
	return 0x3f << 26;
}
static inline u32 ram_rl_entry_tsg_length_v(u32 r)
{
	return (r >> 26) & 0x3f;
}
static inline u32 ram_rl_entry_tsg_length_init_v(void)
{
	return 0x00000000;
}
static inline u32 ram_rl_entry_tsg_length_init_f(void)
{
	return 0x0;
}
static inline u32 ram_rl_entry_tsg_length_min_v(void)
{
	return 0x00000001;
}
static inline u32 ram_rl_entry_tsg_length_min_f(void)
{
	return 0x4000000;
}
static inline u32 ram_rl_entry_tsg_length_max_v(void)
{
	return 0x00000020;
}
static inline u32 ram_rl_entry_tsg_length_max_f(void)
{
	return 0x80000000;
}
static inline u32 ram_rl_entry_size_v(void)
{
	return 8;
}

#endif /* __hw_ram_gk20a_h__ */
