/*
 * drivers/video/tegra/host/gk20a/hw_therm_gk20a.h
 *
 * Copyright (c) 2012, NVIDIA Corporation.
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed in the hope it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

 /*
  * Function naming determines intended use:
  *
  *     <x>_r(void) : Returns the offset for register <x>.
  *
  *     <x>_w(void) : Returns the word offset for word (4 byte) element <x>.
  *
  *     <x>_<y>_s(void) : Returns size of field <y> of register <x> in bits.
  *
  *     <x>_<y>_f(u32 v) : Returns a value based on 'v' which has been shifted
  *         and masked to place it at field <y> of register <x>.  This value
  *         can be |'d with others to produce a full register value for
  *         register <x>.
  *
  *     <x>_<y>_m(void) : Returns a mask for field <y> of register <x>.  This
  *         value can be ~'d and then &'d to clear the value of field <y> for
  *         register <x>.
  *
  *     <x>_<y>_<z>_f(void) : Returns the constant value <z> after being shifted
  *         to place it at field <y> of register <x>.  This value can be |'d
  *         with others to produce a full register value for <x>.
  *
  *     <x>_<y>_v(u32 r) : Returns the value of field <y> from a full register
  *         <x> value 'r' after being shifted to place its LSB at bit 0.
  *         This value is suitable for direct comparison with other unshifted
  *         values appropriate for use in field <y> of register <x>.
  *
  *     <x>_<y>_<z>_v(void) : Returns the constant value for <z> defined for
  *         field <y> of register <x>.  This value is suitable for direct
  *         comparison with unshifted values appropriate for use in field <y>
  *         of register <x>.
  */

#ifndef __hw_therm_gk20a_h__
#define __hw_therm_gk20a_h__
/*This file is autogenerated.  Do not edit. */

static inline u32 therm_use_a_r(void)
{
	return 0x00020798;
}
static inline u32 therm_use_a__priv_level_mask_v(void)
{
	return 0x00000320;
}
static inline u32 therm_use_a_ext_therm_0_s(void)
{
	return 1;
}
static inline u32 therm_use_a_ext_therm_0_f(u32 v)
{
	return (v & 0x1) << 0;
}
static inline u32 therm_use_a_ext_therm_0_m(void)
{
	return 0x1 << 0;
}
static inline u32 therm_use_a_ext_therm_0_v(u32 r)
{
	return (r >> 0) & 0x1;
}
static inline u32 therm_use_a_ext_therm_0_no_v(void)
{
	return 0x00000000;
}
static inline u32 therm_use_a_ext_therm_0_no_f(void)
{
	return 0x0;
}
static inline u32 therm_use_a_ext_therm_0_yes_v(void)
{
	return 0x00000001;
}
static inline u32 therm_use_a_ext_therm_0_yes_f(void)
{
	return 0x1;
}
static inline u32 therm_use_a_ext_therm_1_s(void)
{
	return 1;
}
static inline u32 therm_use_a_ext_therm_1_f(u32 v)
{
	return (v & 0x1) << 1;
}
static inline u32 therm_use_a_ext_therm_1_m(void)
{
	return 0x1 << 1;
}
static inline u32 therm_use_a_ext_therm_1_v(u32 r)
{
	return (r >> 1) & 0x1;
}
static inline u32 therm_use_a_ext_therm_1_no_v(void)
{
	return 0x00000000;
}
static inline u32 therm_use_a_ext_therm_1_no_f(void)
{
	return 0x0;
}
static inline u32 therm_use_a_ext_therm_1_yes_v(void)
{
	return 0x00000001;
}
static inline u32 therm_use_a_ext_therm_1_yes_f(void)
{
	return 0x2;
}
static inline u32 therm_use_a_ext_therm_2_s(void)
{
	return 1;
}
static inline u32 therm_use_a_ext_therm_2_f(u32 v)
{
	return (v & 0x1) << 2;
}
static inline u32 therm_use_a_ext_therm_2_m(void)
{
	return 0x1 << 2;
}
static inline u32 therm_use_a_ext_therm_2_v(u32 r)
{
	return (r >> 2) & 0x1;
}
static inline u32 therm_use_a_ext_therm_2_no_v(void)
{
	return 0x00000000;
}
static inline u32 therm_use_a_ext_therm_2_no_f(void)
{
	return 0x0;
}
static inline u32 therm_use_a_ext_therm_2_yes_v(void)
{
	return 0x00000001;
}
static inline u32 therm_use_a_ext_therm_2_yes_f(void)
{
	return 0x4;
}
static inline u32 therm_use_a_global_idle_s(void)
{
	return 1;
}
static inline u32 therm_use_a_global_idle_f(u32 v)
{
	return (v & 0x1) << 10;
}
static inline u32 therm_use_a_global_idle_m(void)
{
	return 0x1 << 10;
}
static inline u32 therm_use_a_global_idle_v(u32 r)
{
	return (r >> 10) & 0x1;
}
static inline u32 therm_use_a_global_idle_no_v(void)
{
	return 0x00000000;
}
static inline u32 therm_use_a_global_idle_no_f(void)
{
	return 0x0;
}
static inline u32 therm_use_a_global_idle_yes_v(void)
{
	return 0x00000001;
}
static inline u32 therm_use_a_global_idle_yes_f(void)
{
	return 0x400;
}
static inline u32 therm_use_a_sw_s(void)
{
	return 1;
}
static inline u32 therm_use_a_sw_f(u32 v)
{
	return (v & 0x1) << 11;
}
static inline u32 therm_use_a_sw_m(void)
{
	return 0x1 << 11;
}
static inline u32 therm_use_a_sw_v(u32 r)
{
	return (r >> 11) & 0x1;
}
static inline u32 therm_use_a_sw_no_v(void)
{
	return 0x00000000;
}
static inline u32 therm_use_a_sw_no_f(void)
{
	return 0x0;
}
static inline u32 therm_use_a_sw_yes_v(void)
{
	return 0x00000001;
}
static inline u32 therm_use_a_sw_yes_f(void)
{
	return 0x800;
}
static inline u32 therm_use_a_ba_w0_t1h_s(void)
{
	return 1;
}
static inline u32 therm_use_a_ba_w0_t1h_f(u32 v)
{
	return (v & 0x1) << 20;
}
static inline u32 therm_use_a_ba_w0_t1h_m(void)
{
	return 0x1 << 20;
}
static inline u32 therm_use_a_ba_w0_t1h_v(u32 r)
{
	return (r >> 20) & 0x1;
}
static inline u32 therm_use_a_ba_w0_t1h_no_v(void)
{
	return 0x00000000;
}
static inline u32 therm_use_a_ba_w0_t1h_no_f(void)
{
	return 0x0;
}
static inline u32 therm_use_a_ba_w0_t1h_yes_v(void)
{
	return 0x00000001;
}
static inline u32 therm_use_a_ba_w0_t1h_yes_f(void)
{
	return 0x100000;
}
static inline u32 therm_use_a_ba_w0_t2h_s(void)
{
	return 1;
}
static inline u32 therm_use_a_ba_w0_t2h_f(u32 v)
{
	return (v & 0x1) << 21;
}
static inline u32 therm_use_a_ba_w0_t2h_m(void)
{
	return 0x1 << 21;
}
static inline u32 therm_use_a_ba_w0_t2h_v(u32 r)
{
	return (r >> 21) & 0x1;
}
static inline u32 therm_use_a_ba_w0_t2h_no_v(void)
{
	return 0x00000000;
}
static inline u32 therm_use_a_ba_w0_t2h_no_f(void)
{
	return 0x0;
}
static inline u32 therm_use_a_ba_w0_t2h_yes_v(void)
{
	return 0x00000001;
}
static inline u32 therm_use_a_ba_w0_t2h_yes_f(void)
{
	return 0x200000;
}
static inline u32 therm_use_a_ba_w1_t1h_s(void)
{
	return 1;
}
static inline u32 therm_use_a_ba_w1_t1h_f(u32 v)
{
	return (v & 0x1) << 22;
}
static inline u32 therm_use_a_ba_w1_t1h_m(void)
{
	return 0x1 << 22;
}
static inline u32 therm_use_a_ba_w1_t1h_v(u32 r)
{
	return (r >> 22) & 0x1;
}
static inline u32 therm_use_a_ba_w1_t1h_no_v(void)
{
	return 0x00000000;
}
static inline u32 therm_use_a_ba_w1_t1h_no_f(void)
{
	return 0x0;
}
static inline u32 therm_use_a_ba_w1_t1h_yes_v(void)
{
	return 0x00000001;
}
static inline u32 therm_use_a_ba_w1_t1h_yes_f(void)
{
	return 0x400000;
}
static inline u32 therm_use_a_ba_w1_t2h_s(void)
{
	return 1;
}
static inline u32 therm_use_a_ba_w1_t2h_f(u32 v)
{
	return (v & 0x1) << 23;
}
static inline u32 therm_use_a_ba_w1_t2h_m(void)
{
	return 0x1 << 23;
}
static inline u32 therm_use_a_ba_w1_t2h_v(u32 r)
{
	return (r >> 23) & 0x1;
}
static inline u32 therm_use_a_ba_w1_t2h_no_v(void)
{
	return 0x00000000;
}
static inline u32 therm_use_a_ba_w1_t2h_no_f(void)
{
	return 0x0;
}
static inline u32 therm_use_a_ba_w1_t2h_yes_v(void)
{
	return 0x00000001;
}
static inline u32 therm_use_a_ba_w1_t2h_yes_f(void)
{
	return 0x800000;
}
static inline u32 therm_use_a_ba_w2_t1h_s(void)
{
	return 1;
}
static inline u32 therm_use_a_ba_w2_t1h_f(u32 v)
{
	return (v & 0x1) << 24;
}
static inline u32 therm_use_a_ba_w2_t1h_m(void)
{
	return 0x1 << 24;
}
static inline u32 therm_use_a_ba_w2_t1h_v(u32 r)
{
	return (r >> 24) & 0x1;
}
static inline u32 therm_use_a_ba_w2_t1h_no_v(void)
{
	return 0x00000000;
}
static inline u32 therm_use_a_ba_w2_t1h_no_f(void)
{
	return 0x0;
}
static inline u32 therm_use_a_ba_w2_t1h_yes_v(void)
{
	return 0x00000001;
}
static inline u32 therm_use_a_ba_w2_t1h_yes_f(void)
{
	return 0x1000000;
}
static inline u32 therm_use_a_ba_w2_t2h_s(void)
{
	return 1;
}
static inline u32 therm_use_a_ba_w2_t2h_f(u32 v)
{
	return (v & 0x1) << 25;
}
static inline u32 therm_use_a_ba_w2_t2h_m(void)
{
	return 0x1 << 25;
}
static inline u32 therm_use_a_ba_w2_t2h_v(u32 r)
{
	return (r >> 25) & 0x1;
}
static inline u32 therm_use_a_ba_w2_t2h_no_v(void)
{
	return 0x00000000;
}
static inline u32 therm_use_a_ba_w2_t2h_no_f(void)
{
	return 0x0;
}
static inline u32 therm_use_a_ba_w2_t2h_yes_v(void)
{
	return 0x00000001;
}
static inline u32 therm_use_a_ba_w2_t2h_yes_f(void)
{
	return 0x2000000;
}
static inline u32 therm_evt_ext_therm_0_r(void)
{
	return 0x00020700;
}
static inline u32 therm_evt_ext_therm_0__priv_level_mask_v(void)
{
	return 0x00000320;
}
static inline u32 therm_evt_ext_therm_0_slow_factor_s(void)
{
	return 6;
}
static inline u32 therm_evt_ext_therm_0_slow_factor_f(u32 v)
{
	return (v & 0x3f) << 8;
}
static inline u32 therm_evt_ext_therm_0_slow_factor_m(void)
{
	return 0x3f << 8;
}
static inline u32 therm_evt_ext_therm_0_slow_factor_v(u32 r)
{
	return (r >> 8) & 0x3f;
}
static inline u32 therm_evt_ext_therm_0_slow_factor_disabled_v(void)
{
	return 0x00000000;
}
static inline u32 therm_evt_ext_therm_0_slow_factor_disabled_f(void)
{
	return 0x0;
}
static inline u32 therm_evt_ext_therm_0_slow_factor_init_v(void)
{
	return 0x00000000;
}
static inline u32 therm_evt_ext_therm_0_slow_factor_init_f(void)
{
	return 0x0;
}
static inline u32 therm_evt_ext_therm_0_slow_pwm_s(void)
{
	return 8;
}
static inline u32 therm_evt_ext_therm_0_slow_pwm_f(u32 v)
{
	return (v & 0xff) << 16;
}
static inline u32 therm_evt_ext_therm_0_slow_pwm_m(void)
{
	return 0xff << 16;
}
static inline u32 therm_evt_ext_therm_0_slow_pwm_v(u32 r)
{
	return (r >> 16) & 0xff;
}
static inline u32 therm_evt_ext_therm_0_slow_pwm_minpower_v(void)
{
	return 0x00000000;
}
static inline u32 therm_evt_ext_therm_0_slow_pwm_minpower_f(void)
{
	return 0x0;
}
static inline u32 therm_evt_ext_therm_0_slow_pwm_maxpower_v(void)
{
	return 0x000000ff;
}
static inline u32 therm_evt_ext_therm_0_slow_pwm_maxpower_f(void)
{
	return 0xff0000;
}
static inline u32 therm_evt_ext_therm_0_priority_s(void)
{
	return 5;
}
static inline u32 therm_evt_ext_therm_0_priority_f(u32 v)
{
	return (v & 0x1f) << 24;
}
static inline u32 therm_evt_ext_therm_0_priority_m(void)
{
	return 0x1f << 24;
}
static inline u32 therm_evt_ext_therm_0_priority_v(u32 r)
{
	return (r >> 24) & 0x1f;
}
static inline u32 therm_evt_ext_therm_0_priority_highest_v(void)
{
	return 0x00000000;
}
static inline u32 therm_evt_ext_therm_0_priority_highest_f(void)
{
	return 0x0;
}
static inline u32 therm_evt_ext_therm_0_priority_lowest_v(void)
{
	return 0x0000001f;
}
static inline u32 therm_evt_ext_therm_0_priority_lowest_f(void)
{
	return 0x1f000000;
}
static inline u32 therm_evt_ext_therm_0_priority_default_v(void)
{
	return 0x0000001f;
}
static inline u32 therm_evt_ext_therm_0_priority_default_f(void)
{
	return 0x1f000000;
}
static inline u32 therm_evt_ext_therm_1_r(void)
{
	return 0x00020704;
}
static inline u32 therm_evt_ext_therm_1__priv_level_mask_v(void)
{
	return 0x00000320;
}
static inline u32 therm_evt_ext_therm_1_slow_factor_s(void)
{
	return 6;
}
static inline u32 therm_evt_ext_therm_1_slow_factor_f(u32 v)
{
	return (v & 0x3f) << 8;
}
static inline u32 therm_evt_ext_therm_1_slow_factor_m(void)
{
	return 0x3f << 8;
}
static inline u32 therm_evt_ext_therm_1_slow_factor_v(u32 r)
{
	return (r >> 8) & 0x3f;
}
static inline u32 therm_evt_ext_therm_1_slow_factor_disabled_v(void)
{
	return 0x00000000;
}
static inline u32 therm_evt_ext_therm_1_slow_factor_disabled_f(void)
{
	return 0x0;
}
static inline u32 therm_evt_ext_therm_1_slow_factor_init_v(void)
{
	return 0x00000000;
}
static inline u32 therm_evt_ext_therm_1_slow_factor_init_f(void)
{
	return 0x0;
}
static inline u32 therm_evt_ext_therm_1_slow_pwm_s(void)
{
	return 8;
}
static inline u32 therm_evt_ext_therm_1_slow_pwm_f(u32 v)
{
	return (v & 0xff) << 16;
}
static inline u32 therm_evt_ext_therm_1_slow_pwm_m(void)
{
	return 0xff << 16;
}
static inline u32 therm_evt_ext_therm_1_slow_pwm_v(u32 r)
{
	return (r >> 16) & 0xff;
}
static inline u32 therm_evt_ext_therm_1_slow_pwm_minpower_v(void)
{
	return 0x00000000;
}
static inline u32 therm_evt_ext_therm_1_slow_pwm_minpower_f(void)
{
	return 0x0;
}
static inline u32 therm_evt_ext_therm_1_slow_pwm_maxpower_v(void)
{
	return 0x000000ff;
}
static inline u32 therm_evt_ext_therm_1_slow_pwm_maxpower_f(void)
{
	return 0xff0000;
}
static inline u32 therm_evt_ext_therm_1_priority_s(void)
{
	return 5;
}
static inline u32 therm_evt_ext_therm_1_priority_f(u32 v)
{
	return (v & 0x1f) << 24;
}
static inline u32 therm_evt_ext_therm_1_priority_m(void)
{
	return 0x1f << 24;
}
static inline u32 therm_evt_ext_therm_1_priority_v(u32 r)
{
	return (r >> 24) & 0x1f;
}
static inline u32 therm_evt_ext_therm_1_priority_highest_v(void)
{
	return 0x00000000;
}
static inline u32 therm_evt_ext_therm_1_priority_highest_f(void)
{
	return 0x0;
}
static inline u32 therm_evt_ext_therm_1_priority_lowest_v(void)
{
	return 0x0000001f;
}
static inline u32 therm_evt_ext_therm_1_priority_lowest_f(void)
{
	return 0x1f000000;
}
static inline u32 therm_evt_ext_therm_1_priority_default_v(void)
{
	return 0x0000001f;
}
static inline u32 therm_evt_ext_therm_1_priority_default_f(void)
{
	return 0x1f000000;
}
static inline u32 therm_evt_ext_therm_2_r(void)
{
	return 0x00020708;
}
static inline u32 therm_evt_ext_therm_2__priv_level_mask_v(void)
{
	return 0x00000320;
}
static inline u32 therm_evt_ext_therm_2_slow_factor_s(void)
{
	return 6;
}
static inline u32 therm_evt_ext_therm_2_slow_factor_f(u32 v)
{
	return (v & 0x3f) << 8;
}
static inline u32 therm_evt_ext_therm_2_slow_factor_m(void)
{
	return 0x3f << 8;
}
static inline u32 therm_evt_ext_therm_2_slow_factor_v(u32 r)
{
	return (r >> 8) & 0x3f;
}
static inline u32 therm_evt_ext_therm_2_slow_factor_disabled_v(void)
{
	return 0x00000000;
}
static inline u32 therm_evt_ext_therm_2_slow_factor_disabled_f(void)
{
	return 0x0;
}
static inline u32 therm_evt_ext_therm_2_slow_factor_init_v(void)
{
	return 0x00000000;
}
static inline u32 therm_evt_ext_therm_2_slow_factor_init_f(void)
{
	return 0x0;
}
static inline u32 therm_evt_ext_therm_2_slow_pwm_s(void)
{
	return 8;
}
static inline u32 therm_evt_ext_therm_2_slow_pwm_f(u32 v)
{
	return (v & 0xff) << 16;
}
static inline u32 therm_evt_ext_therm_2_slow_pwm_m(void)
{
	return 0xff << 16;
}
static inline u32 therm_evt_ext_therm_2_slow_pwm_v(u32 r)
{
	return (r >> 16) & 0xff;
}
static inline u32 therm_evt_ext_therm_2_slow_pwm_minpower_v(void)
{
	return 0x00000000;
}
static inline u32 therm_evt_ext_therm_2_slow_pwm_minpower_f(void)
{
	return 0x0;
}
static inline u32 therm_evt_ext_therm_2_slow_pwm_maxpower_v(void)
{
	return 0x000000ff;
}
static inline u32 therm_evt_ext_therm_2_slow_pwm_maxpower_f(void)
{
	return 0xff0000;
}
static inline u32 therm_evt_ext_therm_2_priority_s(void)
{
	return 5;
}
static inline u32 therm_evt_ext_therm_2_priority_f(u32 v)
{
	return (v & 0x1f) << 24;
}
static inline u32 therm_evt_ext_therm_2_priority_m(void)
{
	return 0x1f << 24;
}
static inline u32 therm_evt_ext_therm_2_priority_v(u32 r)
{
	return (r >> 24) & 0x1f;
}
static inline u32 therm_evt_ext_therm_2_priority_highest_v(void)
{
	return 0x00000000;
}
static inline u32 therm_evt_ext_therm_2_priority_highest_f(void)
{
	return 0x0;
}
static inline u32 therm_evt_ext_therm_2_priority_lowest_v(void)
{
	return 0x0000001f;
}
static inline u32 therm_evt_ext_therm_2_priority_lowest_f(void)
{
	return 0x1f000000;
}
static inline u32 therm_evt_ext_therm_2_priority_default_v(void)
{
	return 0x0000001f;
}
static inline u32 therm_evt_ext_therm_2_priority_default_f(void)
{
	return 0x1f000000;
}
static inline u32 therm_evt_ba_w0_t1h_r(void)
{
	return 0x00020750;
}
static inline u32 therm_evt_ba_w0_t1h__priv_level_mask_v(void)
{
	return 0x00000320;
}
static inline u32 therm_evt_ba_w0_t1h_slow_factor_s(void)
{
	return 6;
}
static inline u32 therm_evt_ba_w0_t1h_slow_factor_f(u32 v)
{
	return (v & 0x3f) << 8;
}
static inline u32 therm_evt_ba_w0_t1h_slow_factor_m(void)
{
	return 0x3f << 8;
}
static inline u32 therm_evt_ba_w0_t1h_slow_factor_v(u32 r)
{
	return (r >> 8) & 0x3f;
}
static inline u32 therm_evt_ba_w0_t1h_slow_factor_disabled_v(void)
{
	return 0x00000000;
}
static inline u32 therm_evt_ba_w0_t1h_slow_factor_disabled_f(void)
{
	return 0x0;
}
static inline u32 therm_evt_ba_w0_t1h_slow_factor_init_v(void)
{
	return 0x00000000;
}
static inline u32 therm_evt_ba_w0_t1h_slow_factor_init_f(void)
{
	return 0x0;
}
static inline u32 therm_evt_ba_w0_t1h_slow_pwm_s(void)
{
	return 8;
}
static inline u32 therm_evt_ba_w0_t1h_slow_pwm_f(u32 v)
{
	return (v & 0xff) << 16;
}
static inline u32 therm_evt_ba_w0_t1h_slow_pwm_m(void)
{
	return 0xff << 16;
}
static inline u32 therm_evt_ba_w0_t1h_slow_pwm_v(u32 r)
{
	return (r >> 16) & 0xff;
}
static inline u32 therm_evt_ba_w0_t1h_slow_pwm_minpower_v(void)
{
	return 0x00000000;
}
static inline u32 therm_evt_ba_w0_t1h_slow_pwm_minpower_f(void)
{
	return 0x0;
}
static inline u32 therm_evt_ba_w0_t1h_slow_pwm_maxpower_v(void)
{
	return 0x000000ff;
}
static inline u32 therm_evt_ba_w0_t1h_slow_pwm_maxpower_f(void)
{
	return 0xff0000;
}
static inline u32 therm_evt_ba_w0_t1h_priority_s(void)
{
	return 5;
}
static inline u32 therm_evt_ba_w0_t1h_priority_f(u32 v)
{
	return (v & 0x1f) << 24;
}
static inline u32 therm_evt_ba_w0_t1h_priority_m(void)
{
	return 0x1f << 24;
}
static inline u32 therm_evt_ba_w0_t1h_priority_v(u32 r)
{
	return (r >> 24) & 0x1f;
}
static inline u32 therm_evt_ba_w0_t1h_priority_highest_v(void)
{
	return 0x00000000;
}
static inline u32 therm_evt_ba_w0_t1h_priority_highest_f(void)
{
	return 0x0;
}
static inline u32 therm_evt_ba_w0_t1h_priority_lowest_v(void)
{
	return 0x0000001f;
}
static inline u32 therm_evt_ba_w0_t1h_priority_lowest_f(void)
{
	return 0x1f000000;
}
static inline u32 therm_evt_ba_w0_t1h_priority_default_v(void)
{
	return 0x0000001f;
}
static inline u32 therm_evt_ba_w0_t1h_priority_default_f(void)
{
	return 0x1f000000;
}
static inline u32 therm_ctrl_1_r(void)
{
	return 0x00020004;
}
static inline u32 therm_ctrl_1__priv_level_mask_v(void)
{
	return 0x00000320;
}
static inline u32 therm_ctrl_1_isob_disable_s(void)
{
	return 1;
}
static inline u32 therm_ctrl_1_isob_disable_f(u32 v)
{
	return (v & 0x1) << 21;
}
static inline u32 therm_ctrl_1_isob_disable_m(void)
{
	return 0x1 << 21;
}
static inline u32 therm_ctrl_1_isob_disable_v(u32 r)
{
	return (r >> 21) & 0x1;
}
static inline u32 therm_ctrl_1_isob_disable_off_v(void)
{
	return 0x00000000;
}
static inline u32 therm_ctrl_1_isob_disable_off_f(void)
{
	return 0x0;
}
static inline u32 therm_ctrl_1_isob_disable_on_v(void)
{
	return 0x00000001;
}
static inline u32 therm_ctrl_1_isob_disable_on_f(void)
{
	return 0x200000;
}
static inline u32 therm_ctrl_1_clk_slowdown_intr_gpcclk_s(void)
{
	return 1;
}
static inline u32 therm_ctrl_1_clk_slowdown_intr_gpcclk_f(u32 v)
{
	return (v & 0x1) << 24;
}
static inline u32 therm_ctrl_1_clk_slowdown_intr_gpcclk_m(void)
{
	return 0x1 << 24;
}
static inline u32 therm_ctrl_1_clk_slowdown_intr_gpcclk_v(u32 r)
{
	return (r >> 24) & 0x1;
}
static inline u32 therm_ctrl_1_clk_slowdown_intr_gpcclk_disable_v(void)
{
	return 0x00000000;
}
static inline u32 therm_ctrl_1_clk_slowdown_intr_gpcclk_disable_f(void)
{
	return 0x0;
}
static inline u32 therm_ctrl_1_clk_slowdown_intr_gpcclk_enable_v(void)
{
	return 0x00000001;
}
static inline u32 therm_ctrl_1_clk_slowdown_intr_gpcclk_enable_f(void)
{
	return 0x1000000;
}
static inline u32 therm_weight_1_r(void)
{
	return 0x00020024;
}
static inline u32 therm_weight_1__priv_level_mask_v(void)
{
	return 0x00000320;
}
static inline u32 therm_weight_1_hubmmu_s(void)
{
	return 5;
}
static inline u32 therm_weight_1_hubmmu_f(u32 v)
{
	return (v & 0x1f) << 8;
}
static inline u32 therm_weight_1_hubmmu_m(void)
{
	return 0x1f << 8;
}
static inline u32 therm_weight_1_hubmmu_v(u32 r)
{
	return (r >> 8) & 0x1f;
}
static inline u32 therm_weight_1_hubmmu_zero_v(void)
{
	return 0x00000000;
}
static inline u32 therm_weight_1_hubmmu_zero_f(void)
{
	return 0x0;
}
static inline u32 therm_weight_1_fe_s(void)
{
	return 5;
}
static inline u32 therm_weight_1_fe_f(u32 v)
{
	return (v & 0x1f) << 16;
}
static inline u32 therm_weight_1_fe_m(void)
{
	return 0x1f << 16;
}
static inline u32 therm_weight_1_fe_v(u32 r)
{
	return (r >> 16) & 0x1f;
}
static inline u32 therm_weight_1_fe_zero_v(void)
{
	return 0x00000000;
}
static inline u32 therm_weight_1_fe_zero_f(void)
{
	return 0x0;
}
static inline u32 therm_weight_1_xv_s(void)
{
	return 5;
}
static inline u32 therm_weight_1_xv_f(u32 v)
{
	return (v & 0x1f) << 24;
}
static inline u32 therm_weight_1_xv_m(void)
{
	return 0x1f << 24;
}
static inline u32 therm_weight_1_xv_v(u32 r)
{
	return (r >> 24) & 0x1f;
}
static inline u32 therm_weight_1_xv_zero_v(void)
{
	return 0x00000000;
}
static inline u32 therm_weight_1_xv_zero_f(void)
{
	return 0x0;
}
static inline u32 therm_peakpower_config1_r(u32 i)
{
	return 0x00020154+((i)*4);
}
static inline u32 therm_peakpower_config1__size_1_v(void)
{
	return 3;
}
static inline u32 therm_peakpower_config1__priv_level_mask_v(void)
{
	return 0x00000320;
}
static inline u32 therm_peakpower_config1_window_period_s(void)
{
	return 5;
}
static inline u32 therm_peakpower_config1_window_period_f(u32 v)
{
	return (v & 0x1f) << 0;
}
static inline u32 therm_peakpower_config1_window_period_m(void)
{
	return 0x1f << 0;
}
static inline u32 therm_peakpower_config1_window_period_v(u32 r)
{
	return (r >> 0) & 0x1f;
}
static inline u32 therm_peakpower_config1_window_period_max_v(void)
{
	return 0x00000015;
}
static inline u32 therm_peakpower_config1_window_period_max_f(void)
{
	return 0x15;
}
static inline u32 therm_peakpower_config1_window_period_128m_v(void)
{
	return 0x00000015;
}
static inline u32 therm_peakpower_config1_window_period_128m_f(void)
{
	return 0x15;
}
static inline u32 therm_peakpower_config1_window_period_64m_v(void)
{
	return 0x00000014;
}
static inline u32 therm_peakpower_config1_window_period_64m_f(void)
{
	return 0x14;
}
static inline u32 therm_peakpower_config1_window_period_32m_v(void)
{
	return 0x00000013;
}
static inline u32 therm_peakpower_config1_window_period_32m_f(void)
{
	return 0x13;
}
static inline u32 therm_peakpower_config1_window_period_16m_v(void)
{
	return 0x00000012;
}
static inline u32 therm_peakpower_config1_window_period_16m_f(void)
{
	return 0x12;
}
static inline u32 therm_peakpower_config1_window_period_8m_v(void)
{
	return 0x00000011;
}
static inline u32 therm_peakpower_config1_window_period_8m_f(void)
{
	return 0x11;
}
static inline u32 therm_peakpower_config1_window_period_4m_v(void)
{
	return 0x00000010;
}
static inline u32 therm_peakpower_config1_window_period_4m_f(void)
{
	return 0x10;
}
static inline u32 therm_peakpower_config1_window_period_2m_v(void)
{
	return 0x0000000f;
}
static inline u32 therm_peakpower_config1_window_period_2m_f(void)
{
	return 0xf;
}
static inline u32 therm_peakpower_config1_window_period_1m_v(void)
{
	return 0x0000000e;
}
static inline u32 therm_peakpower_config1_window_period_1m_f(void)
{
	return 0xe;
}
static inline u32 therm_peakpower_config1_window_period_512k_v(void)
{
	return 0x0000000d;
}
static inline u32 therm_peakpower_config1_window_period_512k_f(void)
{
	return 0xd;
}
static inline u32 therm_peakpower_config1_window_period_256k_v(void)
{
	return 0x0000000c;
}
static inline u32 therm_peakpower_config1_window_period_256k_f(void)
{
	return 0xc;
}
static inline u32 therm_peakpower_config1_window_period_128k_v(void)
{
	return 0x0000000b;
}
static inline u32 therm_peakpower_config1_window_period_128k_f(void)
{
	return 0xb;
}
static inline u32 therm_peakpower_config1_window_period_64k_v(void)
{
	return 0x0000000a;
}
static inline u32 therm_peakpower_config1_window_period_64k_f(void)
{
	return 0xa;
}
static inline u32 therm_peakpower_config1_window_period_32k_v(void)
{
	return 0x00000009;
}
static inline u32 therm_peakpower_config1_window_period_32k_f(void)
{
	return 0x9;
}
static inline u32 therm_peakpower_config1_window_period_16k_v(void)
{
	return 0x00000008;
}
static inline u32 therm_peakpower_config1_window_period_16k_f(void)
{
	return 0x8;
}
static inline u32 therm_peakpower_config1_window_period_8k_v(void)
{
	return 0x00000007;
}
static inline u32 therm_peakpower_config1_window_period_8k_f(void)
{
	return 0x7;
}
static inline u32 therm_peakpower_config1_window_period_4k_v(void)
{
	return 0x00000006;
}
static inline u32 therm_peakpower_config1_window_period_4k_f(void)
{
	return 0x6;
}
static inline u32 therm_peakpower_config1_window_period_2k_v(void)
{
	return 0x00000005;
}
static inline u32 therm_peakpower_config1_window_period_2k_f(void)
{
	return 0x5;
}
static inline u32 therm_peakpower_config1_window_period_1k_v(void)
{
	return 0x00000004;
}
static inline u32 therm_peakpower_config1_window_period_1k_f(void)
{
	return 0x4;
}
static inline u32 therm_peakpower_config1_window_period_512_v(void)
{
	return 0x00000003;
}
static inline u32 therm_peakpower_config1_window_period_512_f(void)
{
	return 0x3;
}
static inline u32 therm_peakpower_config1_window_period_256_v(void)
{
	return 0x00000002;
}
static inline u32 therm_peakpower_config1_window_period_256_f(void)
{
	return 0x2;
}
static inline u32 therm_peakpower_config1_window_period_128_v(void)
{
	return 0x00000001;
}
static inline u32 therm_peakpower_config1_window_period_128_f(void)
{
	return 0x1;
}
static inline u32 therm_peakpower_config1_window_period_64_v(void)
{
	return 0x00000000;
}
static inline u32 therm_peakpower_config1_window_period_64_f(void)
{
	return 0x0;
}
static inline u32 therm_peakpower_config1_window_period_min_v(void)
{
	return 0x00000000;
}
static inline u32 therm_peakpower_config1_window_period_min_f(void)
{
	return 0x0;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_s(void)
{
	return 6;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_f(u32 v)
{
	return (v & 0x3f) << 8;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_m(void)
{
	return 0x3f << 8;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_v(u32 r)
{
	return (r >> 8) & 0x3f;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_max_v(void)
{
	return 0x00000024;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_max_f(void)
{
	return 0x2400;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_36_v(void)
{
	return 0x00000024;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_36_f(void)
{
	return 0x2400;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_35_v(void)
{
	return 0x00000023;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_35_f(void)
{
	return 0x2300;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_34_v(void)
{
	return 0x00000022;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_34_f(void)
{
	return 0x2200;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_33_v(void)
{
	return 0x00000021;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_33_f(void)
{
	return 0x2100;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_32_v(void)
{
	return 0x00000020;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_32_f(void)
{
	return 0x2000;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_31_v(void)
{
	return 0x0000001f;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_31_f(void)
{
	return 0x1f00;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_30_v(void)
{
	return 0x0000001e;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_30_f(void)
{
	return 0x1e00;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_29_v(void)
{
	return 0x0000001d;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_29_f(void)
{
	return 0x1d00;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_28_v(void)
{
	return 0x0000001c;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_28_f(void)
{
	return 0x1c00;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_27_v(void)
{
	return 0x0000001b;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_27_f(void)
{
	return 0x1b00;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_26_v(void)
{
	return 0x0000001a;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_26_f(void)
{
	return 0x1a00;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_25_v(void)
{
	return 0x00000019;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_25_f(void)
{
	return 0x1900;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_24_v(void)
{
	return 0x00000018;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_24_f(void)
{
	return 0x1800;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_23_v(void)
{
	return 0x00000017;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_23_f(void)
{
	return 0x1700;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_22_v(void)
{
	return 0x00000016;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_22_f(void)
{
	return 0x1600;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_21_v(void)
{
	return 0x00000015;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_21_f(void)
{
	return 0x1500;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_20_v(void)
{
	return 0x00000014;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_20_f(void)
{
	return 0x1400;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_19_v(void)
{
	return 0x00000013;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_19_f(void)
{
	return 0x1300;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_18_v(void)
{
	return 0x00000012;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_18_f(void)
{
	return 0x1200;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_17_v(void)
{
	return 0x00000011;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_17_f(void)
{
	return 0x1100;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_16_v(void)
{
	return 0x00000010;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_16_f(void)
{
	return 0x1000;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_15_v(void)
{
	return 0x0000000f;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_15_f(void)
{
	return 0xf00;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_14_v(void)
{
	return 0x0000000e;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_14_f(void)
{
	return 0xe00;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_13_v(void)
{
	return 0x0000000d;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_13_f(void)
{
	return 0xd00;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_12_v(void)
{
	return 0x0000000c;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_12_f(void)
{
	return 0xc00;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_11_v(void)
{
	return 0x0000000b;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_11_f(void)
{
	return 0xb00;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_10_v(void)
{
	return 0x0000000a;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_10_f(void)
{
	return 0xa00;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_9_v(void)
{
	return 0x00000009;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_9_f(void)
{
	return 0x900;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_8_v(void)
{
	return 0x00000008;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_8_f(void)
{
	return 0x800;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_7_v(void)
{
	return 0x00000007;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_7_f(void)
{
	return 0x700;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_6_v(void)
{
	return 0x00000006;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_6_f(void)
{
	return 0x600;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_5_v(void)
{
	return 0x00000005;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_5_f(void)
{
	return 0x500;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_4_v(void)
{
	return 0x00000004;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_4_f(void)
{
	return 0x400;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_3_v(void)
{
	return 0x00000003;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_3_f(void)
{
	return 0x300;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_2_v(void)
{
	return 0x00000002;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_2_f(void)
{
	return 0x200;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_1_v(void)
{
	return 0x00000001;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_1_f(void)
{
	return 0x100;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_0_v(void)
{
	return 0x00000000;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_0_f(void)
{
	return 0x0;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_min_v(void)
{
	return 0x00000000;
}
static inline u32 therm_peakpower_config1_ba_sum_shift_min_f(void)
{
	return 0x0;
}
static inline u32 therm_peakpower_config1_win_sum_shift_s(void)
{
	return 4;
}
static inline u32 therm_peakpower_config1_win_sum_shift_f(u32 v)
{
	return (v & 0xf) << 16;
}
static inline u32 therm_peakpower_config1_win_sum_shift_m(void)
{
	return 0xf << 16;
}
static inline u32 therm_peakpower_config1_win_sum_shift_v(u32 r)
{
	return (r >> 16) & 0xf;
}
static inline u32 therm_peakpower_config1_win_sum_shift_max_v(void)
{
	return 0x00000008;
}
static inline u32 therm_peakpower_config1_win_sum_shift_max_f(void)
{
	return 0x80000;
}
static inline u32 therm_peakpower_config1_win_sum_shift_8_v(void)
{
	return 0x00000008;
}
static inline u32 therm_peakpower_config1_win_sum_shift_8_f(void)
{
	return 0x80000;
}
static inline u32 therm_peakpower_config1_win_sum_shift_7_v(void)
{
	return 0x00000007;
}
static inline u32 therm_peakpower_config1_win_sum_shift_7_f(void)
{
	return 0x70000;
}
static inline u32 therm_peakpower_config1_win_sum_shift_6_v(void)
{
	return 0x00000006;
}
static inline u32 therm_peakpower_config1_win_sum_shift_6_f(void)
{
	return 0x60000;
}
static inline u32 therm_peakpower_config1_win_sum_shift_5_v(void)
{
	return 0x00000005;
}
static inline u32 therm_peakpower_config1_win_sum_shift_5_f(void)
{
	return 0x50000;
}
static inline u32 therm_peakpower_config1_win_sum_shift_4_v(void)
{
	return 0x00000004;
}
static inline u32 therm_peakpower_config1_win_sum_shift_4_f(void)
{
	return 0x40000;
}
static inline u32 therm_peakpower_config1_win_sum_shift_3_v(void)
{
	return 0x00000003;
}
static inline u32 therm_peakpower_config1_win_sum_shift_3_f(void)
{
	return 0x30000;
}
static inline u32 therm_peakpower_config1_win_sum_shift_2_v(void)
{
	return 0x00000002;
}
static inline u32 therm_peakpower_config1_win_sum_shift_2_f(void)
{
	return 0x20000;
}
static inline u32 therm_peakpower_config1_win_sum_shift_1_v(void)
{
	return 0x00000001;
}
static inline u32 therm_peakpower_config1_win_sum_shift_1_f(void)
{
	return 0x10000;
}
static inline u32 therm_peakpower_config1_win_sum_shift_0_v(void)
{
	return 0x00000000;
}
static inline u32 therm_peakpower_config1_win_sum_shift_0_f(void)
{
	return 0x0;
}
static inline u32 therm_peakpower_config1_win_sum_shift_min_v(void)
{
	return 0x00000000;
}
static inline u32 therm_peakpower_config1_win_sum_shift_min_f(void)
{
	return 0x0;
}
static inline u32 therm_peakpower_config1_window_rst_s(void)
{
	return 1;
}
static inline u32 therm_peakpower_config1_window_rst_f(u32 v)
{
	return (v & 0x1) << 30;
}
static inline u32 therm_peakpower_config1_window_rst_m(void)
{
	return 0x1 << 30;
}
static inline u32 therm_peakpower_config1_window_rst_v(u32 r)
{
	return (r >> 30) & 0x1;
}
static inline u32 therm_peakpower_config1_window_rst_init_v(void)
{
	return 0x00000000;
}
static inline u32 therm_peakpower_config1_window_rst_init_f(void)
{
	return 0x0;
}
static inline u32 therm_peakpower_config1_window_rst_cleared_v(void)
{
	return 0x00000000;
}
static inline u32 therm_peakpower_config1_window_rst_cleared_f(void)
{
	return 0x0;
}
static inline u32 therm_peakpower_config1_window_rst_trigger_v(void)
{
	return 0x00000001;
}
static inline u32 therm_peakpower_config1_window_rst_trigger_f(void)
{
	return 0x40000000;
}
static inline u32 therm_peakpower_config1_window_en_s(void)
{
	return 1;
}
static inline u32 therm_peakpower_config1_window_en_f(u32 v)
{
	return (v & 0x1) << 31;
}
static inline u32 therm_peakpower_config1_window_en_m(void)
{
	return 0x1 << 31;
}
static inline u32 therm_peakpower_config1_window_en_v(u32 r)
{
	return (r >> 31) & 0x1;
}
static inline u32 therm_peakpower_config1_window_en_disabled_v(void)
{
	return 0x00000000;
}
static inline u32 therm_peakpower_config1_window_en_disabled_f(void)
{
	return 0x0;
}
static inline u32 therm_peakpower_config1_window_en_enabled_v(void)
{
	return 0x00000001;
}
static inline u32 therm_peakpower_config1_window_en_enabled_f(void)
{
	return 0x80000000;
}
static inline u32 therm_peakpower_config2_r(u32 i)
{
	return 0x00020170+((i)*4);
}
static inline u32 therm_peakpower_config2__size_1_v(void)
{
	return 3;
}
static inline u32 therm_peakpower_config2__priv_level_mask_v(void)
{
	return 0x00000320;
}
static inline u32 therm_peakpower_config2_ba_threshold_1h_val_s(void)
{
	return 31;
}
static inline u32 therm_peakpower_config2_ba_threshold_1h_val_f(u32 v)
{
	return (v & 0x7fffffff) << 0;
}
static inline u32 therm_peakpower_config2_ba_threshold_1h_val_m(void)
{
	return 0x7fffffff << 0;
}
static inline u32 therm_peakpower_config2_ba_threshold_1h_val_v(u32 r)
{
	return (r >> 0) & 0x7fffffff;
}
static inline u32 therm_peakpower_config2_ba_threshold_1h_val_init_v(void)
{
	return 0x00000000;
}
static inline u32 therm_peakpower_config2_ba_threshold_1h_val_init_f(void)
{
	return 0x0;
}
static inline u32 therm_peakpower_config2_ba_threshold_1h_en_s(void)
{
	return 1;
}
static inline u32 therm_peakpower_config2_ba_threshold_1h_en_f(u32 v)
{
	return (v & 0x1) << 31;
}
static inline u32 therm_peakpower_config2_ba_threshold_1h_en_m(void)
{
	return 0x1 << 31;
}
static inline u32 therm_peakpower_config2_ba_threshold_1h_en_v(u32 r)
{
	return (r >> 31) & 0x1;
}
static inline u32 therm_peakpower_config2_ba_threshold_1h_en_disabled_v(void)
{
	return 0x00000000;
}
static inline u32 therm_peakpower_config2_ba_threshold_1h_en_disabled_f(void)
{
	return 0x0;
}
static inline u32 therm_peakpower_config2_ba_threshold_1h_en_enabled_v(void)
{
	return 0x00000001;
}
static inline u32 therm_peakpower_config2_ba_threshold_1h_en_enabled_f(void)
{
	return 0x80000000;
}
static inline u32 therm_peakpower_config4_r(u32 i)
{
	return 0x000201c0+((i)*4);
}
static inline u32 therm_peakpower_config4__size_1_v(void)
{
	return 3;
}
static inline u32 therm_peakpower_config4__priv_level_mask_v(void)
{
	return 0x00000320;
}
static inline u32 therm_peakpower_config4_ba_threshold_1l_val_s(void)
{
	return 31;
}
static inline u32 therm_peakpower_config4_ba_threshold_1l_val_f(u32 v)
{
	return (v & 0x7fffffff) << 0;
}
static inline u32 therm_peakpower_config4_ba_threshold_1l_val_m(void)
{
	return 0x7fffffff << 0;
}
static inline u32 therm_peakpower_config4_ba_threshold_1l_val_v(u32 r)
{
	return (r >> 0) & 0x7fffffff;
}
static inline u32 therm_peakpower_config4_ba_threshold_1l_val_init_v(void)
{
	return 0x00000000;
}
static inline u32 therm_peakpower_config4_ba_threshold_1l_val_init_f(void)
{
	return 0x0;
}
static inline u32 therm_peakpower_config4_ba_threshold_1l_en_s(void)
{
	return 1;
}
static inline u32 therm_peakpower_config4_ba_threshold_1l_en_f(u32 v)
{
	return (v & 0x1) << 31;
}
static inline u32 therm_peakpower_config4_ba_threshold_1l_en_m(void)
{
	return 0x1 << 31;
}
static inline u32 therm_peakpower_config4_ba_threshold_1l_en_v(u32 r)
{
	return (r >> 31) & 0x1;
}
static inline u32 therm_peakpower_config4_ba_threshold_1l_en_disabled_v(void)
{
	return 0x00000000;
}
static inline u32 therm_peakpower_config4_ba_threshold_1l_en_disabled_f(void)
{
	return 0x0;
}
static inline u32 therm_peakpower_config4_ba_threshold_1l_en_enabled_v(void)
{
	return 0x00000001;
}
static inline u32 therm_peakpower_config4_ba_threshold_1l_en_enabled_f(void)
{
	return 0x80000000;
}
static inline u32 therm_peakpower_config6_r(u32 i)
{
	return 0x00020270+((i)*4);
}
static inline u32 therm_peakpower_config6__size_1_v(void)
{
	return 3;
}
static inline u32 therm_peakpower_config6__priv_level_mask_v(void)
{
	return 0x00000320;
}
static inline u32 therm_peakpower_config6_trigger_cfg_1h_s(void)
{
	return 2;
}
static inline u32 therm_peakpower_config6_trigger_cfg_1h_f(u32 v)
{
	return (v & 0x3) << 20;
}
static inline u32 therm_peakpower_config6_trigger_cfg_1h_m(void)
{
	return 0x3 << 20;
}
static inline u32 therm_peakpower_config6_trigger_cfg_1h_v(u32 r)
{
	return (r >> 20) & 0x3;
}
static inline u32 therm_peakpower_config6_trigger_cfg_1h_init_v(void)
{
	return 0x00000000;
}
static inline u32 therm_peakpower_config6_trigger_cfg_1h_init_f(void)
{
	return 0x0;
}
static inline u32 therm_peakpower_config6_trigger_cfg_1h_none_v(void)
{
	return 0x00000000;
}
static inline u32 therm_peakpower_config6_trigger_cfg_1h_none_f(void)
{
	return 0x0;
}
static inline u32 therm_peakpower_config6_trigger_cfg_1h_rsvd1_v(void)
{
	return 0x00000001;
}
static inline u32 therm_peakpower_config6_trigger_cfg_1h_rsvd1_f(void)
{
	return 0x100000;
}
static inline u32 therm_peakpower_config6_trigger_cfg_1h_intr_v(void)
{
	return 0x00000002;
}
static inline u32 therm_peakpower_config6_trigger_cfg_1h_intr_f(void)
{
	return 0x200000;
}
static inline u32 therm_peakpower_config6_trigger_cfg_1h_rsvd2_v(void)
{
	return 0x00000003;
}
static inline u32 therm_peakpower_config6_trigger_cfg_1h_rsvd2_f(void)
{
	return 0x300000;
}
static inline u32 therm_peakpower_config6_trigger_cfg_1l_s(void)
{
	return 1;
}
static inline u32 therm_peakpower_config6_trigger_cfg_1l_f(u32 v)
{
	return (v & 0x1) << 22;
}
static inline u32 therm_peakpower_config6_trigger_cfg_1l_m(void)
{
	return 0x1 << 22;
}
static inline u32 therm_peakpower_config6_trigger_cfg_1l_v(u32 r)
{
	return (r >> 22) & 0x1;
}
static inline u32 therm_peakpower_config6_trigger_cfg_1l_init_v(void)
{
	return 0x00000000;
}
static inline u32 therm_peakpower_config6_trigger_cfg_1l_init_f(void)
{
	return 0x0;
}
static inline u32 therm_peakpower_config6_trigger_cfg_1l_none_v(void)
{
	return 0x00000000;
}
static inline u32 therm_peakpower_config6_trigger_cfg_1l_none_f(void)
{
	return 0x0;
}
static inline u32 therm_peakpower_config6_trigger_cfg_1l_intr_v(void)
{
	return 0x00000001;
}
static inline u32 therm_peakpower_config6_trigger_cfg_1l_intr_f(void)
{
	return 0x400000;
}
static inline u32 therm_peakpower_config8_r(u32 i)
{
	return 0x000202e8+((i)*4);
}
static inline u32 therm_peakpower_config8__size_1_v(void)
{
	return 3;
}
static inline u32 therm_peakpower_config8__priv_level_mask_v(void)
{
	return 0x00000320;
}
static inline u32 therm_peakpower_config8_factor_a_s(void)
{
	return 8;
}
static inline u32 therm_peakpower_config8_factor_a_f(u32 v)
{
	return (v & 0xff) << 0;
}
static inline u32 therm_peakpower_config8_factor_a_m(void)
{
	return 0xff << 0;
}
static inline u32 therm_peakpower_config8_factor_a_v(u32 r)
{
	return (r >> 0) & 0xff;
}
static inline u32 therm_peakpower_config8_factor_a_init_v(void)
{
	return 0x00000000;
}
static inline u32 therm_peakpower_config8_factor_a_init_f(void)
{
	return 0x0;
}
static inline u32 therm_peakpower_config9_r(u32 i)
{
	return 0x000202f4+((i)*4);
}
static inline u32 therm_peakpower_config9__size_1_v(void)
{
	return 3;
}
static inline u32 therm_peakpower_config9__priv_level_mask_v(void)
{
	return 0x00000320;
}
static inline u32 therm_peakpower_config9_leakage_c_s(void)
{
	return 30;
}
static inline u32 therm_peakpower_config9_leakage_c_f(u32 v)
{
	return (v & 0x3fffffff) << 0;
}
static inline u32 therm_peakpower_config9_leakage_c_m(void)
{
	return 0x3fffffff << 0;
}
static inline u32 therm_peakpower_config9_leakage_c_v(u32 r)
{
	return (r >> 0) & 0x3fffffff;
}
static inline u32 therm_peakpower_config9_leakage_c_init_v(void)
{
	return 0x00000000;
}
static inline u32 therm_peakpower_config9_leakage_c_init_f(void)
{
	return 0x0;
}
static inline u32 therm_config1_r(void)
{
	return 0x00020050;
}
static inline u32 therm_config1__priv_level_mask_v(void)
{
	return 0x00000320;
}
static inline u32 therm_config1_pwm_period_s(void)
{
	return 3;
}
static inline u32 therm_config1_pwm_period_f(u32 v)
{
	return (v & 0x7) << 0;
}
static inline u32 therm_config1_pwm_period_m(void)
{
	return 0x7 << 0;
}
static inline u32 therm_config1_pwm_period_v(u32 r)
{
	return (r >> 0) & 0x7;
}
static inline u32 therm_config1_pwm_period_512_v(void)
{
	return 0x00000007;
}
static inline u32 therm_config1_pwm_period_512_f(void)
{
	return 0x7;
}
static inline u32 therm_config1_pwm_period_max_v(void)
{
	return 0x00000007;
}
static inline u32 therm_config1_pwm_period_max_f(void)
{
	return 0x7;
}
static inline u32 therm_config1_pwm_period_256_v(void)
{
	return 0x00000006;
}
static inline u32 therm_config1_pwm_period_256_f(void)
{
	return 0x6;
}
static inline u32 therm_config1_pwm_period_128_v(void)
{
	return 0x00000005;
}
static inline u32 therm_config1_pwm_period_128_f(void)
{
	return 0x5;
}
static inline u32 therm_config1_pwm_period_64_v(void)
{
	return 0x00000004;
}
static inline u32 therm_config1_pwm_period_64_f(void)
{
	return 0x4;
}
static inline u32 therm_config1_pwm_period_32_v(void)
{
	return 0x00000003;
}
static inline u32 therm_config1_pwm_period_32_f(void)
{
	return 0x3;
}
static inline u32 therm_config1_pwm_period_16_v(void)
{
	return 0x00000002;
}
static inline u32 therm_config1_pwm_period_16_f(void)
{
	return 0x2;
}
static inline u32 therm_config1_pwm_period_min_v(void)
{
	return 0x00000002;
}
static inline u32 therm_config1_pwm_period_min_f(void)
{
	return 0x2;
}
static inline u32 therm_config1_ba_enable_s(void)
{
	return 1;
}
static inline u32 therm_config1_ba_enable_f(u32 v)
{
	return (v & 0x1) << 20;
}
static inline u32 therm_config1_ba_enable_m(void)
{
	return 0x1 << 20;
}
static inline u32 therm_config1_ba_enable_v(u32 r)
{
	return (r >> 20) & 0x1;
}
static inline u32 therm_config1_ba_enable_no_v(void)
{
	return 0x00000000;
}
static inline u32 therm_config1_ba_enable_no_f(void)
{
	return 0x0;
}
static inline u32 therm_config1_ba_enable_yes_v(void)
{
	return 0x00000001;
}
static inline u32 therm_config1_ba_enable_yes_f(void)
{
	return 0x100000;
}
static inline u32 therm_config2_r(void)
{
	return 0x00020130;
}
static inline u32 therm_config2__priv_level_mask_v(void)
{
	return 0x00000320;
}
static inline u32 therm_config2_grad_pwm_period_s(void)
{
	return 4;
}
static inline u32 therm_config2_grad_pwm_period_f(u32 v)
{
	return (v & 0xf) << 0;
}
static inline u32 therm_config2_grad_pwm_period_m(void)
{
	return 0xf << 0;
}
static inline u32 therm_config2_grad_pwm_period_v(u32 r)
{
	return (r >> 0) & 0xf;
}
static inline u32 therm_config2_grad_pwm_period_max_v(void)
{
	return 0x0000000f;
}
static inline u32 therm_config2_grad_pwm_period_max_f(void)
{
	return 0xf;
}
static inline u32 therm_config2_grad_pwm_period_128k_v(void)
{
	return 0x0000000f;
}
static inline u32 therm_config2_grad_pwm_period_128k_f(void)
{
	return 0xf;
}
static inline u32 therm_config2_grad_pwm_period_64k_v(void)
{
	return 0x0000000e;
}
static inline u32 therm_config2_grad_pwm_period_64k_f(void)
{
	return 0xe;
}
static inline u32 therm_config2_grad_pwm_period_32k_v(void)
{
	return 0x0000000d;
}
static inline u32 therm_config2_grad_pwm_period_32k_f(void)
{
	return 0xd;
}
static inline u32 therm_config2_grad_pwm_period_16k_v(void)
{
	return 0x0000000c;
}
static inline u32 therm_config2_grad_pwm_period_16k_f(void)
{
	return 0xc;
}
static inline u32 therm_config2_grad_pwm_period_8k_v(void)
{
	return 0x0000000b;
}
static inline u32 therm_config2_grad_pwm_period_8k_f(void)
{
	return 0xb;
}
static inline u32 therm_config2_grad_pwm_period_4k_v(void)
{
	return 0x0000000a;
}
static inline u32 therm_config2_grad_pwm_period_4k_f(void)
{
	return 0xa;
}
static inline u32 therm_config2_grad_pwm_period_2k_v(void)
{
	return 0x00000009;
}
static inline u32 therm_config2_grad_pwm_period_2k_f(void)
{
	return 0x9;
}
static inline u32 therm_config2_grad_pwm_period_1k_v(void)
{
	return 0x00000008;
}
static inline u32 therm_config2_grad_pwm_period_1k_f(void)
{
	return 0x8;
}
static inline u32 therm_config2_grad_pwm_period_512_v(void)
{
	return 0x00000007;
}
static inline u32 therm_config2_grad_pwm_period_512_f(void)
{
	return 0x7;
}
static inline u32 therm_config2_grad_pwm_period_256_v(void)
{
	return 0x00000006;
}
static inline u32 therm_config2_grad_pwm_period_256_f(void)
{
	return 0x6;
}
static inline u32 therm_config2_grad_pwm_period_128_v(void)
{
	return 0x00000005;
}
static inline u32 therm_config2_grad_pwm_period_128_f(void)
{
	return 0x5;
}
static inline u32 therm_config2_grad_pwm_period_64_v(void)
{
	return 0x00000004;
}
static inline u32 therm_config2_grad_pwm_period_64_f(void)
{
	return 0x4;
}
static inline u32 therm_config2_grad_pwm_period_32_v(void)
{
	return 0x00000003;
}
static inline u32 therm_config2_grad_pwm_period_32_f(void)
{
	return 0x3;
}
static inline u32 therm_config2_grad_pwm_period_16_v(void)
{
	return 0x00000002;
}
static inline u32 therm_config2_grad_pwm_period_16_f(void)
{
	return 0x2;
}
static inline u32 therm_config2_grad_pwm_period_8_v(void)
{
	return 0x00000001;
}
static inline u32 therm_config2_grad_pwm_period_8_f(void)
{
	return 0x1;
}
static inline u32 therm_config2_grad_pwm_period_4_v(void)
{
	return 0x00000000;
}
static inline u32 therm_config2_grad_pwm_period_4_f(void)
{
	return 0x0;
}
static inline u32 therm_config2_grad_step_duration_s(void)
{
	return 4;
}
static inline u32 therm_config2_grad_step_duration_f(u32 v)
{
	return (v & 0xf) << 8;
}
static inline u32 therm_config2_grad_step_duration_m(void)
{
	return 0xf << 8;
}
static inline u32 therm_config2_grad_step_duration_v(u32 r)
{
	return (r >> 8) & 0xf;
}
static inline u32 therm_config2_grad_step_duration_128k_v(void)
{
	return 0x0000000f;
}
static inline u32 therm_config2_grad_step_duration_128k_f(void)
{
	return 0xf00;
}
static inline u32 therm_config2_grad_step_duration_512_v(void)
{
	return 0x00000007;
}
static inline u32 therm_config2_grad_step_duration_512_f(void)
{
	return 0x700;
}
static inline u32 therm_config2_grad_step_duration_256_v(void)
{
	return 0x00000006;
}
static inline u32 therm_config2_grad_step_duration_256_f(void)
{
	return 0x600;
}
static inline u32 therm_config2_grad_step_duration_128_v(void)
{
	return 0x00000005;
}
static inline u32 therm_config2_grad_step_duration_128_f(void)
{
	return 0x500;
}
static inline u32 therm_config2_grad_step_duration_64_v(void)
{
	return 0x00000004;
}
static inline u32 therm_config2_grad_step_duration_64_f(void)
{
	return 0x400;
}
static inline u32 therm_config2_grad_step_duration_32_v(void)
{
	return 0x00000003;
}
static inline u32 therm_config2_grad_step_duration_32_f(void)
{
	return 0x300;
}
static inline u32 therm_config2_grad_step_duration_16_v(void)
{
	return 0x00000002;
}
static inline u32 therm_config2_grad_step_duration_16_f(void)
{
	return 0x200;
}
static inline u32 therm_config2_grad_step_duration_8_v(void)
{
	return 0x00000001;
}
static inline u32 therm_config2_grad_step_duration_8_f(void)
{
	return 0x100;
}
static inline u32 therm_config2_grad_step_duration_4_v(void)
{
	return 0x00000000;
}
static inline u32 therm_config2_grad_step_duration_4_f(void)
{
	return 0x0;
}
static inline u32 therm_config2_grad_step_duration_cycle_s(void)
{
	return 4;
}
static inline u32 therm_config2_grad_step_duration_cycle_f(u32 v)
{
	return (v & 0xf) << 12;
}
static inline u32 therm_config2_grad_step_duration_cycle_m(void)
{
	return 0xf << 12;
}
static inline u32 therm_config2_grad_step_duration_cycle_v(u32 r)
{
	return (r >> 12) & 0xf;
}
static inline u32 therm_config2_grad_step_duration_cycle_init_v(void)
{
	return 0x00000001;
}
static inline u32 therm_config2_grad_step_duration_cycle_init_f(void)
{
	return 0x1000;
}
static inline u32 therm_config2_grad_step_duration_cycle_1_v(void)
{
	return 0x00000001;
}
static inline u32 therm_config2_grad_step_duration_cycle_1_f(void)
{
	return 0x1000;
}
static inline u32 therm_config2_grad_step_duration_cycle_2_v(void)
{
	return 0x00000002;
}
static inline u32 therm_config2_grad_step_duration_cycle_2_f(void)
{
	return 0x2000;
}
static inline u32 therm_config2_grad_step_duration_cycle_4_v(void)
{
	return 0x00000004;
}
static inline u32 therm_config2_grad_step_duration_cycle_4_f(void)
{
	return 0x4000;
}
static inline u32 therm_config2_grad_step_duration_cycle_8_v(void)
{
	return 0x00000008;
}
static inline u32 therm_config2_grad_step_duration_cycle_8_f(void)
{
	return 0x8000;
}
static inline u32 therm_config2_slowdown_factor_extended_s(void)
{
	return 1;
}
static inline u32 therm_config2_slowdown_factor_extended_f(u32 v)
{
	return (v & 0x1) << 24;
}
static inline u32 therm_config2_slowdown_factor_extended_m(void)
{
	return 0x1 << 24;
}
static inline u32 therm_config2_slowdown_factor_extended_v(u32 r)
{
	return (r >> 24) & 0x1;
}
static inline u32 therm_config2_slowdown_factor_extended_init_v(void)
{
	return 0x00000000;
}
static inline u32 therm_config2_slowdown_factor_extended_init_f(void)
{
	return 0x0;
}
static inline u32 therm_config2_grad_enable_s(void)
{
	return 1;
}
static inline u32 therm_config2_grad_enable_f(u32 v)
{
	return (v & 0x1) << 31;
}
static inline u32 therm_config2_grad_enable_m(void)
{
	return 0x1 << 31;
}
static inline u32 therm_config2_grad_enable_v(u32 r)
{
	return (r >> 31) & 0x1;
}
static inline u32 therm_config2_grad_enable_init_v(void)
{
	return 0x00000000;
}
static inline u32 therm_config2_grad_enable_init_f(void)
{
	return 0x0;
}
static inline u32 therm_clk_slowdown_0_r(u32 i)
{
	return 0x00020160+((i)*4);
}
static inline u32 therm_clk_slowdown_0__size_1_v(void)
{
	return 1;
}
static inline u32 therm_clk_slowdown_0__priv_level_mask_v(void)
{
	return 0x00000320;
}
static inline u32 therm_clk_slowdown_0_hw_failsafe_factor_s(void)
{
	return 6;
}
static inline u32 therm_clk_slowdown_0_hw_failsafe_factor_f(u32 v)
{
	return (v & 0x3f) << 0;
}
static inline u32 therm_clk_slowdown_0_hw_failsafe_factor_m(void)
{
	return 0x3f << 0;
}
static inline u32 therm_clk_slowdown_0_hw_failsafe_factor_v(u32 r)
{
	return (r >> 0) & 0x3f;
}
static inline u32 therm_clk_slowdown_0_hw_failsafe_factor_disabled_v(void)
{
	return 0x00000000;
}
static inline u32 therm_clk_slowdown_0_hw_failsafe_factor_disabled_f(void)
{
	return 0x0;
}
static inline u32 therm_clk_slowdown_0_hw_failsafe_factor_div2_v(void)
{
	return 0x00000001;
}
static inline u32 therm_clk_slowdown_0_hw_failsafe_factor_div2_f(void)
{
	return 0x1;
}
static inline u32 therm_clk_slowdown_0_hw_failsafe_factor_div4_v(void)
{
	return 0x00000002;
}
static inline u32 therm_clk_slowdown_0_hw_failsafe_factor_div4_f(void)
{
	return 0x2;
}
static inline u32 therm_clk_slowdown_0_hw_failsafe_factor_div8_v(void)
{
	return 0x00000003;
}
static inline u32 therm_clk_slowdown_0_hw_failsafe_factor_div8_f(void)
{
	return 0x3;
}
static inline u32 therm_clk_slowdown_0_hw_failsafe_factor_div16_v(void)
{
	return 0x00000004;
}
static inline u32 therm_clk_slowdown_0_hw_failsafe_factor_div16_f(void)
{
	return 0x4;
}
static inline u32 therm_clk_slowdown_0_hw_failsafe_use_local_s(void)
{
	return 1;
}
static inline u32 therm_clk_slowdown_0_hw_failsafe_use_local_f(u32 v)
{
	return (v & 0x1) << 7;
}
static inline u32 therm_clk_slowdown_0_hw_failsafe_use_local_m(void)
{
	return 0x1 << 7;
}
static inline u32 therm_clk_slowdown_0_hw_failsafe_use_local_v(u32 r)
{
	return (r >> 7) & 0x1;
}
static inline u32 therm_clk_slowdown_0_hw_failsafe_use_local_no_v(void)
{
	return 0x00000000;
}
static inline u32 therm_clk_slowdown_0_hw_failsafe_use_local_no_f(void)
{
	return 0x0;
}
static inline u32 therm_clk_slowdown_0_hw_failsafe_use_local_yes_v(void)
{
	return 0x00000001;
}
static inline u32 therm_clk_slowdown_0_hw_failsafe_use_local_yes_f(void)
{
	return 0x80;
}
static inline u32 therm_clk_slowdown_0_hw_failsafe_pwm_s(void)
{
	return 8;
}
static inline u32 therm_clk_slowdown_0_hw_failsafe_pwm_f(u32 v)
{
	return (v & 0xff) << 8;
}
static inline u32 therm_clk_slowdown_0_hw_failsafe_pwm_m(void)
{
	return 0xff << 8;
}
static inline u32 therm_clk_slowdown_0_hw_failsafe_pwm_v(u32 r)
{
	return (r >> 8) & 0xff;
}
static inline u32 therm_clk_slowdown_0_hw_failsafe_pwm_minpower_v(void)
{
	return 0x00000000;
}
static inline u32 therm_clk_slowdown_0_hw_failsafe_pwm_minpower_f(void)
{
	return 0x0;
}
static inline u32 therm_clk_slowdown_0_hw_failsafe_pwm_maxpower_v(void)
{
	return 0x000000ff;
}
static inline u32 therm_clk_slowdown_0_hw_failsafe_pwm_maxpower_f(void)
{
	return 0xff00;
}
static inline u32 therm_clk_slowdown_0_idle_factor_s(void)
{
	return 6;
}
static inline u32 therm_clk_slowdown_0_idle_factor_f(u32 v)
{
	return (v & 0x3f) << 16;
}
static inline u32 therm_clk_slowdown_0_idle_factor_m(void)
{
	return 0x3f << 16;
}
static inline u32 therm_clk_slowdown_0_idle_factor_v(u32 r)
{
	return (r >> 16) & 0x3f;
}
static inline u32 therm_clk_slowdown_0_idle_factor_disabled_v(void)
{
	return 0x00000000;
}
static inline u32 therm_clk_slowdown_0_idle_factor_disabled_f(void)
{
	return 0x0;
}
static inline u32 therm_clk_slowdown_0_idle_factor_div2_v(void)
{
	return 0x00000001;
}
static inline u32 therm_clk_slowdown_0_idle_factor_div2_f(void)
{
	return 0x10000;
}
static inline u32 therm_clk_slowdown_0_idle_factor_div4_v(void)
{
	return 0x00000002;
}
static inline u32 therm_clk_slowdown_0_idle_factor_div4_f(void)
{
	return 0x20000;
}
static inline u32 therm_clk_slowdown_0_idle_factor_div8_v(void)
{
	return 0x00000003;
}
static inline u32 therm_clk_slowdown_0_idle_factor_div8_f(void)
{
	return 0x30000;
}
static inline u32 therm_clk_slowdown_0_idle_factor_div16_v(void)
{
	return 0x00000004;
}
static inline u32 therm_clk_slowdown_0_idle_factor_div16_f(void)
{
	return 0x40000;
}
static inline u32 therm_clk_slowdown_0_idle_pwm_s(void)
{
	return 8;
}
static inline u32 therm_clk_slowdown_0_idle_pwm_f(u32 v)
{
	return (v & 0xff) << 24;
}
static inline u32 therm_clk_slowdown_0_idle_pwm_m(void)
{
	return 0xff << 24;
}
static inline u32 therm_clk_slowdown_0_idle_pwm_v(u32 r)
{
	return (r >> 24) & 0xff;
}
static inline u32 therm_clk_slowdown_0_idle_pwm_minpower_v(void)
{
	return 0x00000000;
}
static inline u32 therm_clk_slowdown_0_idle_pwm_minpower_f(void)
{
	return 0x0;
}
static inline u32 therm_clk_slowdown_0_idle_pwm_maxpower_v(void)
{
	return 0x000000ff;
}
static inline u32 therm_clk_slowdown_0_idle_pwm_maxpower_f(void)
{
	return 0xff000000;
}
static inline u32 therm_clk_slowdown_1_r(u32 i)
{
	return 0x00020180+((i)*4);
}
static inline u32 therm_clk_slowdown_1__size_1_v(void)
{
	return 1;
}
static inline u32 therm_clk_slowdown_1__priv_level_mask_v(void)
{
	return 0x00000320;
}
static inline u32 therm_clk_slowdown_1_sw_therm_factor_s(void)
{
	return 6;
}
static inline u32 therm_clk_slowdown_1_sw_therm_factor_f(u32 v)
{
	return (v & 0x3f) << 0;
}
static inline u32 therm_clk_slowdown_1_sw_therm_factor_m(void)
{
	return 0x3f << 0;
}
static inline u32 therm_clk_slowdown_1_sw_therm_factor_v(u32 r)
{
	return (r >> 0) & 0x3f;
}
static inline u32 therm_clk_slowdown_1_sw_therm_factor_disabled_v(void)
{
	return 0x00000000;
}
static inline u32 therm_clk_slowdown_1_sw_therm_factor_disabled_f(void)
{
	return 0x0;
}
static inline u32 therm_clk_slowdown_1_sw_therm_factor_div2_v(void)
{
	return 0x00000001;
}
static inline u32 therm_clk_slowdown_1_sw_therm_factor_div2_f(void)
{
	return 0x1;
}
static inline u32 therm_clk_slowdown_1_sw_therm_factor_div4_v(void)
{
	return 0x00000002;
}
static inline u32 therm_clk_slowdown_1_sw_therm_factor_div4_f(void)
{
	return 0x2;
}
static inline u32 therm_clk_slowdown_1_sw_therm_factor_div8_v(void)
{
	return 0x00000003;
}
static inline u32 therm_clk_slowdown_1_sw_therm_factor_div8_f(void)
{
	return 0x3;
}
static inline u32 therm_clk_slowdown_1_sw_therm_factor_div16_v(void)
{
	return 0x00000004;
}
static inline u32 therm_clk_slowdown_1_sw_therm_factor_div16_f(void)
{
	return 0x4;
}
static inline u32 therm_clk_slowdown_1_sw_therm_pwm_s(void)
{
	return 8;
}
static inline u32 therm_clk_slowdown_1_sw_therm_pwm_f(u32 v)
{
	return (v & 0xff) << 8;
}
static inline u32 therm_clk_slowdown_1_sw_therm_pwm_m(void)
{
	return 0xff << 8;
}
static inline u32 therm_clk_slowdown_1_sw_therm_pwm_v(u32 r)
{
	return (r >> 8) & 0xff;
}
static inline u32 therm_clk_slowdown_1_sw_therm_pwm_minpower_v(void)
{
	return 0x00000000;
}
static inline u32 therm_clk_slowdown_1_sw_therm_pwm_minpower_f(void)
{
	return 0x0;
}
static inline u32 therm_clk_slowdown_1_sw_therm_pwm_maxpower_v(void)
{
	return 0x000000ff;
}
static inline u32 therm_clk_slowdown_1_sw_therm_pwm_maxpower_f(void)
{
	return 0xff00;
}
static inline u32 therm_gate_ctrl_r(u32 i)
{
	return 0x00020200+((i)*4);
}
static inline u32 therm_gate_ctrl__size_1_v(void)
{
	return 24;
}
static inline u32 therm_gate_ctrl__priv_level_mask_v(void)
{
	return 0x0000032c;
}
static inline u32 therm_gate_ctrl_eng_clk_s(void)
{
	return 2;
}
static inline u32 therm_gate_ctrl_eng_clk_f(u32 v)
{
	return (v & 0x3) << 0;
}
static inline u32 therm_gate_ctrl_eng_clk_m(void)
{
	return 0x3 << 0;
}
static inline u32 therm_gate_ctrl_eng_clk_v(u32 r)
{
	return (r >> 0) & 0x3;
}
static inline u32 therm_gate_ctrl_eng_clk_run_v(void)
{
	return 0x00000000;
}
static inline u32 therm_gate_ctrl_eng_clk_run_f(void)
{
	return 0x0;
}
static inline u32 therm_gate_ctrl_eng_clk_auto_v(void)
{
	return 0x00000001;
}
static inline u32 therm_gate_ctrl_eng_clk_auto_f(void)
{
	return 0x1;
}
static inline u32 therm_gate_ctrl_eng_clk_stop_v(void)
{
	return 0x00000002;
}
static inline u32 therm_gate_ctrl_eng_clk_stop_f(void)
{
	return 0x2;
}
static inline u32 therm_gate_ctrl_blk_clk_s(void)
{
	return 2;
}
static inline u32 therm_gate_ctrl_blk_clk_f(u32 v)
{
	return (v & 0x3) << 2;
}
static inline u32 therm_gate_ctrl_blk_clk_m(void)
{
	return 0x3 << 2;
}
static inline u32 therm_gate_ctrl_blk_clk_v(u32 r)
{
	return (r >> 2) & 0x3;
}
static inline u32 therm_gate_ctrl_blk_clk_run_v(void)
{
	return 0x00000000;
}
static inline u32 therm_gate_ctrl_blk_clk_run_f(void)
{
	return 0x0;
}
static inline u32 therm_gate_ctrl_blk_clk_auto_v(void)
{
	return 0x00000001;
}
static inline u32 therm_gate_ctrl_blk_clk_auto_f(void)
{
	return 0x4;
}
static inline u32 therm_gate_ctrl_eng_pwr_s(void)
{
	return 2;
}
static inline u32 therm_gate_ctrl_eng_pwr_f(u32 v)
{
	return (v & 0x3) << 4;
}
static inline u32 therm_gate_ctrl_eng_pwr_m(void)
{
	return 0x3 << 4;
}
static inline u32 therm_gate_ctrl_eng_pwr_v(u32 r)
{
	return (r >> 4) & 0x3;
}
static inline u32 therm_gate_ctrl_eng_pwr_on_v(void)
{
	return 0x00000000;
}
static inline u32 therm_gate_ctrl_eng_pwr_on_f(void)
{
	return 0x0;
}
static inline u32 therm_gate_ctrl_eng_pwr_auto_v(void)
{
	return 0x00000001;
}
static inline u32 therm_gate_ctrl_eng_pwr_auto_f(void)
{
	return 0x10;
}
static inline u32 therm_gate_ctrl_eng_pwr_off_v(void)
{
	return 0x00000002;
}
static inline u32 therm_gate_ctrl_eng_pwr_off_f(void)
{
	return 0x20;
}
static inline u32 therm_gate_ctrl_blk_pwr_s(void)
{
	return 2;
}
static inline u32 therm_gate_ctrl_blk_pwr_f(u32 v)
{
	return (v & 0x3) << 6;
}
static inline u32 therm_gate_ctrl_blk_pwr_m(void)
{
	return 0x3 << 6;
}
static inline u32 therm_gate_ctrl_blk_pwr_v(u32 r)
{
	return (r >> 6) & 0x3;
}
static inline u32 therm_gate_ctrl_blk_pwr_on_v(void)
{
	return 0x00000000;
}
static inline u32 therm_gate_ctrl_blk_pwr_on_f(void)
{
	return 0x0;
}
static inline u32 therm_gate_ctrl_blk_pwr_auto_v(void)
{
	return 0x00000001;
}
static inline u32 therm_gate_ctrl_blk_pwr_auto_f(void)
{
	return 0x40;
}
static inline u32 therm_gate_ctrl_eng_idle_filt_exp_s(void)
{
	return 5;
}
static inline u32 therm_gate_ctrl_eng_idle_filt_exp_f(u32 v)
{
	return (v & 0x1f) << 8;
}
static inline u32 therm_gate_ctrl_eng_idle_filt_exp_m(void)
{
	return 0x1f << 8;
}
static inline u32 therm_gate_ctrl_eng_idle_filt_exp_v(u32 r)
{
	return (r >> 8) & 0x1f;
}
static inline u32 therm_gate_ctrl_eng_idle_filt_exp_init_v(void)
{
	return 0x00000004;
}
static inline u32 therm_gate_ctrl_eng_idle_filt_exp_init_f(void)
{
	return 0x400;
}
static inline u32 therm_gate_ctrl_eng_idle_filt_exp_max_v(void)
{
	return 0x0000001f;
}
static inline u32 therm_gate_ctrl_eng_idle_filt_exp_max_f(void)
{
	return 0x1f00;
}
static inline u32 therm_gate_ctrl_eng_idle_filt_exp__prod_v(void)
{
	return 0x00000002;
}
static inline u32 therm_gate_ctrl_eng_idle_filt_exp__prod_f(void)
{
	return 0x200;
}
static inline u32 therm_gate_ctrl_eng_idle_filt_mant_s(void)
{
	return 3;
}
static inline u32 therm_gate_ctrl_eng_idle_filt_mant_f(u32 v)
{
	return (v & 0x7) << 13;
}
static inline u32 therm_gate_ctrl_eng_idle_filt_mant_m(void)
{
	return 0x7 << 13;
}
static inline u32 therm_gate_ctrl_eng_idle_filt_mant_v(u32 r)
{
	return (r >> 13) & 0x7;
}
static inline u32 therm_gate_ctrl_eng_idle_filt_mant_init_v(void)
{
	return 0x00000001;
}
static inline u32 therm_gate_ctrl_eng_idle_filt_mant_init_f(void)
{
	return 0x2000;
}
static inline u32 therm_gate_ctrl_eng_idle_filt_mant_max_v(void)
{
	return 0x00000007;
}
static inline u32 therm_gate_ctrl_eng_idle_filt_mant_max_f(void)
{
	return 0xe000;
}
static inline u32 therm_gate_ctrl_eng_idle_filt_mant__prod_v(void)
{
	return 0x00000001;
}
static inline u32 therm_gate_ctrl_eng_idle_filt_mant__prod_f(void)
{
	return 0x2000;
}
static inline u32 therm_gate_ctrl_eng_delay_before_s(void)
{
	return 4;
}
static inline u32 therm_gate_ctrl_eng_delay_before_f(u32 v)
{
	return (v & 0xf) << 16;
}
static inline u32 therm_gate_ctrl_eng_delay_before_m(void)
{
	return 0xf << 16;
}
static inline u32 therm_gate_ctrl_eng_delay_before_v(u32 r)
{
	return (r >> 16) & 0xf;
}
static inline u32 therm_gate_ctrl_eng_delay_before_min_v(void)
{
	return 0x00000000;
}
static inline u32 therm_gate_ctrl_eng_delay_before_min_f(void)
{
	return 0x0;
}
static inline u32 therm_gate_ctrl_eng_delay_before_init_v(void)
{
	return 0x00000002;
}
static inline u32 therm_gate_ctrl_eng_delay_before_init_f(void)
{
	return 0x20000;
}
static inline u32 therm_gate_ctrl_eng_delay_before_max_v(void)
{
	return 0x0000000f;
}
static inline u32 therm_gate_ctrl_eng_delay_before_max_f(void)
{
	return 0xf0000;
}
static inline u32 therm_gate_ctrl_eng_delay_before__prod_v(void)
{
	return 0x00000000;
}
static inline u32 therm_gate_ctrl_eng_delay_before__prod_f(void)
{
	return 0x0;
}
static inline u32 therm_gate_ctrl_eng_delay_after_s(void)
{
	return 4;
}
static inline u32 therm_gate_ctrl_eng_delay_after_f(u32 v)
{
	return (v & 0xf) << 20;
}
static inline u32 therm_gate_ctrl_eng_delay_after_m(void)
{
	return 0xf << 20;
}
static inline u32 therm_gate_ctrl_eng_delay_after_v(u32 r)
{
	return (r >> 20) & 0xf;
}
static inline u32 therm_gate_ctrl_eng_delay_after_min_v(void)
{
	return 0x00000000;
}
static inline u32 therm_gate_ctrl_eng_delay_after_min_f(void)
{
	return 0x0;
}
static inline u32 therm_gate_ctrl_eng_delay_after_init_v(void)
{
	return 0x00000007;
}
static inline u32 therm_gate_ctrl_eng_delay_after_init_f(void)
{
	return 0x700000;
}
static inline u32 therm_gate_ctrl_eng_delay_after_max_v(void)
{
	return 0x0000000f;
}
static inline u32 therm_gate_ctrl_eng_delay_after_max_f(void)
{
	return 0xf00000;
}
static inline u32 therm_gate_ctrl_eng_delay_after__prod_v(void)
{
	return 0x00000000;
}
static inline u32 therm_gate_ctrl_eng_delay_after__prod_f(void)
{
	return 0x0;
}
static inline u32 therm_gate_ctrl_blk_ovr_delay_before_s(void)
{
	return 4;
}
static inline u32 therm_gate_ctrl_blk_ovr_delay_before_f(u32 v)
{
	return (v & 0xf) << 24;
}
static inline u32 therm_gate_ctrl_blk_ovr_delay_before_m(void)
{
	return 0xf << 24;
}
static inline u32 therm_gate_ctrl_blk_ovr_delay_before_v(u32 r)
{
	return (r >> 24) & 0xf;
}
static inline u32 therm_gate_ctrl_blk_ovr_delay_before_min_v(void)
{
	return 0x00000000;
}
static inline u32 therm_gate_ctrl_blk_ovr_delay_before_min_f(void)
{
	return 0x0;
}
static inline u32 therm_gate_ctrl_blk_ovr_delay_before_init_v(void)
{
	return 0x00000002;
}
static inline u32 therm_gate_ctrl_blk_ovr_delay_before_init_f(void)
{
	return 0x2000000;
}
static inline u32 therm_gate_ctrl_blk_ovr_delay_before_max_v(void)
{
	return 0x0000000f;
}
static inline u32 therm_gate_ctrl_blk_ovr_delay_before_max_f(void)
{
	return 0xf000000;
}
static inline u32 therm_gate_ctrl_blk_ovr_delay_after_s(void)
{
	return 4;
}
static inline u32 therm_gate_ctrl_blk_ovr_delay_after_f(u32 v)
{
	return (v & 0xf) << 28;
}
static inline u32 therm_gate_ctrl_blk_ovr_delay_after_m(void)
{
	return 0xf << 28;
}
static inline u32 therm_gate_ctrl_blk_ovr_delay_after_v(u32 r)
{
	return (r >> 28) & 0xf;
}
static inline u32 therm_gate_ctrl_blk_ovr_delay_after_min_v(void)
{
	return 0x00000000;
}
static inline u32 therm_gate_ctrl_blk_ovr_delay_after_min_f(void)
{
	return 0x0;
}
static inline u32 therm_gate_ctrl_blk_ovr_delay_after_init_v(void)
{
	return 0x00000002;
}
static inline u32 therm_gate_ctrl_blk_ovr_delay_after_init_f(void)
{
	return 0x20000000;
}
static inline u32 therm_gate_ctrl_blk_ovr_delay_after_max_v(void)
{
	return 0x0000000f;
}
static inline u32 therm_gate_ctrl_blk_ovr_delay_after_max_f(void)
{
	return 0xf0000000;
}
static inline u32 therm_fecs_idle_filter_r(void)
{
	return 0x00020288;
}
static inline u32 therm_fecs_idle_filter__priv_level_mask_v(void)
{
	return 0x0000032c;
}
static inline u32 therm_fecs_idle_filter_value_s(void)
{
	return 32;
}
static inline u32 therm_fecs_idle_filter_value_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 therm_fecs_idle_filter_value_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 therm_fecs_idle_filter_value_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 therm_fecs_idle_filter_value_init_v(void)
{
	return 0x00000000;
}
static inline u32 therm_fecs_idle_filter_value_init_f(void)
{
	return 0x0;
}
static inline u32 therm_fecs_idle_filter_value_max_v(void)
{
	return 0xffffffff;
}
static inline u32 therm_fecs_idle_filter_value_max_f(void)
{
	return 0xffffffff;
}
static inline u32 therm_fecs_idle_filter_value__prod_v(void)
{
	return 0x00000000;
}
static inline u32 therm_fecs_idle_filter_value__prod_f(void)
{
	return 0x0;
}
static inline u32 therm_hubmmu_idle_filter_r(void)
{
	return 0x0002028c;
}
static inline u32 therm_hubmmu_idle_filter__priv_level_mask_v(void)
{
	return 0x0000032c;
}
static inline u32 therm_hubmmu_idle_filter_value_s(void)
{
	return 32;
}
static inline u32 therm_hubmmu_idle_filter_value_f(u32 v)
{
	return (v & 0xffffffff) << 0;
}
static inline u32 therm_hubmmu_idle_filter_value_m(void)
{
	return 0xffffffff << 0;
}
static inline u32 therm_hubmmu_idle_filter_value_v(u32 r)
{
	return (r >> 0) & 0xffffffff;
}
static inline u32 therm_hubmmu_idle_filter_value_init_v(void)
{
	return 0x00000000;
}
static inline u32 therm_hubmmu_idle_filter_value_init_f(void)
{
	return 0x0;
}
static inline u32 therm_hubmmu_idle_filter_value_max_v(void)
{
	return 0xffffffff;
}
static inline u32 therm_hubmmu_idle_filter_value_max_f(void)
{
	return 0xffffffff;
}
static inline u32 therm_hubmmu_idle_filter_value__prod_v(void)
{
	return 0x00000000;
}
static inline u32 therm_hubmmu_idle_filter_value__prod_f(void)
{
	return 0x0;
}

#endif /* __hw_therm_gk20a_h__ */
