GCOV_PROFILE := y
EXTRA_CFLAGS += -Idrivers/video/tegra/host

nvhost-t124-objs  = \
	t124.o \
	as_t124.o \
	intr_t124.o \
	cdma_t124.o \
	3dctx_t124.o \
	debug_t124.o

obj-$(CONFIG_TEGRA_GRHOST) += nvhost-t124.o
