GCOV_PROFILE := y

subdir-ccflags-y := -Werror

obj-$(CONFIG_VIDEO_ISC)	+= isc_gpio.o
obj-$(CONFIG_VIDEO_ISC)	+= isc_mgr.o
obj-$(CONFIG_VIDEO_ISC)	+= isc_dev.o
obj-$(CONFIG_VIDEO_ISC)	+= isc_pwm.o
obj-$(CONFIG_VIDEO_ISC)	+= debugfs.o
