GCOV_PROFILE := y
subdir-ccflags-y := -Werror
ccflags-y += -Idrivers/video/tegra -Idrivers/video/tegra/dc -I$(srctree)/arch/arm/mach-tegra
obj-y += nvdisp.o
obj-y += nvdisp_win.o
obj-y += nvdisp_stub.o
