GCOV_PROFILE_pinctrl-tegra186-padctl.o := y

ccflags-y += -Werror
ccflags-y += -I$(srctree)/drivers/pinctrl
obj-$(CONFIG_PINCTRL_TEGRA186)  += pinctrl-tegra186.o
obj-$(CONFIG_PINCTRL_TEGRA186_PADCTL) += pinctrl-tegra186-padctl.o
