GCOV_PROFILE_pinctrl-tegra194-padctl.o := y

ccflags-y += -Werror
ccflags-y += -I$(srctree)/drivers/pinctrl
ccflags-y += -I$(srctree)/drivers/pinctrl/tegra
ccflags-y += -I$(srctree)/drivers/video/tegra/host
ccflags-y += -I$(srctree)/../nvhost/drivers/video/tegra/host
ccflags-y += -I$(srctree)/../nvhost/include

obj-$(CONFIG_PINCTRL_TEGRA194)  += pinctrl-tegra194.o
obj-$(CONFIG_PINCTRL_TEGRA194_PADCTL) += pinctrl-tegra194-padctl.o
